### ISSUE TITLE
Meeting session initialize not working with multiple window (Electron app)

### ISSUE THREAD

**Issue by kalpeshims** [aws/amazon-chime-sdk-js#1009]
Hello, 

I am trying to render attendee video list with audio on second window  on screen share start, once the screen share stoped the videos of attendee list should be render on main window.

Facing issue::
It get stop on second window

Code :: 
Update code into ChimeSdkWrapper.ts recall the chime sdk for second window. even set the meeting id, attendee id as received from the parent window using localStorage but not able to render audio/videos even attendee list into second window.

code looks like below
![image](https://user-images.githubusercontent.com/53003080/104446060-e8eea300-55bf-11eb-867e-731e1f0937ff.png)

so, how to solve my issue.

Thanks.

**Comment by nicklera1** [comment]
Hi @kalpeshims,

Sounds like 1 meeting (window) get canceled by the 2nd window since you are reusing same meetingInfo and attendee. Its drops one for the other.  

You could try creating another attended (Roaster attendee) and join a meeting with "Roaster attendee" and only utilize what you need out of it. another way is to setup [BroadcastChannel](https://developer.mozilla.org/en-US/docs/Web/API/BroadcastChannel) where you could send data between two different windows as needed using single meetingSession context.

**Comment by devalevenkatesh** [comment]
Closing this issue as we do not need further action here. Request you to open new issue if you have more questions.
