### ISSUE TITLE
Horizontal video flip for live streaming inverts text

### ISSUE THREAD

**Issue by rmarcet** [aws/amazon-chime-sdk-js#1021]
The situation I experience is live streaming where I'm whiteboarding or diagraming on paper, and any written text appears backward or horizontally inverted.  There does not appear to be an option to "uncheck" this in the video settings.  I've tried on two separate webcams. The horizontal flip would not be an issue otherwise.  

**Screenshots**

![Chime](https://user-images.githubusercontent.com/77805648/105405549-448ce200-5bf9-11eb-9207-b449f2a3bf3a.jpg)

**Platform**
 - OS: Windows 10
 - Browser: Chrome
 - Browser Version: Version 87.0.4280.141
 - Amazon Chime SDK GitHub Commit:

**Comment by anuranduttaroy** [comment]
Hey @rmarcet can you please confirm whether you are using the Amazon Chime Javascript SDK or the Amazon Chime native app?

**Comment by rmarcet** [comment]
Native app

**Comment by tedfar** [comment]
Having the same issue on MacOS, Chime native app 

- MacOS 10.15.7
- Chime for Mac Build #1.0.210977.0, Version: 4.36.8260
- Camera: IPEVO V4K document camera.  

The picture is not flipped in zoom or their provided Visualizer viewer.

**Comment by rnewman** [comment]
Thanks for commenting, @tedfar and @rmarcet.

This repo is for the Amazon Chime SDK — the code that developers use to add video and voice to their applications — not for the Amazon Chime app. The best way to get support for the app is through AWS support.

I’m asking some experts about whether it’s possible to turn off the mirroring of the local video tile in the native Chime app. 

The mirroring should only be present in your own self-view, and is there because it’s comforting to most users: if you connect a second participant to the meeting, they *should* see the video with no flip. Could you confirm?

As a workaround, you might be able to use the web app at https://app.chime.aws, and use your browser developer tools to add CSS to the self-view video element:

```css
-moz-transform: scale(-1, 1);
-webkit-transform: scale(-1, 1); -o-transform: scale(-1, 1);
transform: scale(-1, 1); filter: FlipH;
```

which will flip it if it’s not already, or turning those `-1`s to `1` to remove flipping if it’s flipped. Again, that should only affect what you see locally.

**Comment by rmarcet** [comment]
@rnewman, thanks for bringing to my attention the possibility that this existed only in the self-view.  I was able to test with other participants and they said the video was not horizontally inverted and that they could read the text as intended.  Might still be useful to add this feature to the application as many may still want the option of seeing a non-inverted self-view.  Many thanks!

**Comment by rvhuang** [comment]
Late to the party but again this is really bad because the flaw basically prevents everyone from using Chime for whiteboard coding interviews. Please fix this ASAP.

**Comment by rmarcet** [comment]
As I mentioned in my previous post before closing the case, this issue only affects the self view and not the view from others attending the Chime meeting. I tested it with others and the text was not inverted horizontally. Again, this only affects the self view which you really do not need anyway if you are looking at your whiteboard.

**Comment by rnewman** [comment]
Just to reiterate here, @rvhuang: this repo is for the Amazon Chime SDK for JavaScript; it's straightforward to flip or not flip self view in the SDK.

In neither the SDK nor the Amazon Chime app is your actual video stream flipped.

I'll pass along the feature request to the relevant team.
