### ISSUE TITLE
Question: Clarification on purpose of ClientRequestToken

### ISSUE THREAD

**Issue by chuckntaylor** [aws/amazon-chime-sdk-js#1046]
### Where the confusion is.

Working through the example browser app demos, the server creates a meeting in `await chime.createMeeting()`, passing in a `ClientRequestToken`. In the example, a random `uuidv4()` is assigned here. There is a comment saying:
```
// Use a UUID for the client request token to ensure that any request retries
// do not create multiple meetings.
```

I'm not understanding how supplying a **NEW** random token each time is ensuring that we are **NOT** creating multiple meetings.

### How can the documentation be improved to help your use case?

Could a real world example be given? Given that this `ClientRequestToken` property exists, I assume there must be a use case where you would want to pass in an existing token? For example, if a client has a stored `ClientRequestToken` in LocalStorage, and for whatever reason, they refreshed the browser, could this same `ClientRequestToken` be used in some way to help with re-establishing their presence in the meeting?

### What documentation have you looked at so far?

Primarily this repo, and the documentation found in the [Api Reference](https://docs.aws.amazon.com/chime/latest/APIReference/API_CreateMeeting.html#API_CreateMeeting_RequestSyntax), where it states, "The unique identifier for the client request. Use a different token for different meetings."

What about reconnecting to an existing meeting?

**Comment by simmkyu** [comment]
```
// Use a UUID for the client request token to ensure that any request retries
// do not create multiple meetings.
```

AWS SDK uses the `ClientRequestToken` parameter to retry the original `CreateMeeting` request. Once succeeded, calling `CreateMeeting` with the same token returns the response of the previously-created meeting.

⠀

> Given that this ClientRequestToken property exists, I assume there must be a use case where you would want to pass in an existing token? For example, if a client has a stored ClientRequestToken in LocalStorage, and for whatever reason, they refreshed the browser, could this same ClientRequestToken be used in some way to help with re-establishing their presence in the meeting?
>
> What about reconnecting to an existing meeting?

We recommend using the [GetMeeting API](https://docs.aws.amazon.com/chime/latest/APIReference/API_GetMeeting.html) action to retrieve the existing meeting response based on the meeting ID. For example, the [Chime SDK serverless demo](https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/serverless) stores the `CreateMeeting` API response to Amazon DynamoDB and retrieves it for the following cases:
- Other attendees join the same meeting.
- You re-join the same meeting, e.g., after refreshing the browser.


You can pass the same `ClientRequestToken` to retrieve the meeting response and join the meeting again. But if the meeting has ended, passing in the same token will return a new meeting response.
1. Call `CreateMeeting` API with the token `test`. Assume that it returns the meeting ID `foo`.
2. Join the meeting using the meeting ID `foo` in the browser.
3. After 30 minutes, the meeting automatically ends due to [the auto-end policy](https://docs.aws.amazon.com/chime/latest/dg/mtgs-sdk-mtgs.html). (Or someone else deletes the meeting.)
4. Refresh the browser and call `CreateMeeting` API with the same token `test`.
5. Now, the `CreateMeeting` API returns a different meeting ID `bar`.

**Comment by chuckntaylor** [comment]
@simmkyu Thank you kindly for the thorough response and the links to further clarification! Your response makes perfect sense, and I am going to proceed in the future with storing the meetingId in my DynamoDB as you mentioned above.
