### ISSUE TITLE
Webpack Worker warning

### ISSUE THREAD

**Issue by adambyer** [aws/amazon-chime-sdk-js#1057]
Hi. I'm not sure if this is a Chime issue or not but wanted to see if someone could provide some insight.

I just started using web workers in my project along with the worker-plugin (https://github.com/GoogleChromeLabs/worker-plugin). After adding that, when I compile my JS I get the following warning...

```
WARNING in new Worker() will only be bundled if passed options that include { type: 'module' }.
  Received: new Worker()(null, {})
 @ ./node_modules/amazon-chime-sdk-js/libs/voicefocus/voicefocus.js 15:20-42
 @ ./node_modules/amazon-chime-sdk-js/build/voicefocus/VoiceFocusDeviceTransformer.js
 @ ./node_modules/amazon-chime-sdk-js/build/index.js
```

So far, in limited testing, this doesn't seem to be causing any issues. Anything to be concerned about?

**Comment by richnew10** [comment]
Amazon Voice Focus itself uses workers for loading WebAssembly modules and performing estimation.

The worker code is loaded from a CDN at runtime, and because this supports cross-origin loads, it does something roughly like this:

```typescript
  if (workerURLIsSameOrigin) {
    return Promise.resolve(new Worker(workerURL));
  }
  return fetch(workerURL).then((res) => {
    if (res.ok) {
      return res.blob()
                .then((blob) => new Worker(window.URL.createObjectURL(blob)));
    }
    …
```

`worker-plugin` claims:

> Workers with fully dynamic URLs, Blob URLs, data URLs or with no { type:'module' } option are left unchanged.

`voicefocus.js` lines 15–20 is `loader.js`, which is where that logic lives.


Judging by the issues I've found, `worker-plugin` [is not very sophisticated](https://github.com/angular/angular-cli/issues/14776#issuecomment-516998921), so I think the warning you're seeing is a mix of it getting confused about syntax and also telling you that it's not messing with Chime's own workers.

It's a shame that it's spitting out that warning. [This issue will be relevant to you](https://github.com/GoogleChromeLabs/worker-plugin/issues/12). It includes this explanation:

> In terms of any ill-effects related to the warning, it's really there for the opposite reason: the warning points out failed cases where folks do want WorkerPlugin to bundle a Worker, where static analysis bails out and it can't figure out the worker's entry module…

so I think you can safely ignore it.
