### ISSUE TITLE
Fix race conditions with DOM mock

### ISSUE THREAD

**Issue by vidya-mohan** [aws/amazon-chime-sdk-js#106]
**Describe the bug**
Some tests use DOM mock behavior that create timeouts. These timeouts sometimes expire after the test finishes and can lead to unpredictable tests since the DOMMock may cleanup before then.

The first thing to do would be to fix existing failures when running npm run test:slow.

We may want to strictly sequence changes to the global DOM object so that it is not possible for tests to step on each other as easily.

**Platform**
 - OS: 
 - Browser: 
 - Browser Version: 
 - Amazon Chime SDK GitHub Commit:

**Comment by aburnson** [comment]
This is difficult to fix correctly since many tests have promises that resolve/reject and interact with global DOM state well after the test finishes and unfortunately there is not a simple way to force these promises to clean up before the end of the test. The current method of retrying the test suite has worked for us so far. In the future it may not be sufficient and we will have to rethink this, but for now we can close this issue.
