### ISSUE TITLE
Serverless deploy is currently failing

### ISSUE THREAD

**Issue by richnew10** [aws/amazon-chime-sdk-js#1089]
```
Deploying serverless application
Command sam failed with exit code 1 signal null
Error: Failed to create/update the stack: chime-sdk-demo-canary, An error occurred (InvalidChangeSetStatus) when calling the ExecuteChangeSet operation: ChangeSet [arn:aws:cloudformation:us-east-1:***:stack/chime-sdk-demo-canary/<uuid>] cannot be executed in its current execution status of [OBSOLETE]
```

**Comment by michhyun1** [comment]
Looks like the more recent run of the deploy script was successful, so the script isnt completely broken. Not sure why the status of the Changeset was OBSOLETE in this case though. It could be because "the stack was already updated." https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_DescribeChangeSet.html

This seems to be a one-off case, since the deploy workflow script hasn't run into this issue before.
