### ISSUE TITLE
Could not get local video to start

### ISSUE THREAD

**Issue by gsudhanshu** [aws/amazon-chime-sdk-js#1109]
I got the meetingSession, but could not get local video to start even after I call chooseVideoInputDevice

Error Log:

MyLogger - failed to get video device for constraints {"video":{"deviceId":{"exact":"0"},"width":{"ideal":960},"height":{"ideal":540},"frameRate":{"ideal":15},"googCpuOveruseDetection":true,"googCpuOveruseEncodeUsage":true,"googCpuOveruseThreshold":85,"googCpuUnderuseThreshold":55}}: OverconstrainedError: Constraints could be not satisfied.

**Comment by gsudhanshu** [comment]
able to get it work, thanks

**Comment by henlamk** [comment]
Hello @gsudhanshu 
A user has encountered this problem and I'd be happy to hear how you resolved this issue. 
Thank you

**Comment by michhyun1** [comment]
Please check the Web APIs for the OverConstrainedError - https://developer.mozilla.org/en-US/docs/Web/API/OverconstrainedError

The OverConstrainedError "indicates that the set of desired capabilities for the current MediaStreamTrack cannot currently be met"

This is usually due to the parameters that are passed to chooseVideoInputDevice are invalid because the constraints you are asking for are not supported by your video device.

**Comment by gsudhanshu** [comment]
@henlamk I was able to resolve by calling chooseVideoInputDevice() everytime, before calling startLocalVideoTile()

moreover we provided a video button to the user to toggle video. so if the video is not appearing then the user can use this button to enable video

**Comment by henlamk** [comment]
Thanks for your response.
The resolve was much easier: he just restarted the browser.
