### ISSUE TITLE
Remote video tile turns black once the local video tile is turned off

### ISSUE THREAD

**Issue by anupjk-5** [aws/amazon-chime-sdk-js#1137]
**Describe the bug**
During a video conference, when a user turns his/ her camera off, one of the tiles corresponding to other users turns black along with the removal of the local tile. Here is how the bug can be replicated-

1. User A joins the meeting and turns the camera on
2. User B joins the meeting and turns the camera on. At this point, both the users can see both the video tiles properly in their screen
3. User A turns the camera off. The video tile of A is removed as expected, but the video tile of User B turns black in the screen of User A.

I am using a 'tileState' array to keep track of the available videoTiles and bind them to video elements. Whenever someone joins the meeting, I am adding the new tile to the array via 'videoTileDidUpdate'. Similarly, 'videoTileWasRemoved' is used to remove a tile whenever someone turns the camera off. 

When a tile displays the video properly, turning that particular camera on/ off invokes the 'videoTileDidUpdate' & 'videoTileWasRemoved' methods. But when the tile starts displaying the black screen, neither of these methods are invoked and as a result, the black screen stays irrespective of the state of the corresponding camera(on or off).

**info-logs**
This is the log file during the meeting between two users. The steps followed are same as described in the 'Describe the bug section'.
[justAfterBlackScreen.log](https://github.com/aws/amazon-chime-sdk-js/files/6151870/justAfterBlackScreen.log)

**Screenshots**
Video tile states when the videos are working properly (index '0' is the local tile & index '1' is the remote video tile):
![allOk](https://user-images.githubusercontent.com/72908594/111372189-556d4780-86c0-11eb-9118-6c86460ce236.PNG)

Black-screen in the video tile corresponding to the remote user:
![blackScreen](https://user-images.githubusercontent.com/72908594/111369554-315c3700-86bd-11eb-9a3d-aba383c9ecd2.PNG)

Video tile state corresponding to the black screen video
![tileStateCorrespondingToBlackBox](https://user-images.githubusercontent.com/72908594/111372216-5e5e1900-86c0-11eb-9604-fb68946c2a17.PNG)

As evident from the last screenshot, the 'active' property of 'boundVideoStream' becomes 'false' once the tile turns black. Apart from that, the other properties of the corresponding tile remains same.

**Platform**
 - OS: MacOS, Linux, Windows
 - Browser: Chrome, Safari

**Comment by simmkyu** [comment]
The Amazon Chime server logs indicate that User B (Attendee ID `6aa58890`) also turned the camera off 3 seconds after User A. Do you see the black tile before User B stopped the video?

Time | User | Action
--|--|--
03/16/21 15:34:39 | User A | Stopped the local video.
03/16/21 15:37:32 | User B | Stopped the local video.


--- 

> I am using a 'tileState' array to keep track of the available videoTiles and bind them to video elements. Whenever someone joins the meeting, I am adding the new tile to the array via 'videoTileDidUpdate'. Similarly, 'videoTileWasRemoved' is used to remove a tile whenever someone turns the camera off.

Note that the `videoTileWasRemoved` is not called when you turn your camera off using the `meetingSession.audioVideo.stopLocalVideoTile` API. The `videoTileWasRemoved` is called only when remote attendees turn their cameras off.

How do you bind tile states from your `tileState` array to the video elements?

The [Chime SDK demo application](https://github.com/aws/amazon-chime-sdk-js/blob/0bc46928411f417b551196d03e0a1646133fcc56/demos/browser/app/meetingV2/meetingV2.ts#L2321) binds a video tile to a video element in the `videoTileDidUpdate` method as described in the [README example](https://github.com/aws/amazon-chime-sdk-js#video). I wasn't able to reproduce the bug (See the attached video below ). Could you try again after binding in the `videoTileDidUpdate` method?

https://user-images.githubusercontent.com/36240708/111543364-30b0b880-8730-11eb-88fd-e94a716af1ed.mov

**Comment by anupjk-5** [comment]
> The Amazon Chime server logs indicate that User B (Attendee ID `6aa58890`) also turned the camera off 3 seconds after User A. Do you see the black tile before User B stopped the video? 

User A can see the black screen as soon as his/ her local camera is turned off. The time between turning the camera off and the black screen appearing is less than 1 second.

> Note that the `videoTileWasRemoved` is not called when you turn your camera off using the `meetingSession.audioVideo.stopLocalVideoTile` API. The `videoTileWasRemoved` is called only when remote attendees turn their cameras off.

I am using `stopLocalVideoTile` & `removeLocalVideoTile` when the user turns off the camera. The `removeLocalVideoTile` is invoking the `videoTileWasRemoved` for the local user also.

> How do you bind tile states from your `tileState` array to the video elements?

I am using React for the frontend. The updated tileState received from `videoTileDidUpdate` & `videoTileWasRemoved` is mapped to video element components. Each tile is bound to the respective element as follows-
                            `const videoElement = this.videoRef.current;`
                            `meeting.meetingSession.audioVideo.bindVideoElement(tile.tileId, videoElement); `

The `this.videoRef` is the reference to the corresponding video element of the tile.

**Comment by simmkyu** [comment]
The [Chime SDK React component library](https://github.com/aws/amazon-chime-sdk-component-library-react) has a similar implementation for handling remote videos. When a remote attendee turns a video on/off:
1. `videoTileDidUpdate` / `videoTileWasRemoved ` is called in [RemoteVideoTileProvider](https://github.com/aws/amazon-chime-sdk-component-library-react/blob/c636b8bae302553dcde0fc877062725687e9f5db/src/providers/RemoteVideoTileProvider/index.tsx#L21-L47). This provider dispatches an array of tiles to child components.
2.  The [RemoteVideos component](https://github.com/aws/amazon-chime-sdk-component-library-react/blob/c636b8bae302553dcde0fc877062725687e9f5db/src/components/sdk/RemoteVideos/index.tsx#L13) receives these updated tiles and passes them down to a child component [RemoteVideo](https://github.com/aws/amazon-chime-sdk-component-library-react/blob/c636b8bae302553dcde0fc877062725687e9f5db/src/components/sdk/RemoteVideo/index.tsx#L30-L43).
3. The [RemoteVideo component](https://github.com/aws/amazon-chime-sdk-component-library-react/blob/c636b8bae302553dcde0fc877062725687e9f5db/src/components/sdk/RemoteVideo/index.tsx#L30-L43) binds a tile to `videoEl.current`.

But the component library does not handle `videoTileWasRemoved` for a local video. See [LocalVideoProvider](https://github.com/aws/amazon-chime-sdk-component-library-react/blob/master/src/providers/LocalVideoProvider/index.tsx#L55-L75).


I couldn't reproduce the bug in the [component demo](https://github.com/aws/amazon-chime-sdk-component-library-react/tree/master/demo/meeting) running on Windows (left) and macOS (right).

https://user-images.githubusercontent.com/36240708/111707605-97ea6d80-8801-11eb-8e77-f5673b73b6a8.mov


⠀
⠀
The key difference from your implementation is that the component library does not handle the `videoTileWasRemoved` event because it doesn't call `removeLocalVideoTile`. Could you try decoupling the local video logic from remote videos and see if that helps? Please take a look at the component library's implementation.

**Comment by anupjk-5** [comment]
The issue seems to be resolved after I have decoupled the local video tile logic from the remote videos.  Thanks!!
Although the observer was setup perfectly to handle the local tile also, it seems that there was a problem during the sync up between 'stopLocalVideoTile' and the observer.
