### ISSUE TITLE
Video Processor feedback

### ISSUE THREAD

**Issue by s4souvik** [aws/amazon-chime-sdk-js#1141]
### What are you trying to do?

I am trying to blur the background/ replace the background of a meeting attendee.

### How can the documentation be improved to help your use case?

Include a section to show how the VideoFrameProcessor can be used to do so.

### What documentation have you looked at so far?

README.md, Amazon Chime SDK Developer Guide, CHANGELOG

**Comment by simmkyu** [comment]
Please review the video processing API guide:
https://github.com/aws/amazon-chime-sdk-js/blob/master/guides/10_Video_Processor.md

The [Chime SDK demo app](https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/browser) uses the video processing API and the TensorFlow [BodyPix model](https://github.com/tensorflow/tfjs-models/tree/master/body-pix) to apply the mask to an attendee. In the demo app, turn your camera on and choose the **Segmentation** option to apply the mask filter.

<img src="https://user-images.githubusercontent.com/36240708/111712814-a50c5a00-880b-11eb-8476-47fd6e718695.png" width="200">
⠀

To blur the background, you can replace the mask API call in [SegmentationProcessor](https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/browser/app/meetingV2/videofilter/SegmentationProcessor.ts#L58-L67):

https://github.com/aws/amazon-chime-sdk-js/blob/cf473e32770fd82bd1dda9a3e64081f16276cf8e/demos/browser/app/meetingV2/videofilter/SegmentationProcessor.ts#L58-L67

with the following code that uses the `BodyPix.drawBokehEffect` API.

```
// eslint-disable-next-line @typescript-eslint/no-explicit-any
let predictions = await this.model.segmentPerson(inputCanvas);
if (predictions) {
  bodyPix.drawBokehEffect(this.targetCanvas, inputCanvas, predictions, 3, 3, false);
  buffers[0] = this.canvasVideoFrameBuffer;
}
```

Once you update the code, rebuild your demo app and choose the **Segmentation** option. You can also integrate this logic into your application. See the [BodyPix repo](https://github.com/tensorflow/tfjs-models/tree/master/body-pix) for available APIs.

**Comment by s4souvik** [comment]
Hi Ktu,

Thanks for the email. I need just one information.
In line no 5 of SegmentationProcessor.ts, we have:

declare var bodyPix: any;

Do we need to import bodyPix library somewhere? I couldn't find it in the
package.json

Thanks,
Souvik Sengupta

**Comment by simmkyu** [comment]
Sorry for the confusion. The Chime SDK demo app performs lazy loading of TensorFlow files instead of using package.json.

1. The demo app calls the `loadBodyPixDependency` function if the user's browser supports Unified Plan (a proposal for signaling multiple media sources in SDP) and the playback of canvas-captured stream.
  https://github.com/aws/amazon-chime-sdk-js/blob/cf473e32770fd82bd1dda9a3e64081f16276cf8e/demos/browser/app/meetingV2/meetingV2.ts#L1645
2. [SegmentationUtil](https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/browser/app/meetingV2/videofilter/SegmentationUtil.ts) defines the `loadBodyPixDependency` function that simply downloads four TensorFlow files, including the BodyPix model.
  https://github.com/aws/amazon-chime-sdk-js/blob/cf473e32770fd82bd1dda9a3e64081f16276cf8e/demos/browser/app/meetingV2/videofilter/SegmentationUtil.ts#L34

**Comment by anuranduttaroy** [comment]
Hey @s4souvik, feel free to re-open this if you still have questions.
