### ISSUE TITLE
[ERROR] MyLogger - missing TURN credentials - falling back to fetch

### ISSUE THREAD

**Issue by timanderson** [aws/amazon-chime-sdk-js#1170]
I am using the singlejs demo. The application includes a meeting with 2-5 participants. It mostly works fine, but sometimes the video fails to show for the other participants and the browser reports this error:

2021-03-31T18:45:31.920Z [ERROR] MyLogger - missing TURN credentials - falling back to fetch amazon-chime-sdk.min.js:1:27329

Audio continues to work correctly. Typically the problem corrects itself after a period.

I am not sure where to look to fix this?

In this case the web browser is Firefox 87 on Windows 10. Chime SDK for JavaScript version 2.6.2, though we also saw the error in earlier versions.

**Comment by devalevenkatesh** [comment]
The log "[ERROR] MyLogger - missing TURN credentials - falling back to fetch" appears when the [ReceiveTURNCredentialsTask](https://github.com/aws/amazon-chime-sdk-js/blob/master/src/task/ReceiveTURNCredentialsTask.ts#L45) task runs. This task is triggered as part of either the meeting session start which is the result of `meetingSession.audioVideo.start()` check the use case [here](https://github.com/aws/amazon-chime-sdk-js#starting-a-session) or as part of meeting reconnect. Could you please provide more information to understand the issue?
1. Since, your video fails to show and then comes back there may be some reconnection taking place? Check for `AudioVideoReconnect` in your logs if thats the case.
2. Please provide us a detailed log and repro steps to follow to further understand the issue.

**Comment by timanderson** [comment]
Thanks, in this case I'm pretty sure it is triggered by starting a session. I wonder why the turnCredentials would be missing, where are they set? The way it works in our application is that one meeting ands and another meeting with different participants starts very soon after.

Tim

**Comment by simmkyu** [comment]
When you call the `meetingSession.audioVideo.start` API, the Chime SDK performs the following tasks:
1. Chime SDK sends the Chime media server the join message and receives the ack message with TURN credentials. This operation happens over a WebSocket connection to the Chime media server.

   Note that Chime SDK uses these credentials to connect to the ICE servers right before creating a [`RTCPeerConnection` object](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection(https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection).
2. If the Chime media servers do not return TURN credentials, the Chime makes an HTTP request to retrieve these credentials.

**Comment by simmkyu** [comment]
> The way it works in our application is that one meeting ends and another meeting with different participants starts very soon after.

Are you using the same meeting response for two meetings? A meeting automatically ends after a period of inactivity in the following conditions:

From the [Amazon Chime SDK developer guide](https://docs.aws.amazon.com/chime/latest/dg/mtgs-sdk-mtgs.html):
> - No audio connections are present in the meeting for more than five minutes.
> - Less than two audio connections are present in the meeting for more than 30 minutes.
> - Screen share viewer connections are inactive for more than 30 minutes.
> - The meeting time exceeds 24 hours.


In that case, your meeting should end with the following `MeetingEnded` status code, but I guess a race condition could happen.
https://github.com/aws/amazon-chime-sdk-js/blob/25685d906e5f75ca98e203efc51a0d83e07b53cc/src/meetingsession/MeetingSessionStatusCode.ts#L48-L51

If you share your meeting ID and attendee ID who experienced the problem, we can investigate the Chime server logs.

**Comment by vidya-mohan** [comment]
Resolving as no response
