### ISSUE TITLE
URL IS NAKED AND ANYONE CAN MESS UP WITH IT

### ISSUE THREAD

**Issue by adesun2k** [aws/amazon-chime-sdk-js#1242]
Hi guys since url is naked anybody can mess up with it.  I want to be sure the request is from me so I added a post parameter 'key' to my request but it is not working please where on the backend am supposed to do this

<img width="1279" alt="Screenshot 2021-05-01 at 12 15 05" src="https://user-images.githubusercontent.com/57893099/116780837-e5036580-aa76-11eb-8e00-5796ec373d91.png">

**handlers.js**
```
let body = JSON.parse(event.body)
 if (body.key !== "3fG#$5o") {
  return response(400, 'application/json', JSON.stringify({error: 'Need parameters: title, name, region'}));
}
```

**Comment by simmkyu** [comment]
You can pass a custom key from your client application to Lambda handlers using two ways.
1. Query parameters
    - Client: Include the query parameters in the request URL. e.g., The following URL contains `title`, `name`, and `region`.
       https://github.com/aws/amazon-chime-sdk-js/blob/327c5464dfa0e6cbe4858485e582ba2de108ad3c/demos/browser/app/meetingV2/meetingV2.ts#L567-L576
     - Server: You can access the query parameters via `event.queryStringParameters`, e.g., `event.queryStringParameters.title`
        https://github.com/aws/amazon-chime-sdk-js/blob/327c5464dfa0e6cbe4858485e582ba2de108ad3c/demos/serverless/src/handlers.js#L36-L40
2. Body
     - Client: You can pass a string JSON body like `meetingId` and `attendeeId`.
       https://github.com/aws/amazon-chime-sdk-js/blob/327c5464dfa0e6cbe4858485e582ba2de108ad3c/demos/browser/app/meetingV2/meetingV2.ts#L1147-L1155
     - Server: You can parse `event.body` and then access those body items.
       https://github.com/aws/amazon-chime-sdk-js/blob/327c5464dfa0e6cbe4858485e582ba2de108ad3c/demos/serverless/src/handlers.js#L250-L252

⠀

The [`handlers.ts`](https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/serverless/src/handlers.js) contains Lambda examples for the [serverless demo application](https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/serverless).

In a production environment, we recommend restricting access to your API using Lambda authorizers, Amazon Cognito user pools, or other mechanisms. For more information, see the "Controlling and managing access to a REST API in API Gateway" guide: https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-control-access-to-api.html

**Comment by adesun2k** [comment]
I have adjusted my code accordingly still no difference. I event deleted the entire code in amazon-chime-sdk-js/demos/serverless/src/handlers.js still no difference. I couldn't find any handlers.ts  but handlers.js

May be I need to update my entire amazon-chime-sdk-js
Please do I update amazon-chime-sdk-js my project is in production?

**Comment by simmkyu** [comment]
> I couldn't find any handlers.ts but handlers.js

Sorry for the typo. It should be [`handlers.js`](https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/serverless/src/handlers.js). 

The [Chime SDK serverless demo](https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/serverless) uses the [AWS CloudFormation](https://aws.amazon.com/cloudformation/) to deploy your client and server applications to AWS resources. When you run the following command, the serverless demo uploads `handlers.js` to the [AWS Lambda] functions so that your users have access to the same website.

```
npm run deploy -- -r us-east-1 -b <my-bucket> -s <my-stack-name> -a meeting
```

---

Suppose that you want to pass a new query parameter `key` (approach 1 in https://github.com/aws/amazon-chime-sdk-js/issues/1242#issuecomment-830761627)

1. Clone the repository.
    ```
    git clone https://github.com/aws/amazon-chime-sdk-js.git
    cd amazon-chime-sdk-js
    ```
2. On the client side, let's include the`key` parameter. To do so, replace the following client-side code:
  https://github.com/aws/amazon-chime-sdk-js/blob/2fca426171ca6aff5feece7819cf114170372c7b/demos/browser/app/meetingV2/meetingV2.ts#L1563-L1570
  with
    ```js
    const response = await fetch(
      `${DemoMeetingApp.BASE_URL}join?title=${encodeURIComponent(
        this.meeting
      )}&name=${encodeURIComponent(this.name)}&region=${encodeURIComponent(
        this.region
      )}&key=${encodeURIComponent('replace-with-your-key')}`,
      {
        method: 'POST',
      }
    );
    ```
3. On the server side, we check if the client passes a proper `key` parameter. To do so, replace the following server-side code (Lambda):
  https://github.com/aws/amazon-chime-sdk-js/blob/2fca426171ca6aff5feece7819cf114170372c7b/demos/serverless/src/handlers.js#L36-L40
  with
    ```js
    exports.join = async (event, context) => {
      const query = event.queryStringParameters;
      if (query.key !== 'replace-with-your-key') {
        return response(401, 'application/json', JSON.stringify({error: 'Missing key!'}));
      }

      if (!query.title || !query.name || !query.region) {
        return response(400, 'application/json', JSON.stringify({error: 'Need parameters: title, name, region'}));
      }
    ```
 4. Deploy your serverless application.
    ```
    cd demos/serverless
    npm install
    npm run deploy -- -r us-east-1 -b <my-bucket> -s <my-stack-name> -a meeting
    ```
5. **Now that your "Join" Lambda function throws a 401 error to the client if a `/join` request does not contain the `key=replace-with-your-key`. You can replace `replace-with-your-key` with your custom key name.**

    Note that the "Join" Lambda function receives the meeting title, attendee name, region, **and your custom key** from the client. The Lambda function then creates a meeting using [CreateMeeting API](https://docs.aws.amazon.com/chime/latest/APIReference/API_CreateMeeting.html) and [CreateAttendee API](https://docs.aws.amazon.com/chime/latest/APIReference/API_CreateAttendee.html).
6. Whenver you make changes in the `demos/browser/app/meetingV2/meetingV2.ts` or `demos/serverless/src/handlers.js`, you must re-deploy your changes using the same bucket and stack names. Re-run the following command again:
    ```bash
    # To ensure that we upload the latest version, delete any assets from the previous deployment
    rm -rf demos/browser/dist
    cd demos/serverless
    npm run deploy -- -r us-east-1 -b <my-bucket> -s <my-stack-name> -a meeting
    ```

Again, we recommend the following auth mechanisms for production:

> In a production environment, we recommend restricting access to your API using Lambda authorizers, Amazon Cognito user pools, or other mechanisms. For more information, see the "Controlling and managing access to a REST API in API Gateway" guide: https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-control-access-to-api.html

**Comment by devalevenkatesh** [comment]
We hope all the provided information has helped. Closing this issue, please feel free to open issues if you need more help.
