### ISSUE TITLE
SDK bundle fails to load if app uses require

### ISSUE THREAD

**Issue by rugoncalves** [aws/amazon-chime-sdk-js#1249]
## Describe the bug
Following the steps in [demo singleJS](https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/singlejs) to bundle all require files into a single one, leads to a run time error, **IF** the application is using **requireJS**:
```
// Runtime error with stack trace//
Module name "buffer" has not been loaded yet for context: _. Use require([])
http://requirejs.org/docs/errors.html#notloaded 
inquire@[domain-removed]/scripts/amazonchimesdk_min.js?SpjlrnxN_4XiW8xZMKWjxw:14:23839
minimal</i.Buffer<@[domain-removed]/scripts/amazonchimesdk_min.js?SpjlrnxN_4XiW8xZMKWjxw:14:28768
minimal<@[domain-removed]/scripts/amazonchimesdk_min.js?SpjlrnxN_4XiW8xZMKWjxw:14:28851
createCommonjsModule@[domain-removed]/scripts/amazonchimesdk_min.js?SpjlrnxN_4XiW8xZMKWjxw:5:564
@[domain-removed]/scripts/amazonchimesdk_min.js?SpjlrnxN_4XiW8xZMKWjxw:14:27271
@[domain-removed]/scripts/amazonchimesdk_min.js?SpjlrnxN_4XiW8xZMKWjxw:5:140
@[domain-removed]/scripts/amazonchimesdk_min.js?SpjlrnxN_4XiW8xZMKWjxw:5:209
```

As a *workaround*, I had to add the following JS to the bundled file:
```javascript
const currRequire = require;
require = undefined;

/*
(bundled code....)
*/

require = currRequire;
```

This is what lead me to think that *there might be* some incompatibility with requirejs.

### Rollup configuration
I tried to use different plugins to solve the runtime error while loading the SDK, but without success....
Below, you'll find a piece of the rollup config file, used to bundle:

```javascript
import commonjs from '@rollup/plugin-commonjs';
import resolve from '@rollup/plugin-node-resolve';
import { nodeResolve } from '@rollup/plugin-node-resolve';
import { terser } from 'rollup-plugin-terser';
import builtins from 'rollup-plugin-node-builtins';

//...

plugins: [
    buildtins()
    resolve(),
    nodeResolve({ preferBuiltins: false, browser: true }),
    commonjs(),
    terser()
]
```

**Platform**
 - OS: windows
 - Browser: all
 - Amazon Chime SDK GitHub Commit: **2.8.0** (latest)

## Questions

1. Is there any known issue/incompatibility with requireJS?
2. Am I missing some configuration while bundling?
3. Do you you see a *better* way to workaround this issue?

**Thank you** for your work in this repo, super complete, and in advance for your precious time to help me.

**Comment by simmkyu** [comment]
Using the [RequireJS 2.3.6 template](https://github.com/volojs/create-template), I could import the bundled "Chime SDK for JavaScript" file (default: `amazon-chime-sdk.min.js`) using the `require` function. I replaced the content of the [create-template/blob/master/www/app/main.js](https://github.com/volojs/create-template/blob/master/www/app/main.js) file with the following:

```
define(function (require) {
    const ChimeSDK = require('./amazon-chime-sdk.min.js');
    const logger = new ChimeSDK.ConsoleLogger('MyLogger', ChimeSDK.LogLevel.INFO);
    logger.info('test');
});
```

The `ConsoleLogger` object works as expected.

⠀

---

> Is there any known issue/incompatibility with requireJS?

We are not aware of any issue related to requireJS. The Chime SDK for JavaScript requires Node and NPM. In your NPM-based project, you install the Chime SDK for JavaScript and use the `import` or `require` keyword depending on your project's module.

> Am I missing some configuration while bundling?
No, the Rollup configuration for the [singlejs](https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/singlejs) example is only for combining the Chime SDK for JavaScript file into a single JavaScript file so that non-NPM applications can import this file by embedding it in `index.html`. For example, you can embed the file using the `<script>` tag in your PHP application.

> Do you you see a better way to workaround this issue?
We recommend using Node and NPM to import the Chime SDK for JavaScript. In a non-NPM project, you can still import the Chime SDK using the `<script>` tag in your `index.html`. I also confirm that I was able to import the Chime SDK using RequireJS 2.3.6.

**Comment by rugoncalves** [comment]
Hi @simmkyu 

Thank you for the reply.
I'll have to dig a little more in this in order to understand what might be causing this problem on our side.

I'll keep this issue updated with what might be causing it.

Thank you

**Comment by simmkyu** [comment]
> Would by any change the any of the module names have the symbol "$" in it?

I don't think the $ sign matters unless the Require JS has a bug with it. The [single-js](https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/singlejs) script does not use `$`. It exposes Chime SDK components under the `window.ChimeSDK` object, e.g.,

```
const logger = new ChimeSDK.ConsoleLogger('ChimeMeetingLogs', ChimeSDK.LogLevel.INFO);
```

**Comment by vidya-mohan** [comment]
Resolving, pls reactivate in case of questions or cut a new issue
