### ISSUE TITLE
Preview video not working in 2.9.0

### ISSUE THREAD

**Issue by junedlanja** [aws/amazon-chime-sdk-js#1278]
**Important:** 

**Meeting and attendee IDs:**

**Timeline**

**Describe the bug**
The video preview shows a black screen. It is working in my application as expected in version 2.8.0 after upgrading to 2.9.0, I can see the camera light turn on and off automatically. Seems like a video stream is automatically get released.

Is it due to update in `startVideoPreviewForVideoInput`? After joining local tile is working as expected though.

**Screenshots**
<img width="608" alt="Screenshot 2021-05-11 at 17 27 00" src="https://user-images.githubusercontent.com/11869570/117811450-2f0df780-b27e-11eb-9745-e531a45a2ac0.png">

**Platform**
 - OS: Mac 11.1
 - Browser: Chrome
 - Browser Version: 90.0.4430.93
 - Amazon Chime SDK GitHub Commit: 2.9.0

**Comment by ltrung** [comment]
@junedlanja Thanks for reporting this. It is probably due to the change in `startVideoPreviewForVideoInput` as you pointed out. However, i could not reproduce this using our meeting demo using Chrome 90.0.4430.93 and Safari 14.1.
Does your app call `chooseVideoInputDevice` before `startVideoPreviewForVideoInput`? And is there anything else your app does before calling `startVideoPreviewForVideoInput`?
It would also be great if you can send us the console.log?

**Comment by junedlanja** [comment]
Yes my app call `chooseVideoInputDevice` before `startVideoPreviewForVideoInput`. Here is log before `audioVideo` start if Im changing anything related to video input `videoInputSelected` twice and then `videoInputUnselected` event fires. Even though I'm not unselecting video input.

Here is a screencast of the log.
<img width="1122" alt="Screenshot 2021-05-12 at 10 03 36" src="https://user-images.githubusercontent.com/11869570/117918999-d71cd280-b309-11eb-9729-11625dbf2e6c.png">

**Comment by ltrung** [comment]
From the event it seems the video input is unselected and thus, the video stream is unavailable. It probably works in 2.8.0 and earlier version because `startVideoPreviewForVideoInput` calls getUserMedia again.
Could you post the full console INFO log for SDK? Also if you could debug locally, could you put a checkpoint here https://github.com/aws/amazon-chime-sdk-js/blob/master/src/devicecontroller/DefaultDeviceController.ts#L537 and check the callstack to see what sets the `videoInputUnselected` event.

**Comment by junedlanja** [comment]
[logs](https://github.com/aws/amazon-chime-sdk-js/files/6464371/logs.log) file

**Comment by ltrung** [comment]
From the logs, it seems the call to `startVideoPreviewForVideoInput` is before `chooseVideoInputDevice` returns. `chooseVideoInputDevice` and `chooseAudioInputDevice` are async function so do you do await to wait for them to return first?

**Comment by junedlanja** [comment]
Yes, they are used with async and await.

**Comment by junedlanja** [comment]
@ltrung any update? The above solution solved the issue in the pc browser but it's happening in iPad. Also in iPad changing camera not working.

**Comment by devalevenkatesh** [comment]
Hello @junedlanja,

For the iPad issue, need some information:
1. Is changing camera not working on the preview screen or the in-meeting screen?
2. Can you please provide browser console logs for the iPad issue?

Instruction to get the logs from iPad if you need them:
1. plug iphone into computer
2. settings > safari > advanced > web inspector (turn on)
3. open safari on your computer
4. run your web app on your iphone in the safari browser
5. on your computer in safari, go to develop > inspectable applications, your running app should be in there.
6. Click the running website link and you will logs in the open window of Safari console.

**Comment by junedlanja** [comment]
It was due to `meetingReadinessChecker` after selecting the video input device, I was calling the `checkVideoInput` method to check if the device has permissions and working. Internally `checkVideoInput` changes video input to `null` from the selected device.

Regarding the camera not switching it was due to the wrong deviceId was passed in some cases.
