### ISSUE TITLE
Establishing a messaging connection with chime.getMessagingSessionEndpoint

### ISSUE THREAD

**Issue by Berkyle** [aws/amazon-chime-sdk-js#1284]
### What are you trying to do?

I'm trying to implement a messaging session within my application using the amazon-chime-sdk-js. [Following the README](https://github.com/aws/amazon-chime-sdk-js/blob/050457e82fcbe88f0d149c2aacde483b9ff612e8/README.md#messaging-session), I'm trying to retrieve the messaging session endpoint by doing the following:
```typescript
const chime = new Chime({ region: 'us-east-1' });
const endpoint = await chime.getMessagingSessionEndpoint().promise();
```

However when I do this, I seem to only get an uncaught promise rejection error stating I have missing credentials in the config for the Chime client. See below:

![Screen Shot 2021-05-12 at 1 13 23 PM](https://user-images.githubusercontent.com/34729254/118034489-a8b1ee00-b32f-11eb-9e5e-229bf37f3b80.png)
![Screen Shot 2021-05-12 at 1 13 07 PM](https://user-images.githubusercontent.com/34729254/118034491-a94a8480-b32f-11eb-9943-ecb00d142956.png)

The README led me to believe that this was all I needed to do to retrieve the messaging session endpoint. On a whim, I then tried attaching my `accessKeyId` and `secretAccessKey` as a credentials object to the client options, like so:
```typescript
new Chime({
    region: 'us-east-1',
    credentials: {
      accessKeyId: 'AKIATMYACCESSKEY',
      secretAccessKey: 'nALMy/SecretAccessKey',
    },
});
```

When I did this I was actually able to retrieve the messaging session endpoint, but this is code I mean to run on the client side so passing in a credentials object like this is out of the question.  

Later, I ran the messagingSession application demo in `demo/browsers` via `npm run start --app=messagingSession` and the application ran just fine, despite also instantiating the Chime client as described on the README, [like so](https://github.com/aws/amazon-chime-sdk-js/blob/050457e82fcbe88f0d149c2aacde483b9ff612e8/demos/browser/app/messagingSession/messagingSession.ts#L61-L63):
```typescript
const chime = new Chime({ region: 'us-east-1' });
const endpoint = await chime.getMessagingSessionEndpoint().promise();
this.configuration = new MessagingSessionConfiguration(this.userArn, this.sessionId, endpoint.Endpoint.Url, chime, AWS);
```

I'd guess that I am either missing something in my set up configuration in my own app, I've misinterpreted the README documentation, or something else.

### How can the documentation be improved to help your use case?

Describe what else is required of the developer in order to successfully call the `Chime.getMessagingSessionEndpoint`.

### What documentation have you looked at so far?

- README
- AWS CLI API documentation
- Steps in the [Establishing a Connection](https://docs.aws.amazon.com/chime/latest/dg/websockets.html#establish-connection) section of "Using websockets to receive messages" in the AWS Chime Messaging docs.

**Comment by devalevenkatesh** [comment]
Hello, Thanks for reporting this issue.

You are right that your try after passing the credentials worked. The console error indicates that you have not performed AWS credential configuration which is a required pre-requisite. 

The messaging app under `demo/browsers` ran fine because it gets the AWS credentials by making a `GET` call to a node server. The `getMessagingSessionEndpoint` is part of the block which requests the AWS credentials first and then gets the messaging endpoint.
https://github.com/aws/amazon-chime-sdk-js/blob/050457e82fcbe88f0d149c2aacde483b9ff612e8/demos/browser/app/messagingSession/messagingSession.ts#L55-L71

If you check the `fetchCredentials` function it makes a fetch call [here](https://github.com/aws/amazon-chime-sdk-js/blob/050457e82fcbe88f0d149c2aacde483b9ff612e8/demos/browser/app/messagingSession/messagingSession.ts#L142). This call hits our backend node server [here](https://github.com/aws/amazon-chime-sdk-js/blob/050457e82fcbe88f0d149c2aacde483b9ff612e8/demos/browser/server.js#L96) which retrieves the credentials.

Also, currently our demo does not call AWS SDK APIs directly from the browser and does that all in the nodejs server linked in previous line.

To solve this, we will update our README and call this out. Please let us know if you have further questions.

**Comment by Berkyle** [comment]
Thanks for the update, your response makes sense. To make sure I fully understand, do you mean to say it is not possible to call the `getMessagingSessionEndpoint` API without providing the client side the accessKeyId and secretAccessKey?

**Comment by devalevenkatesh** [comment]
Yes, you need AWS credentials with required access to call the `getMessagingSessionEndpoint` API otherwise you will get errors.

The [Establishing a connection](https://docs.aws.amazon.com/chime/latest/dg/websockets.html#establish-connection) link also says the same in the first point and the README for our demos also calls this out in the Pre-requisite section [here](https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/browser#prerequisites).

I will update the demo README to add a step to run the messaging session demo app which is missing currently.

**Comment by Berkyle** [comment]
Gotcha, I understand it's easy enough to just generate the messaging session endpoint from the server rather than the client - I found it confusing that so many code examples besides [the readme](https://github.com/aws/amazon-chime-sdk-js/blob/050457e82fcbe88f0d149c2aacde483b9ff612e8/README.md#messaging-session) called this API and then used the response to instantiate `MessagingSessionConfiguration` and `DefaultMessagingSession`, which (to my understanding) are strictly client-side APIs.

Another code example that added to my confusion was [a demo in the amazon-chime-sdk-component-library-react](https://github.com/aws/amazon-chime-sdk-component-library-react/blob/master/demo/chat/src/services/MessagingService.js#L44-L62). Will credentials need added to the Chime and AWS objects passed in to the `MessagingSessionConfiguration` constructor here as well in order for the `DefaultMessagingSession.addObserver` and `DefaultMessagingSession.start` methods to work?

**Comment by ltrung** [comment]
@Berkyle You are correct. You would need a AWS Client with Credentials on the client in order to use messaging SDK APIs such as SendChannelMessage (https://docs.aws.amazon.com/chime/latest/APIReference/API_SendChannelMessage.html)

**Comment by Berkyle** [comment]
@ltrung thanks for clearing this up - I figured I'll need to route my send message requests from the client to my application server and send the message from there since SendChannelMessage requires credentials, but do you know whether `MessagingSessionConfiguration` requires the AWS and Chime objects to have credentials attached in order to subscribe to message events? My hope is the answer to that is no, otherwise this would be a non-starter for subscribing to message events from the browser, for example.

**Comment by devalevenkatesh** [comment]
As long as you have some form of AWS credential verification on the client side like either AWS Cognito used in [React SDK chat demo](https://github.com/aws/amazon-chime-sdk-component-library-react/blob/master/demo/chat/src/services/MessagingService.js#L44-L62) or credential fetching in JS SDK messaging session demo, I think you need not have to pass the credentials along with the Chime and AWS objects. 

Is there a problem you are running into with the demos even if the credential management is set?

**Comment by dpwspoon** [comment]
I think the intent is that client applications will have AWS credentials, but those credentials are scoped to individual end user’s permissions and obtained dynamically on client application startup.  The aws credential gives users access to the APIs and it allows the backend AWS services to securely identify who they are, so they can only use those APIs as themselves.

To better understand, the AWS credentials are scoped to permissions on a specific end user via a _parameterized_ IAM policy.  In the react demo, this policy is parameterized [here](https://github.com/aws/amazon-chime-sdk-component-library-react/blob/master/demo/chat/src/backend/serverless/template.yaml#L362).  Specifically, the app-instance-user ARN in the resource section of that policy is parameterized `${cognito-identity.amazonaws.com:sub}`.  What is happening in the demo is the user is logging into Cognito User pools and getting Cognito User pool credentials (JWT which has a sub uniquely identifying the user). It then exchanges those Cognito User Pool credentials for AWS credentials via Congito Identity Pools.  Cognito Identity pool returns user specific credentials generated from the above policy by parameterizing that policy with the cognito “sub” (where sub is unique to a user).  Notice that policy gives permissions on SendChannelMessage, CreateChannelMembership etc on the app-instance-user ARN that once parameterized is unique to the end user's application.  Thus when the end user application calls a Chime Messaging API such as SendMessage with these credentials, they can only send messages as themselves else the action is forbidden.  All of the Chime SDK Messaging APIs work like this (createChannelMembership etc).  If you want to limit which APIs your users have access to modify the policy to remove or add APIs as needed.  

**If you don't want to use Cognito User Pools**, Cognito Identity Pools can do this same exchange process with any standards based identity token (JWT, SAML, OPENID, etc).  But the parameterized part of the IAM policy (`${cognito-identity.amazonaws.com:sub}`) would change (see https://docs.aws.amazon.com/cognito/latest/developerguide/role-based-access-control.html).  

**If you don’t want to use Cognito Identity Pools or your users don't already have a standards based identity token**, you can setup a small backend service that calls `sts assume-role <roleArn> --tags username=<your users uuid>`.   The IAM policy would be the same as linked above except instead of `${cognito-identity.amazonaws.com:sub}` it would be `${aws:PrincipalTag/username}`, where username can be what ever key you want as long as it matches the `--tag` value in assume role.  For example, something like https://github.com/aws-samples/amazon-chime-sdk/blob/main/apps/moderated-chat-and-sentiment-analysis/backend/template.yaml#L51.

**Comment by Berkyle** [comment]
@devalevenkatesh @dpwspoon Thank you for your replies. Right now I'm still familiarizing myself with AWS's authentication platform and services. If it's alright with you, would you mind leaving this issue open a little longer so I can look into the best way my team's application could leverage the options you've recommended and get back to you with any final questions or clarifications about using chime's messaging session with the provided services?

**Comment by devalevenkatesh** [comment]
Sure. Please let us know. Thanks @ltrung and @dpwspoon for providing more information.

**Comment by dpwspoon** [comment]
@Berkyle We are working on better documenting and demoing the options above.  As part of that we have added the 3rd option of building a small service that returns AWS credentials to users via a call to sts-assume-role to the chat demo.  You can find that example here: https://github.com/aws-samples/amazon-chime-sdk/blob/main/apps/chat/README.md#credential-exchange-service-login.  In this case the small service is a self contained lambda behind API gateway with the full back-end code and cloud-front configuration in this file: https://github.com/aws-samples/amazon-chime-sdk/blob/main/apps/chat/src/backend/serverless/template.yaml#L597-L699.

**Comment by akash4chandran** [comment]
Created CreateAppInstanceUser using aws javascript SDK(v2.916.0).

I am facing an issue(i.e. 4401 Error: Unauthorized) while establishing a connection to a web socket on the client-side as a postman(v8.5.1), after creating AppInstanceUser.

![Screenshot 2021-06-02 at 17 52 20](https://user-images.githubusercontent.com/35295545/120479304-6bd79500-c3cb-11eb-980b-7d24e73241de.png)

**Comment by dpwspoon** [comment]
@akash4chandran can you confirm that the WebSocket request from post man is signing the request via Sigv4?  If so is the signature on the headers or via query parameters.  The WebSocket server currently only supports Sigv4 signing on query parameters (not via headers), as browsers can only sign sigv4 via query params for WebSocket.

**Comment by akash4chandran** [comment]
@dpwspoon Thanks for your reply, No I haven't used Sigv4 in WebSocket request before, and now with your guidelines have included sigv4 in my request, but it produces the same unauthorized error.

![Screenshot 2021-06-03 at 11 19 38](https://user-images.githubusercontent.com/35295545/120594134-1bf5de00-c45e-11eb-8bb9-9b26e9cb9d0d.png)

In addition to that, now have used HTTPS Request for establishing WebSocket connection using postman.
Postman handles sigv4 while using Aws Signature as an Authorization. 

if I made a request with Request Header, it results in 'Unauthorized'
![Screenshot 2021-06-03 at 11 02 44](https://user-images.githubusercontent.com/35295545/120592615-c9b3bd80-c45b-11eb-8d2f-6ca55c95fd8c.png)

if I made a request with Request URL, it results in 'Bad Request'
![Screenshot 2021-06-03 at 11 08 14](https://user-images.githubusercontent.com/35295545/120592909-3a5ada00-c45c-11eb-8f67-ed81fd8ef530.png)

**Comment by Berkyle** [comment]
Hi all, thanks for you patience. My team decided to create an IAM role to provision temporary credentials for our application users on the client by utilizing the STS assume-role API, parameterizing the app instance user resource using session tags.

This issue can be closed, thanks for pointing me in the right direction.

**Comment by ltrung** [comment]
@Berkyle Thanks for letting us know. Glad it worked for you.
