### ISSUE TITLE
Can't join Meeting when no micros available or micro blocked on Firefox and Safari (while working on Chrome)

### ISSUE THREAD

**Issue by rlebosse** [aws/amazon-chime-sdk-js#1325]
**Describe the bug**

I tried the following with the `browser` demo :

* With no micros available (`await listAudioInputDevices()` returns an empty array)
OR
* With micro access blocked

When using Chrome : I can join the Chime Meeting, see myself in the attendees roster, hear the other attendees (if my speaker is authorized) and see the other attendees' videos.
When using Firefox : I cannot join the Chime Meeting
When using Safari : I can join the Chime Meeting but the attendees roster remains empty.

I there any way to allow an attendee to join the Chime Meeting on all supported browsers even if this attendee has no microphone available (a computer with no microphone) or if this attendee has not authorized the access to its microphone ?

**Platform**
 - OS: macOS 11.3.1
 - Browser: Firefox 88 / Safari 14.1 / Chrome 90
 - Amazon Chime SDK GitHub Commit: version 2.10.0

**Comment by xuesichao** [comment]
Hello @rlebosse, thank you for bringing this question to us. 

This is a known issue, maybe you would like to have a look at this [issue 474](https://github.com/aws/amazon-chime-sdk-js/issues/474).

We are working on this issue right now. You can expect the fix will be released in the following weeks. After the fix is released, we should be able to support this kind of use case in Firefox, Safari. I will keep you posted.

Chrome should work well when joining the meeting with blocked permission or unset permission. Could you provide us with  details steps to reproduce the Chrome case? Thank you!

**Comment by rlebosse** [comment]
Thanks that's great news !

Actually, I'm facing problems with Safari and Firefox only.
With Chrome, I'm able to join the Meeting without selecting any authorized microphone.

**Comment by xuesichao** [comment]
@rlebosse That's good, then this issue is consistent with the known one. We will keep you posted when the fix is out.

**Comment by ltrung** [comment]
Closing this as a dup of #474
