### ISSUE TITLE
Create a MessagingSessionConfiguration without userArn for non-registered users

### ISSUE THREAD

**Issue by abhimanusharma** [aws/amazon-chime-sdk-js#1335]
I want my meeting attendees to send each other messages without them actually registering on the application.
It is mentioned in the [faq](https://aws.amazon.com/chime/faq/) :

> **Q: Can I chat with people outside my organization?**
> 
> Yes, you can chat with any registered Amazon Chime user. All you need to know is the email address associated with the Amazon Chime account. Initiate a conversation and chime in.

On the other hand, In documentation, it is mentioned [here](https://docs.aws.amazon.com/chime/latest/dg/connect-id-provider.html) You need to verify user identification in order for them to initiate a messaging session. Do I need to add all the users in the amazon Cognito or something?

then you need to [Create IAM roles](https://docs.aws.amazon.com/chime/latest/dg/iam-roles.html) How can I do it programatically without having access to the aws account (only AWS_ACCESS_KEY and AWS_ACCESS_SECRET).

after that it requires (https://docs.aws.amazon.com/chime/latest/dg/websockets.html#establish-connection)

[In this section](https://docs.aws.amazon.com/chime/latest/APIReference/API_CreateAppInstanceUser.html), Can the client access token be anything? like user email or something?

[Here](https://docs.aws.amazon.com/chime/latest/APIReference/API_CreateRoom.html) can I use user email for ClientRequestToken?
What's AppInstanceUserId? How can I generate or create it for non-registered user programatically?
What's [AppInstanceUserArn](https://docs.aws.amazon.com/chime/latest/APIReference/API_SendChannelMessage.html) ?

Can I create [UserArn](https://docs.aws.amazon.com/chime/latest/dg/websockets.html#connect-api) dynamically?

I have been reading the documentation day and night but I think these questions needs clarification for better documentation and to escalate the resolution quickly with better understanding.

**Comment by dpwspoon** [comment]
Thanks for your feedback and interest.  We are actively working on documentation, demos, and blogs of how to use the Chime Messaging SDK.  The demos are farthest along and I would recommend referring to this [demo](https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/chat) as much as possible until we can improve our documentation.  I'm going to flag this ticket as documentation needed and try to answer your questions here.  I'll be answering your questions out of order of what you asked but in the order that I hope makes most sense.

> Q: Can I chat with people outside my organization?

This FAQ is actually about the [Chime Application](https://aws.amazon.com/chime/download/).  The Chime Application is a messaging and video conferencing application powered by the Chime SDK.  The Application has been out for a few years, where as the SDK is more recent. 

I believe you are interested in the SDK.  Yes you can have your chime SDK meeting attendees chat to each other.  There are 2 possible ways to do this: (1) the chime meetings data channel and (2) the chime messaging SDK.  The data channel would be ephemeral chat and this [blog post](https://aws.amazon.com/about-aws/whats-new/2020/05/amazon-chime-sdk-data-messages-real-time-signaling/) gives an overview and references to how it works.  If you want persistent chat or chat that happens outside or inside of a chime sdk meeting then you will likely want to use the Chime Messaging SDK.  The following questions are discussing about Chime Messaging SDK

> What's AppInstanceUserId? How can I generate or create it for non-registered user programatically?
What's AppInstanceUserArn ?

In the Messaging SDK a chime _app-instance-user_ typically identifies an identity that can send messages, create channels, be invited to channels, connect to a messaging session, etc.  Typically this means you will create an app-instance-user per each user of your application.  This is done prior to the user calling any messaging APIs and is done typically on user registering or logging on with your application (link to [create-app-instance-user](https://docs.aws.amazon.com/cli/latest/reference/chime/create-app-instance-user.html) api).

> Can the client access token be anything? like user email or something?

An app instance user is identified with an ARN of form `arn:aws:chime:us-east-1:<awsAccountId>:app-instance/<appInstanceId>/user/<appInstanceUserId>`.  The appInstanceUserId is just a unique id to identify the user.  It is best to reuse an existing user ID (if your application already has one) for the `appInstanceUserId`.  But you could use a base64 email address or something like that if you wanted.  The `appInstanceId` is just a container to allow multiple different apps inside of one AWS account.  You will create the app instance once.

> Do I need to add all the users in the amazon Cognito or something?  then you need to Create IAM roles?

Your client applications will have AWS credentials that give permissions to call the Chime Messaging SDK directly from the client applications.  How they obtained them is discussed further below, but the credentials will give permissions to an IAM policy.  For example, a user with appInstanceUserId 123456 will have a resolved policy like

```yaml
Effect: "Allow"
Action:
  - "chime:SendChannelMessage"
  - "chime:GetChannelMessage"
  - "chime:ListChannelMessages"
  - "chime:UpdateChannelMessage"
  - "chime:ListChannelMembershipsForAppInstanceUser" 
  
  ... (any other API permissions you want them to have)
Resource:
  - arn:aws:chime:us-east-1:<awsAccountId>:app-instance/<appInstanceId>/user/123456
  - arn:aws:chime:us-east-1:<awsAccountId>:app-instance/<appInstanceId>/channel/*
```

This policy is giving permissions to call APIs like "sendChannelMessage" as the user 123456 for any channel.  How does this work in practice?  All the Chime Messaging APIs listed take a required parameter called `ChimeBearer` that then needs to match the user ARN supplied in the policy, for this example `arn:aws:chime:us-east-1:<awsAccountId>:app-instance/<appInstanceId>/user/123456`.  See [sendChannelMessage](https://docs.aws.amazon.com/chime/latest/APIReference/API_SendChannelMessage.html#API_SendChannelMessage_RequestSyntax) for reference.  If they call SendChannelMessage with a app-instance-user ARN that doesn't match the policy above they will get a 403.

Obviously you won't be creating an IAM policy per user.  The policy above is just psuedo code showing what the policy would resolve to.  In reality you will have an IAM role that parameterizes the appInstanceUserId.  We will discuss how this parameter is resolved in a moment but the policy would look something like 


```yaml
Effect: "Allow"
Action:
  - "chime:SendChannelMessage"
  - "chime:GetChannelMessage"
  - "chime:ListChannelMessages"
  - "chime:UpdateChannelMessage"
  - "chime:ListChannelMembershipsForAppInstanceUser" 
  
  ... (any other API permissions you want them to have)
Resource:
  - arn:aws:chime:us-east-1:<awsAccountId>:app-instance/<appInstanceId>/user/${cognito-identity.amazonaws.com:sub}
  - arn:aws:chime:us-east-1:<awsAccountId>:app-instance/<appInstanceId>/channel/*
```

where `${cognito-identity.amazonaws.com:sub}` is a parameter, and when the policy is assumed (as an IAM Role) that parameter is parameterized to give permissions to a specific user.

> How can I do it programatically without having access to the aws account (only AWS_ACCESS_KEY and AWS_ACCESS_SECRET).

Most AWS developers are familiar with AWS_ACCESS_KEY and AWS_ACCESS_SECRET_KEY that give programmatic access to AWS SDKs.  There is actually a 3rd field called SESSION_ID.  The SESSION_ID is populated when the credentials are _temporary_ (default 1 hour).  Running programs are meant to have these _temporary AWS credentials_.  They refresh periodically. They obtain these credentials by assuming an IAM role, which is just a collection of IAM policies.  This is what is done when giving a role to an EC2 instance or lambda, but it is the same concept as when client side applications need AWS credentials, which is the case for the Chime Messaging SDK.  There are several ways to assume roles.  The 2 main ones for client side applications are Cognito Identity Pools or manually calling assume role from a backend service.  Depending on which one you use changes the format of how you parameterize the role/policy.  Let's discuss these options on how to assume roles.

The chat demo was originally written using Cogntio User Pools and Identity pools.  Cognito User Pools is just a standards based Identity Provider that stores users and user login credentials.  In the demo, the IAM policy is parameterized [here](https://github.com/aws-samples/amazon-chime-sdk/blob/main/apps/chat/src/backend/serverless/template.yaml#L367). Specifically, the app-instance-user ARN in the resource section of that policy is parameterized `${cognito-identity.amazonaws.com:sub}`. What is happening in the demo, is the user is logging into Cognito User pools and getting Cognito User pool credentials (JWT which has a sub uniquely identifying the user). It then exchanges those Cognito User Pool credentials for AWS credentials via Congito Identity Pools. Cognito Identity pool returns user specific AWS credentials generated from the above policy by parameterizing that policy with the cognito “sub” (where sub is unique to a user).  Note, the demo is also using a [Cognito Trigger](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools-working-with-aws-lambda-triggers.html) to create app-instance-users when users register.

**If you don't want to use Cognito User Pools** as your identity provider, Cognito Identity Pools can do this same exchange process with any standards based identity token (JWT, SAML, OPENID, etc). But the parameterized part of the IAM policy (${cognito-identity.amazonaws.com:sub}) would change based on what type of access token your Identity Provider returns, (see https://docs.aws.amazon.com/cognito/latest/developerguide/role-based-access-control.html).  

**If you don’t want to use Cognito Identity Pools or your users don't already have a standards based identity token**, you can setup a small backend service that calls `sts assume-role <roleArn> --tags UserUUID=<your users uuid>`.   The IAM policy would be the same as linked above except instead of ${cognito-identity.amazonaws.com:sub} it would be ${aws:PrincipalTag/UserUUID}.  The demo has been updated to also show this flow as well.  The IAM policy is here: https://github.com/aws-samples/amazon-chime-sdk/blob/main/apps/chat/src/backend/serverless/template.yaml#L491.  And the backend lambda is [here](https://github.com/aws-samples/amazon-chime-sdk/blob/main/apps/chat/src/backend/serverless/template.yaml#L598).  You should be able to customize that lambda to your needs.  It creates the appInstanceUser on first login and has a TODO where you would put your own credential validation logic, such that your users credentials (in any form) would be validated and then exchanged for scoped down AWS credentials.

> [Here](https://docs.aws.amazon.com/chime/latest/APIReference/API_CreateRoom.html) can I use user email for ClientRequestToken?

We are working on better destinguish the Chime Application SDK (APIs that control aspects of the Chime App) and the Chime SDK (like Chime SDK Messaging) that builders can use to build chat into their own apps. The linked API  you asked about (Create Room) is actually to the Chime Application.  For using the Chime Messaging SDK the APIs will generally have "channel" or "app-instance" in their name.

Hope that covers your questions.  Please feel free to ask follow ups and we will try to answer in a timely fashion.  Will leave this ticket open until we can complete documentation updates.

**Comment by abhimanusharma** [comment]
@dpwspoon Wow thank you so much for writing this great documentation in such short amount of time. I think this is going to help many beginners like me. \
I was trying pretty hard to understand the explanation you wrote until this like *The chat demo was originally written using Cogntio User Pools* 
I believe Cognito Identity Pool or Cognito services will work only for the users that are already registered in my application (Linked AWS account) but I mentioned I wanted create a chat group only for anonymous users.
I guess then in that case sts service come in light,  First I want to mention that I am not using Lambda so can I use my nodejs application server (NestJs) to do the same? Can I create [these policies](https://github.com/aws-samples/amazon-chime-sdk/blob/main/apps/chat/src/backend/serverless/template.yaml#L491) with api request instead of serverless approach?

Thank you

**Comment by dpwspoon** [comment]
For anonymous users you have 2 options

1) STS (as you indicated).  Yes, currently the demo shows this working as a lambda behind API gateway.  The code is quite small and is written in javascript.  You can run the same logic in any backend server you prefer.  The code is [here](https://github.com/aws-samples/amazon-chime-sdk/blob/main/apps/chat/src/backend/serverless/template.yaml#L611-L650) and should be easy to port as long as you can get the AWS SDK imported into your server.  You will need to call sts assume-role and optionally chime create-app-instance-user.

2) Cognito Identity Pools actually supports anonymous users (see https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-scenarios.html).  We haven't demoed this yet so you might need to figure out how some of the flows should work; specifically what to set the appInstanceUserId to for anonymous users.  This would be something that would probably be beneficial to add to the demo here: https://github.com/aws-samples/amazon-chime-sdk/blob/main/apps/chat and we could open a ticket in that repository to support that.  But with out doing a sample implementation there I'm not sure what if any gotchas you would face doing this approach.

**Comment by abhimanusharma** [comment]
@dpwspoon Thanks for the clarification, Let me try this one, I will close this issue after successful implementation of the above.

**Comment by abhimanusharma** [comment]
@dpwspoon I was stuck when using MessegingSessionConfiguration but as per your suggestion I tried to use AWS STS but I am getting 403 unauthorized error.
```
AccessDenied: User: arn:aws:iam::1234567891234:user/My_secret_User is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::1234567891234:role/anonymousAttendee
```

I have added all the policies for the above user for STS.
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": "sts:*",
            "Resource": "*"
        }
    ]
}
```

#1355 
Now I tried to use CreateAppInstanceUser to generate the userArn. Then use that userArn to create a messaging channel but getting **422 Unprocessable Entity**

```
{
    "statusCode": 422,
    "success": false,
    "message": "An invalid app instance user ARN was supplied for the x-amz-chime-bearer HTTP header.",
    "errors": []
}
```

I don't really get why there is no single article/tutorial or proper documentation to use AWS Chime Messaging SDK.
