### ISSUE TITLE
Hearing my own voice after initializing audioVideo.chooseAudioInputDevice

### ISSUE THREAD

**Issue by abhimanusharma** [aws/amazon-chime-sdk-js#1349]
I had to initialize audioInput device as the mute button was not working without initializing this. So, when the user just click on the invitation link and then selecting their audio video devices. In case user don't choose anything from audioVideo device list then the default device should select. 

**Describe the bug**
The issue is other users don't hear any audio until the audio input device is selected from the list. So, I tried to intilialize the audio **Input device at index [0]** which is the default device in my case. So, after initializing only audio input device I am hearing my own voice even when I am not initializing my audio output device yet. Even if I select a audio output device I must not hear my voice. I tried everything I could mentioned in the demo [meetingV2](https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/browser/app/meetingV2/meetingV2.ts) but still don't understand the issue. I tried to find online but could not find anyone posted similar issue on stackoverflow or repo issues earlier.

One more important thing to mention that when a user a user join with their audio then, that user and other users in the meeting hear disturbance and very **high frequency squeaky sound** in the background due to which other users barely hear user's voice.  If more than one user join that meeting and use their audio then this become a mess of high frequency squeaky sound.

Here is my simple code.
```
async initializeAudioInputDevice() {
    const audioInputDevice = this.state.audioInputDevicesList[0].key;
    try {
      await this.meetingSession.audioVideo.chooseAudioInputDevice(audioInputDevice);
    } catch (e) {
      fatal(e);
      console.log(`failed to choose audio input device ${audioInputDevice}`, e);
    }
  }
```

**Platform**
 - OS: Ubuntu 18.04, Windows 10, Macbook Pro 11.2.3
 - Browser: 
      --  Google Chrome (Version 91.0.4472.77 (Official Build) (64-bit)), 
      --  Mozilla Firefox 89.0 (64 bit ), 
      --  Safari 14.3.0,

**Comment by simmkyu** [comment]
> So, after initializing only audio input device I am hearing my own voice even when I am not initializing my audio output device yet. Even if I select a audio output device I must not hear my voice. I

Right, you should not hear your voice in any condition. The issue may happen if you join the same meeting using two browser tabs or windows in the same local machine. Could you ensure that you have only one website using WebRTC, audio, and camera? Also, the Chime SDK for JavaScript does not have any API to hear your own audio. Please make sure that you do not have any other setup that may cause this issue in your computer.


> One more important thing to mention that when a user a user join with their audio then, that user and other users in the meeting hear disturbance and very high frequency squeaky sound in the background due to which other users barely hear user's voice.

I am not aware of the high-frequency noise issue or other severe noise issue in the recent versions of the Chime SDK for JavaScript. Could you provide the following information?

- Have you enabled Web Audio or the Amazon Voice Focus feature?
  https://aws.github.io/amazon-chime-sdk-js/modules/amazonvoice_focus.html#amazon-voice-focus-on-the-web
- Do you experience the issue in all the listed OS and browsers? e.g., Ubuntu, Windows, and macOS. Or do you hear the noise in a specific combination or repro steps?
- Could you try our [serverless demo](https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/serverless) and see if the problem persists?

The repro steps would be appreciated too. Thanks!

**Comment by abhimanusharma** [comment]
Ok thanks for pointing out. I was opening multiple tabs/windows of the same system on my local machine. 

There is one more issue that on the device selection screen other users with the same meeting url can hear this user before him joining the meeting. 

One more thing when I am doing `this.meetingSession.audioVideo.unbindAudioElement()` this is muting all users in the meeting instead of current user.

**Comment by simmkyu** [comment]
>  I was opening multiple tabs/windows of the same system on my local machine.

Yes, if you open the website enabled by the Chime SDK JavaScript in multiple tabs/windows, you will hear your voice unless muting one tab's audio input and output.

⠀

> There is one more issue that on the device selection screen other users with the same meeting url can hear this user before him joining the meeting.

I guess that the user has already joined a meeting. Otherwise, other attendees should not be able to hear the user's audio. This should be a severe issue, but I am not aware of any ongoing issue in our support queue.

When this bug happens again, could you share the following information? I can check the Chime server logs if the attendee has already joined a meeting in your device selection page.
- Chime SDK for JavaScript INFO-level browser logs
- Meeting ID
- Attendee IDs

It seems that you experience this audio issue because you are using one local machine to test multi-attendee scenarios. I recommend testing your application using multiple machines, e.g., one attendee per computer.

⠀

> One more thing when I am doing this.meetingSession.audioVideo.unbindAudioElement() this is muting all users in the meeting instead of current user.

Use the following APIs to mute and unmute the current attendee. See the [use case 7](https://github.com/aws/amazon-chime-sdk-js#audio) in README. When you call `realtimeMuteLocalAudio`, other attendees won't be able to hear you.

```
meetingSession.audioVideo.realtimeMuteLocalAudio();
meetingSession.audioVideo.realtimeUnmuteLocalAudio();
```

`this.meetingSession.audioVideo.unbindAudioElement()` unbinds an incoming audio stream from your HTMLAudioElement. The current attendee becomes unable to hear all other attendees' audio.

Note that the Chime SDK for JavaScript does not support muting and unmuting a specific attendee.
