### ISSUE TITLE
if user turned off their own video then video element is not removed

### ISSUE THREAD

**Issue by E5920** [aws/amazon-chime-sdk-js#1373]
@michhyun1, i am facing issue when user turned off their own video then remote video element is not removed. in ideal condition videoelement should be removed, please correct me

Html Code.

< *ngFor="let user of videoElementStatus | keyvalue">

<id="{{user.key}}">

ts code :-

videoElementStatus: { [index: string]: number; } = {};
private domElement(className : string, key : string) {
if(className == 'session-local-video' || className == 'session-audio' ){
return document.getElementsByClassName(className)[0];
} else {
//remote video element
return document.getElementById(key);
}
return null;
}

videotilewasremoved(){

}

  audioVideoDidStop() {
    console.log(" inside audioVideoDidStop");
    this.meeting.meetingSession.audioVideo.stopLocalVideoTile();
    //this.meeting.dropAttendee();
    this.modalService.open('meeting-end-modal');
  }

videoTileDidUpdate(tileState: VideoTileState) {
// Ignore a tile without attendee ID and a content/screen share.
if (!tileState.boundAttendeeId || !tileState.tileId) {
return;
}

// Choose the right video element in your web application
var videoElement = tileState.localTile? 'session-local-video' : 'session-remote-video';

if(!tileState.localTile){
  if (tileState.boundAttendeeId in this.videoElementStatus === false) {

    this.videoElementStatus[tileState.boundAttendeeId] = -1;

    this.changeDetectorRef.detectChanges();
  }
}

 let videoEl = null;    
videoEl = this.domElement(videoElement, tileState.boundAttendeeId);

// Bind the given tile state to the target video element
if (videoEl != null){
	this.meeting.meetingSession.audioVideo
  .bindVideoElement(tileState.tileId, videoEl);
  this.domShow(videoEl);
} else {
}
}

**Comment by devalevenkatesh** [comment]
Hi @E5920 ,

As suggested in an other issue #1372 request you to go over the JS SDK meetingV2 demo implementation. 

In order to handle the tile show-hide we have a [DemoTileOrganizer](https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/browser/app/meetingV2/meetingV2.ts#L89) responsible to acquire and release tile indexes from the available video elements. We store a mapping from tileId to tileIndexes where tileId is allocated by JS SDK and the tileIndex is one of the number from actual number of video elements in the meetingV2 HTML page.

We have implemented the [videoTileDidUpdate](https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/browser/app/meetingV2/meetingV2.ts#L2681-L2725) and [videoTileWasRemoved](https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/browser/app/meetingV2/meetingV2.ts#L2727-L2736) audio-video observers to update the demo app when video state changes for a `tileId`. When we get an update in `videoTileDidUpdate`, we acquire the video tile index and bind the video element and show the video element against that tile index. When we get an update in `videoTileWasRemoved` we release the tile index mapped to the received `tileId` and hide the video element. 

Important reference link that might help:
- [AudioVideoObservers](https://aws.github.io/amazon-chime-sdk-js/interfaces/audiovideoobserver.html#videotiledidupdate)
- [JS SDK README Video Use Cases](https://github.com/aws/amazon-chime-sdk-js#video)

If you still find issues please feel free to re-open this issue.
