### ISSUE TITLE
Do not disconnect after one missed pong - set maximum amount of missable pongs

### ISSUE THREAD

**Issue by massimo-bortolamei-hegias** [aws/amazon-chime-sdk-js#1375]
I noticed that as soon as I miss one pong, and receive the next one out of order, my client disconnects automatically.
Is it possible to configure the maximum amount of missable pongs to something higher?

Sometimes the workload in our webapp is too high and a pong can be missed, causing the disconnection.

In addition, I also noticed (but I don't know if its related) that after a missed pong I can (not always) get one of these two errors:
- ICE failed
- connection to  wss://signal.m1.ue1.app.chime.aws failed

I'm not sure if this is a problem caused by the missed pong, or the cause itself. 
But mind that this happens while already connected, randomly, and after some time. If it was a problem with reaching either the stun/turn servers or the signaling endpoint of chime, connection wouldn't be successful in the first place.
For this reason, I don't think [951](https://github.com/aws/amazon-chime-sdk-js/issues/951) applies to me entirely.
But again, I could be wrong, everything could be related, or they could be 3 different problems.

Can anyone enlighten me a bit, please? Thanks

**Comment by devalevenkatesh** [comment]
Yes, you can configure missed pongs by changing the [`connectionHealthPolicyConfiguration `](https://github.com/aws/amazon-chime-sdk-js/blob/master/src/meetingsession/MeetingSessionConfiguration.ts#L62) while creating the `MeetingSessionConfiguration`.

The Amazon Chime SDK for JS uses defaults specified in the default [`ConnectionHealthPolicyConfiguration`](https://github.com/aws/amazon-chime-sdk-js/blob/11f66bb9ba2bb35582501ffb8b56b2f5f3008c1d/src/connectionhealthpolicy/ConnectionHealthPolicyConfiguration.ts#L23-L24).

The two problems of ICE failure or connection loss may be due to bad network where in JS SDK fails to establish connectivity. Could you please try changing the defaults and check whether you are able to solve the issue?

If not, it would be helpful to get complete browser console logs to look further. Please find the instructions for the same [here](https://github.com/aws/amazon-chime-sdk-js/blob/master/guides/07_FAQs.md#how-can-i-get-amazon-chime-sdk-logs-for-debugging) in our FAQ.

**Comment by devalevenkatesh** [comment]
Hello, we are closing this issue now. Please feel free to create or re-open if you have more questions.

**Comment by massimo-bortolamei-hegias** [comment]
Hey @devalevenkatesh sorry for not getting back to you. I followed your advice and tried setting `ConnectionHealthPolicyConfiguration.missedPongsLowerThreshold = 4` and  `ConnectionHealthPolicyConfiguration.missedPongsUpperThreshold= 10`. We are now testing to see if this will solve our problem. If that is not the case, I'll open a new issue with more logs. Thanks
