### ISSUE TITLE
Deployed serverless meet in ap-south-1 where will my meeting will be stored?

### ISSUE THREAD

**Issue by gavandivya** [aws/amazon-chime-sdk-js#1383]
### What are you trying to do?

I am able to deploy the serverless demo meeting(Create s3 bucket) in the ap-south-1 region. So where will my meeting and client data store??
It will be on ap-south-1 i.e the S3 bucket I created or will be in the us-east-1 region as default, as mentioned by AWS chime documentation.

**Comment by devalevenkatesh** [comment]
Yes, so the resources created as part of the deploy script like the S3 bucket and the CloudFormation created resources will be in `ap-south-1` if that's what is meant by "client data store".

For meeting, the media region defaults to `us-east-1`. In the locally deployed demo app, we do not specify `MediaRegion` in `CreateMeeting` API hence default region would be `us-east-1`.

Below documentation link will help if you want to choose a different media region:
- https://docs.aws.amazon.com/chime/latest/dg/chime-sdk-meetings-regions.html
- https://github.com/aws/amazon-chime-sdk-js/blob/master/guides/01_Getting_Started.md#getting-started
- Local demo server for the meeting demo app:
   https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/browser/server.js#L22-L25

> Note: The Amazon Chime object creation endpoint still requires `us-east-1` as the region.

Please let us know if need more information.

**Comment by gavandivya** [comment]
Okay, client data means the information that is entered while joining the chime meeting like the meeting title, user name and the location in with meeting is hosted. And what about the meeting Id and attendee Id created that is created.  So where all this data is stored?

Because in documentation it is mentioned that if we have meet in us-east-1 then only the user info will be stored otherwise it won't be saved. So I want to know what this exactly means..

**Comment by devalevenkatesh** [comment]
Hello @gavandivya ,

The `meetingId` and the `attendeeId` apart from the actual audio video media from the `CreateMeeting` and `CreateAttendee` API will be still stored in `us-east-1`. The media will be stored nearest to your region if you use nearest media region API as linked in above documentation otherwise you can specify `mediaRegion` as we do in our demo [here](https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/browser/server.js#L60).

For the rest of the demo deployment the serverless template resources will get created in the region you deploy it to. Please let us know if you need more information.

**Comment by gavandivya** [comment]
So lets consider a situation
All the users are in India, so the nearest location for hosting meet will be ap-south-1. 
I deployed the video application using ap-south-1 so all the deployment script and object created by cloudformation is in S3 bucket of ap-south-1.
Now how will I know which user joined the meeting and for how much time. Even the start and end time of video meeting. Where will I find all this information.
Need urgent help.
Where will the meeting id, client id, name duration of meeting, recording will be stored? Because even after having a meeting of 5 minutes I cant see anything on my S3 bucket....

**Comment by michhyun1** [comment]
@gavandivya Have you checked out this [blog post](https://aws.amazon.com/blogs/business-productivity/monitoring-and-troubleshooting-with-amazon-chime-sdk-meeting-events/)? Perhaps it fits your use case to get access to that data.

**Comment by devalevenkatesh** [comment]
So, the information about which user joined and for how much time, you can implement the `eventDidReceive` observer which will provide events with certain attributes as explained in the above blog post Michael linked.

The meetingId, attendeeId from the `CreateMeeting` and `CreateAttendee` response will be stored in `us-east-1`. 
If by clientId you mean the meeting title or username that will get stored in the dynamo db in your region. This DB is created as part of the serverless demo to check and retrieve the meeting if we already have so that we can re-use the meeting title. Request you to once check the implementation for the same. 
https://github.com/aws/amazon-chime-sdk-js/blob/d9f008442ec833957bb54c8a86b775ce48f08b11/demos/serverless/src/handlers.js#L191-L216

The AWS CloudFormation (CF) template creates AWS DynamoDB table and AWS CloudWatch log groups in your specified region so those will be stored in your region which should be `ap-south-1` (since you are deploying in that region). Can you please check if you have changed the region to `ap-south-1` in your AWS management console in the top right region dropdown if you are not seeing the CF resources created in your account?

> Note: The recording in the current demo is just an example to show how to record a meeting provided based on few frequent earlier issue. You would have to store the recording where you would like once available. It is not an feature currently provided in the Amazon Chime SDK for JavaScript.

**Comment by devalevenkatesh** [comment]
Hello,

We are closing this issue now. Please feel free to re-open or create new if you have more questions.

**Comment by gavandivya** [comment]
@devalevenkatesh I have a doubt as you said the meetingId and attendeeId i.e CreateMeeting and CreateAttendee response will be stored on us-east-1 bucket , but what in case of my company having AISPL account.
