### ISSUE TITLE
Can a single tileId be bound to 2 videoElements?

### ISSUE THREAD

**Issue by gsudhanshu** [aws/amazon-chime-sdk-js#1394]
I have a requirement where a single tileId is to be bound to 2 different videoElements, is this possible using sdk js?

**Comment by devalevenkatesh** [comment]
Hi @gsudhanshu ,

Currently, we do not support this use case in the JS SDK. We can bind only a single video element to a video tileId. Closing this issue for now please feel free to re-open if you have more questions.

**Comment by michhyun1** [comment]
I believe a given tileState [can only reference one videoElement](https://github.com/aws/amazon-chime-sdk-js/blob/2e2c7e36631d898b925e6e341c28f72dafcfa8d6/src/videotile/VideoTileState.ts#L61), so technically you cannot map a tileId to two different videoElements at the same time - however, you can play the same video stream on two different videoElements, you just need to be careful not to lose references to the videoElements that you are playing those streams on so that you can kill the streams when you'd like.

**Comment by gsudhanshu** [comment]
@michhyun1 in case I bind a tileId to 1 video element. Then how can I play that videostream onto another videoelement? I do not know how to access video stream from tileId .

**Comment by michhyun1** [comment]
if you have the tileId, you can getVideoTile.state(). The VideoTileState will have a reference to the video stream that is bound to that video tile id.

https://aws.github.io/amazon-chime-sdk-js/classes/videotilestate.html#boundvideostream

Just a reminder that this is not a supported use case of the SDK, but feel free to work with the stream to build your own solution.

**Comment by gsudhanshu** [comment]
Thanks @michhyun1 

Will implement if the need arises.
