### ISSUE TITLE
Getting Started feedback

### ISSUE THREAD

**Issue by Rajan-Gupta1** [aws/amazon-chime-sdk-js#1457]
### What are you trying to do?
Build a sample Angular App which will use Chime SDK

*For example: I'm trying to start a meeting session with audio.*

### How can the documentation be improved to help your use case?
Provide example of how the html code will look for an audio/video session using Chime

*For example: Include a section on how to configure the meeting session.*
Provide a simpler example of using Chime on client side 
### What documentation have you looked at so far?

README.md, Amazon Chime SDK Developer Guide, etc.

**Comment by devalevenkatesh** [comment]
Hello @Rajan-Gupta1 ,

Thank you for reporting the issue. I will check with the team on adding a documentation about this. But for now, from the UI side you would need simply need below HTML code to use for a 1:1 audio-video meeting.
```html
<!DOCTYPE html>
<html>
<body>
  <div class="meeting-view">
    <!-- For binding audio element -->
    <audio id="local-audio" style="display: none;"></audio>
    <!-- For binding local video -->
      <video id="local-video" style="border: solid; width: 200px; height: 100px;"></video>
      <!-- For binding remote video -->
      <video id="remote-video" style="border: solid; width: 200px; height: 100px;></video>
  </div>
</body>
</html>
```

```js
async function initializeMeetingSession() {
  const logger = new ConsoleLogger('ChimeMeetingLogs', LogLevel.INFO);
  const deviceController = new DefaultDeviceController(logger);
  // Meeting and Attendee response from CreateMeeting and CreateAttendee API
  const configuration = new MeetingSessionConfiguration(meeting, attendee);
  meetingSession = new DefaultMeetingSession(configuration, logger, deviceController);

  const observer = {
    videoTileDidUpdate: tileState => {
      const videoElement = tileState.localTile ? 'local-video' : 'remote-video';

      // setting the map to know which tileId will be bound to which video element
      if( tileState.localTile ) {
        map.set(tileState.tileId, 'local-video');
      } else {
        map.set(tileState.tileId, 'remote-video');
      }
      meetingSession.audioVideo.bindVideoElement(tileState.tileId, document.getElementById(videoElement));
    }
  };

  meetingSession.audioVideo.addObserver(observer);
  try {
    const audioInputs = await meetingSession.audioVideo.listAudioInputDevices();
    await meetingSession.audioVideo.chooseAudioInputDevice(audioInputs[0].deviceId);
    const videoInputs = await meetingSession.audioVideo.listVideoInputDevices();
    await meetingSession.audioVideo.chooseVideoInputDevice(videoInputs[0].deviceId);
  } catch (err) {
    // handle error - unable to acquire audio device perhaps due to permissions blocking
    console.log("Failed to access the audio video devices might be due permissions blocking");
  }
  meetingSession.audioVideo.bindAudioElement(document.getElementById('local-audio'));
  meetingSession.audioVideo.start();
}
```

Check [API Overview](https://aws.github.io/amazon-chime-sdk-js/modules/apioverview.html) and our README for more information. Check our meeting [demo](https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/browser) if you want to learn more.

**Comment by Rajan-Gupta1** [comment]
@devalevenkatesh Thanks Venkat for the code snippets. What would be the way that a attendee would join the session? I would imagine that the way Chime works is that there would be an https:// link that is send to attendee via email or sms which the attendee will click on which will connect its browser to the session or do I need to build an app which has the audio/video tags that the attendee launches which hosted of my website?
I checked the documentation here [https://docs.aws.amazon.com/chime/latest/dg/build-client-app.html] but could not determine the mechanism. If the attendee clicks a link directly to Chime, where do I get the link from to send via email ?

**Comment by devalevenkatesh** [comment]
Thank you for your feedback. The Amazon Chime SDK for JavaScript provides APIs to create, start and manage a meeting session. It does not provide any link mechanism with existing attendee join flow. Its up to builders how to use the APIs according to their use-case. It differs from use-case to use-case what that implementation would look like.

Now for example in case of link mechanism, you have to implement the logic using your own frontend and a backend application with JS SDKs help. The JS SDK meetingV2 demo's logic is as follows (one of the use case using a form based join):
- The frontend website gives a form to the attendees to put the meeting title and the attendee name. Any attendee who want to join the same meeting would put the same meeting title.
- The attendees fill up the information and a POST request is made to the Node.js backend server. This stores the meeting information in a DDB table so that if we get the same meeting title we would retrieve same meeting and not create a new one. This is also required to join different attendees to the same meeting.
- The server uses `CreateAttendee` and `CreateMeeting` APIs to create the meeting and the attendee. This information is returned when the UI form is submitted and then you do the meeting session initialization.
- In the meeting session initialization we follow [this](https://aws.github.io/amazon-chime-sdk-js/modules/apioverview.html) guide. We create the meeting session configuration using the meeting and attendee creation response from the backend server. Then, we create the device controller, logger and finally create the meeting session. I posted a snippet above which does this.
- Once you create the meeting session, you get access to the `AudioVideoFacade` APIs. Using those APIs you can start-stop the meeting session.
- In case of remote attendees, they will join similarly but all attendees who want to join the same meeting will put the same meeting title to get the same `CreateMeeting` response.
- Hence, in our meetingV2 demo we do not have a link mechanism implemented but its an implementation of form-based join flow.
- Lastly in the UI, you will need one video element to bind your own local video and extra number of video elements to bind the remote attendee videos. The `videoTileDidUpdate` observer helps the UI with an update if someone starts the video. Check the [video use-cases](https://aws.github.io/amazon-chime-sdk-js/#video) in the README to know the implementation snippets. Likewise, the JS SDK provides various observers to let you (UI) know various updates based on which the UI logic can be implemented.
- We highly recommend to take some time to understand the existing meetingV2 demo. I will discuss more within team on your feedback.

You can also checkout the README [usage](https://aws.github.io/amazon-chime-sdk-js/#usage) information which can help understand more.

**Comment by devalevenkatesh** [comment]
We are closing this issue. Please feel free to create new one if you have more questions.
