### ISSUE TITLE
What is a purpose of `dropped` argument in `realtimeSubscribeToAttendeeIdPresence`?

### ISSUE THREAD

**Issue by dimabory** [aws/amazon-chime-sdk-js#1498]
### What are you trying to do?

I'm trying to handle the event whenever an attendee drops and re-joins a meeting after a poor connection becomes good enough.

### How can the documentation be improved to help your use case?

Include a sentence to describe the purpose of this argument.

### What documentation have you looked at so far?

[realtimeSubscribeToAttendeeIdPresence](https://aws.github.io/amazon-chime-sdk-js/interfaces/realtimecontroller.html#realtimesubscribetoattendeeidpresence)

**Comment by devalevenkatesh** [comment]
Hi @dimabory ,
Thanks for reporting the issue.

The Amazon Chime SDK for JavaScript reconnects a meeting session in below scenarios:
- No audio packets (WebRTC)
- Bad audio delay (WebRTC)
- No pong reply (WebSocket)

In these re-connects if an attendee is dropped and does not re-connect successfully, the `dropped` will be set to `true` and the `realtimeSubscribeToAttendeeIdPresence` callback will be called with this update. Thus, the purpose of this `dropped` parameter is to know whether the attendee was dropped due to above mentioned situations. It is also added to differentiate between a attendee's normal leave and the dropped situations.

You can use this `dropped` along-with the `present` parameter to know when an attendee is dropped and if the attendee re-joins the same meeting. In the JS SDK demo we use the `present` parameter to know whether the attendee is not present anymore where we then log the `dropped` parameter and then we add/delete the attendee to/from the roster. Check this code snippet [here](https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/browser/app/meetingV2/meetingV2.ts#L1739-L1742).

The JS SDK internally uses `ListenForVolumeIndicatorsTask` which monitors the audio signal frame information with the attendeeId information. In an re-connect, this task is also run, now if we see that we do not have a specific attendee and that attendee is not muted then we mark that attendee to be dropped and we set the `present` for that attendee to be `false`. The `dropped` status is actually handled by the Amazon Chime backend and we just send an update with `present` as false and the `dropped` status received from the Amazon Chime backend.

Please let us know if you have further questions, I am updating the API documentation with this #1504 PR.

**Comment by devalevenkatesh** [comment]
Closing this issue as the PR is merged now. Please feel free to open new issues if you have further questions.
