### ISSUE TITLE
Want to know this feature has already there?

### ISSUE THREAD

**Issue by mobcoder-deepanshu** [aws/amazon-chime-sdk-js#1555]
The queries that we need to clarify are as below:

1. what about multiview switch like from grid to list or vice versa in case we have attained maximum user view.(in case of 16 people and also in more than 16+ people) through chime sdk.

2. Also please provide clarification and solution for pin functionality for a user during a video call? 

For example- Like we doing video call with 16 people and we pin to one of user to see his full screen video on my side.

So, Is there any way through chime sdk to achieve pin functionality.
Please look into it.

Thanks
Deepanshu Garg

**Comment by xuesichao** [comment]
Hi @mobcoder-deepanshu. This issue seems to be more like asking question than requesting features. JS SDK doesn't deal with UI things, you could just implement whatever you want.

For your questions:
> what about multiview switch like from grid to list or vice versa in case we have attained maximum user view.(in case of 16 people and also in more than 16+ people) through chime sdk.

I don't understand your question very clearly. I think what you can do is to check the number of video tiles, and change your UI accordingly. To do that, you can use `audioVideo.getAllRemoteVideoTiles().length`. 
Besides this, if you want to better control the preference of video sources, you may want to try [`priorityBasedDownlinkPolicy`](https://aws.github.io/amazon-chime-sdk-js/modules/prioritybased_downlink_policy.html). You can use `priorityBasedDownlinkPolicy` to lower the resolution of video sources when the number of video sources go up and hits a threshold to save bandwidth or even drop some of the video sources.

> Also please provide clarification and solution for pin functionality for a user during a video call?

I think the pin functionality you mentioned here is to focus on a specific attendee's camera source in full screen mode or any other way. When you want to pin a specific video. Change the `VideoPreference` of this video source to increase its resolution, and change the CSS style of this video element to fits your need. Or you could rebind this tile to the specific video element you want.

Maybe you can provide us more information to let us better help you. Let me know if you have more questions.
