### ISSUE TITLE
Inbound stream shows no video for active tile

### ISSUE THREAD

**Issue by mark-vanr** [aws/amazon-chime-sdk-js#1703]
### What happened and what did you expect to happen?

During an ongoing meeting, an attendee left briefly and then and re-joined, with their camera enabled. On my client I received the video tile update events and bound the stream to a tile, but the stream didn't appear to start -- webRTC metrics showed 0 inbound bitrate/framerate. This sometimes happens during meetings and resolves after a few seconds, I assume as the stream is negotiated and started, but more rarely (and in this case) the stream never appears to initiate.

For other remote attendees, the same stream from the same attendee was bound and showed correctly. There were also 2 other active video streams in the same meeting which were playing correctly on my client - it was just this one which ended up in this state. This has happened before in our client, for different users during different meetings, but is fairly rare.

We are using simulcast and the `VideoAdaptiveProbePolicy`

Screenshot of the tile that did not start, with the stats reported from `metricsDidReceive` showing in the overlay.

![Screenshot from 2021-10-21 10-58-28](https://user-images.githubusercontent.com/66750108/138313011-b28325a3-f20a-45c5-b722-49a1ce01aa6e.png)

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Unfortunately this happens somewhat rarely and I haven't yet been able to find a deterministic way to cause it

### Amazon Chime SDK for JavaScript version

2.19.0

### What browsers are you seeing the problem on?

Chrome

### Browser version

Version 94.0.4606.81 (Official Build) (64-bit)

### Meeting and Attendee ID Information.

"attendeeId":"0b60c535-3906-7941-709d-714e2108aa54"  <-- the attendee whose video stream was not playing on my client

### Browser console logs

Unfortunately only managed to capture verbose logs from the receiving side, not the sender. The logs included are from the whole meeting, but relevant logs are around/post timestamp "1634828242980" - the issue occurred after the logged event 'setting layout to: grid' but the inbound video stream did show successfully for a moment after that before the described issue occurred.

[verbose_no_video_received.log](https://github.com/aws/amazon-chime-sdk-js/files/7391151/verbose_no_video_received.log)

**Comment by simmkyu** [comment]
### Chime server logs

The Chime server logs indicate that the sender (`0b60c535`) successfully shared a video at 10/21/21 14:56:39 (GMT), and the receiver (`9fccf71e`) had no problem viewing this video. I could not find any failure events, such as the drop event, at around 14:57:22 (converted from timestamp `1634828242980`). It seems that the Chime SDK for JavaScript or your client application had an issue binding a video tile.

⠀

####  Server events of the sender (0b60c535)

Time (GMT) | Action
--|--
10/21/21 14:31:30 | Created an attendee (0b60c535-3906-7941-709d-714e2108aa54) using the CreateAttendee or BatchCreateAttendees API in your server application.
10/21/21 14:31:32 | Joined the meeting (1st)
10/21/21 14:32:16 | Left the meeting
10/21/21 14:32:26 | Joined the meeting (2nd)
10/21/21 14:50:55 | Left the meeting
10/21/21 14:56:37 | Joined the meeting (3rd)
10/21/21 14:56:39 | Started a local video
**10/21/21 14:57:22<br>(1634828242980)** | **No event found**
10/21/21 14:59:36 | Left the meeting

⠀

### Server events of the receiver (9fccf71e)

Time (GMT) | Action
--|--
10/21/21 14:31:02 | Created an attendee (9fccf71e-2ab6-1aa5-84ed-fa0bfc831069) using the CreateAttendee or BatchCreateAttendees API in your server application.
10/21/21 14:31:04 | Joined the meeting
10/21/21 14:55:58 | Stopped viewing the content sharing from another attendee.
**10/21/21 14:57:22<br>(1634828242980)** | **No event found**
10/21/21 14:59:36 | Left the meeting

⠀

### Client logs of the receiver (9fccf71e)

In the attached [verbose_no_video_received.log](https://github.com/aws/amazon-chime-sdk-js/files/7391151/verbose_no_video_received.log), the Chime SDK for JavaScript triggered `videoNotReceivingEnoughData` and `estimatedDownlinkBandwidthLessThanRequired` many times with the following messages:

```
Downlink video streams are not receiving enough data
Downlink bandwidth pressure is high: estimated bandwidth ...
```

⠀

The Chime SDK for JavaScript calls these observer methods when ​one or more remote attendee video streams do not meet the expected average bitrate which may be due to downlink packet loss.

Our [simulcast guide](https://aws.github.io/amazon-chime-sdk-js/modules/simulcast.html#downlink--bandwidth-policy) says:

> When using the policy it is recommended that applications do not take action on the downlink monitoring events such as videoNotReceivingEnoughData or estimatedDownlinkBandwidthLessThanRequired since it may conflict with decisions being made within the policy.

Do you perform any custom logic in these observer methods?

**Comment by mark-vanr** [comment]
@simmkyu I appreciate the thorough investigation and explanation! Since the guide said not to take action, we not do anything on the downlink monitoring events `videoNotReceivingEnoughData` and `estimatedDownlinkBandwidthLessThanRequired` other than output a debug log.
It certainly does seem like something on the `bind` is going wrong - either failing or taking longer than expected. There aren't visible errors thrown to or by the local client at the time; any further detail you need regarding the client operations at the time? 

As a side note - the core conditional to trigger a bind when we receive a `videoTileDidUpdate` event for a given `tileState` is `tileState.tileId != null && !tileState.paused` - is there any other state or trigger we should be watching instead?

**Comment by hensmi-amazon** [comment]
I have been able to localize the issue to the same as https://github.com/aws/amazon-chime-sdk-js/issues/1797 .  The fix for that has been deployed, so will close this. Please reopen (or cut a new issue) if you continue to see freezes like mentioned.

That binding mechanism sounds correct to me.
