### ISSUE TITLE
Follow-up: The AudioContext was not allowed to start.

### ISSUE THREAD

**Issue by kubiksamek** [aws/amazon-chime-sdk-js#1744]
### What happened and what did you expect to happen?

Follow-up for https://github.com/aws/amazon-chime-sdk-js/issues/624

When joining a meeting with muted "Sound" in Site settings, Chime is not able to connect.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

- Change setting (set Sound to Mute) for meeting url in Chrome settings (chrome://settings/content/siteDetails).
- Reload meeting
- Meeting console log contains
```
The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
```
and `useRosterState` hook will return `{}` without my attendee.
-- This is same as for default site setting, that is "Automatic (Default)"
- It will return proper object after audio is started

- When set to Allow, it will not display specified log and hook will return my attendee immediately.

### Amazon Chime SDK for JavaScript version

2.19.0

### What browsers are you seeing the problem on?

Google Chrom

### Browser version

95

### Browser console logs

```
DefaultDeviceController.js?66c1:1594 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
DefaultDeviceController.js?66c1:882 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
```

**Comment by ltrung** [comment]
So JS SDK relies on audio for roster (or attendee presence) and if there is no audio, the roster will return {}.
The error `The AudioContext was not allowed to start` was thrown by Chrome when there is no user interaction. This seems like our library tries to create an empty audio in order to join meeting using AudioContext but there is no user interaction so Chrome blocks it.

**Comment by kubiksamek** [comment]
Is there any workaround for this?

**Comment by ltrung** [comment]
We usually workaround this by having users interact with the web app (e.g., clicking on a button).

**Comment by kubiksamek** [comment]
I see, thanks for the info.

**Comment by mmarekbb** [comment]
@ltrung Do you have a suggestion on fixing this? Chrome blocks it because like you said, there is no user interaction. For our use case, it is perfectly normal to be in a meeting where there is no audio coming through for some time (and we don't necessarily want to require audio permissions unless the attendee uses their microphone).

Does the Chime SDK expose the AudioContext so that we can call resume on it when clicking on a button in our app?

**Comment by mmarekbb** [comment]
Will there be a consideration to make the roster function independently on the audio? It does not seem that related to it.

**Comment by ltrung** [comment]
AudioContext is blocked from the browser so even if we expose it and you call resume it will be the same. User interaction does not mean device permission though. It just means users have to interact with your sites (like clicking a button).

**Comment by ltrung** [comment]
> Will there be a consideration to make the roster function independently on the audio? It does not seem that related to it.
I don't think we have a public feature request for it yet. Feel free to open a feature request using our Community Request Template.

**Comment by mmarekbb** [comment]
If I understand this correctly, Chime creates the AudioContext when connecting and since there's no user interaction (because device labels is set to None), it fails with the warning. After this, the SDK does not try to call resume on it automatically, so there's no way to recover from the problem.

We need a way to either access the AudioContext that the SDK creates so we can call resume on it _during some sort of a user interaction_ or somehow tell the SDK that it can instantiate the audio context during a specified action - for example clicking on a welcome button.

**Comment by ltrung** [comment]
Yes, the device label is set to None just means Chime JS SDK will create an empty audio device to join the call using AudioContext but in this case, Chrome blocks the empty audio device to play due to no user interaction.

I think you do not need to call resume in this case. It should work if users interact with the site right before joining (clicking on a welcome button) as Chrome should allow the audio context to play then.

**Comment by ltrung** [comment]
Closing but feel free to reopen if you have any more issues.
