### ISSUE TITLE
DefaultVideoTransformDevice is not working on Safari

### ISSUE THREAD

**Issue by artem6connex** [aws/amazon-chime-sdk-js#1758]
### What happened and what did you expect to happen?

DefaultVideoTransformDevice is not working on Safari v15.1
I can not see my own video tile but other attendees are able to see it

I assume it's happening because of [this issue](https://bugs.webkit.org/show_bug.cgi?id=229611) on Safari
If not let me know what causes this problem and is there any workaround to fix it?

P.S. I've checked [your demo](https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/browser) and you've got the same problems with Safari as well

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

try to use DefaultVideoTransformDevice

### Amazon Chime SDK for JavaScript version

2.20.1

### What browsers are you seeing the problem on?

Safari

### Browser version

15.1

### Browser console logs

no logs

**Comment by ltrung** [comment]
This is documented in the known issue thread #1059. Video transform does not work in Safari 15 due to:
> Video Frame Processor does not work in Safari 15 and will throw OverconstrainedError (Safari 15 bug).
Video Frame Processor sends black or red images in Safari 15 due to a bug in canvas.captureStream (Safari 15 bug). For a temporary workaround, you can copy the output content in VideoFrameProcessor.process method to another canvas and use that canvas to render the output video.

The first bug with Overconstrained seems to have been fixed in the Technology Preview but  I can still the see the second issue with black/ red image on the local client. 
For the workaround, can you follow the suggestion above and copy the output content in VideoFrameProcessor.process method to another canvas and use that canvas to render the output video instead of binding to a video element?

**Comment by artem6connex** [comment]
@ltrung Thank you for the response!
I'm gonna implement this workaround
hope it'll fix my issue

**Comment by devalevenkatesh** [comment]
Closing the issue due to the provided FAQ and added workaround. Please feel free to re-open if still an issue.

**Comment by artem6connex** [comment]
Hey @ltrung 
For now, I have to redraw my canvas with at least 20 FPS and it causes a huge problem with performance
Is there another workaround that would cause less CPU consumptions in my case?
