### ISSUE TITLE
Chime meeting eventBridge events: meetingEnded not received

### ISSUE THREAD

**Issue by abhimanusharma** [aws/amazon-chime-sdk-js#1785]
### What happened and what did you expect to happen?

I started a meeting with single user and without audio. What happened?:

1. meetingStarted
2. attendeeAdded
3. Meeting did not stopped after 5 minutes of no audio.
4. Recording started: mediaPipelineInProgress
5. Now wait for 45 minutes, meeting did not end with single user with no audio.
6. attendeeLeft (last and only attendee left event), User left/ close browser/tab then no user join in that meeting for 5-30 minutes.
7. There is no meetingEnded event is triggered for that meeting even after 2 hours of wait.
8. I noticed that the chime:MediaPipelineDeleted event triggered automatically after some time. This might happen because of lot of reason.
9. I want to catch all the events when meeting ended unexpectedly to perform final operations in the backend.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

1. Create a new meeting
2. Join the meeting with a single user
3. Start the recording
4. wait for 5-45 minutes without audio.
5. See the events triggered by the eventBridge

### Amazon Chime SDK for JavaScript version

"amazon-chime-sdk-js": "2.16.1",

### What browsers are you seeing the problem on?

Google Chrome

### Browser version

Version 95.0.4638.54 (Official Build) (64-bit)

### Meeting and Attendee ID Information.

MeetingId: 'cff0e00e-f533-45df-8454-e6f2c7ec0706'
AttendeeId: '52f2bbfe-8488-e450-d7e4-1bc2aa88d456'

### Browser console logs

N/A

**Comment by vincebai** [comment]
Can we get some info on the time the meeting was created so I can check the appropriate logs?

**Comment by devalevenkatesh** [comment]
I checked backend events on the provided MeetingId and AttendeeId and find that the meeting was auto-ended.

MeetingId: `cff0e00e-f533-45df-8454-e6f2c7ec0706`
AttendeeId: `52f2bbfe-8488-e450-d7e4-1bc2aa88d456`

11/11/21 01:23:02 - Meeting created 
11/11/21 01:23:04 - Attendee added (`52f2bbfe-8488-e450-d7e4-1bc2aa88d456`)
11/11/21 01:23:10 - Above attendee presence triggered and joined successfully
11/11/21 01:23:26 - Another attendee was added (`6003ded0-1a6d-8bd0-dc0e-e11d424959a5`)
11/11/21 01:44:46 - Attendee `52f2bbfe-8488-e450-d7e4-1bc2aa88d456` left
11/11/21 02:15:04 - Meeting auto-ended
11/11/21 02:15:04 - Second attendee left `6003ded0-1a6d-8bd0-dc0e-e11d424959a5`.

The meeting auto-ended some time later because even though first attendee left, there was one more attendee present in the meeting.

@vincebai can you check based on this.

**Comment by vincebai** [comment]
I see in our application logs that we published an event bridge message with for this meeting with MeetingEnded event at 2021-11-11T02:15:05.006. Looping in EventBridge team for further investigation and will get back to you.

**Comment by vincebai** [comment]
Hello. I was unable to get traction on this issue from EventBridge team but EventBridge messages are best effort and occasionally messages may be dropped due to a service error or outage on EventBridge side. If you are continually seeing this issue, please feel free to reopen with more data and we will further investigate.

**Comment by devalevenkatesh** [comment]
Closing this issue with the updates provided above. Please file a new or re-open this if you are continuously running into the same issue with same details like meetingId.

**Comment by saurabhghadi0401** [comment]
Hi @devalevenkatesh, I tried with AWS EventBridge to get meeting events. 
I have setup the rule for meetingStarted and meetingEnded events and log them on cloudwatch. But still, I am unable to get those events. I was getting events related to attendeeJoined and attendeeDropeed.
![image](https://user-images.githubusercontent.com/62549260/182307308-e60a6b65-93a4-4356-ac23-1777f3eaeac5.png)

Here are the meeting details: 
meeting ID: 7549812c-b909-47f1-aded-df88419a0706
![image](https://user-images.githubusercontent.com/62549260/182310759-50cf0fcc-fb5b-4b1f-9077-c3b81308403e.png)

**Comment by saurabhghadi0401** [comment]
Hey @devalevenkatesh , I am getting meetingStarted event as well.  if there is only one participant in a meeting then after 4-5  mins I am getting  **meetingEnded** event and that's default behavior of chime I know. So, let's say I stopped meeting using **audioVideo.stop()** then I  will get the same event right? Or do I need to end the meeting using **chime.deleteMeeting()** as given in : https://github.com/aws/amazon-chime-sdk-js/blob/main/demos/serverless/src/handlers.js#:~:text=exports.end%20%3D%20async%20(event%2C%20context  to get that event on eventBride
