### ISSUE TITLE
How to test meeting session with over 100 attendees

### ISSUE THREAD

**Issue by JunedBrilworks** [aws/amazon-chime-sdk-js#1789]
We have an application built-in using chime SDK. Our customers are frequently complaining about reconnecting issues (on `audioVideoDidStartConnecting` we are showing reconnecting UI until connected again) even though they have a good connection. This issue mostly occurs when the attendee's count is greater than 50. 

Just for note, we have already applied video prioritization and also we are decreasing video quality as attendee count increases. From logs, we can see `poorConnectionCount` and `retryCount` indicate some have network issues but the complaints are increasing.

can anyone help how to test such scenarios? To find out if the issue is in our implementation/library/connectivity issue.

Any suggestion on how we can test such scenarios like testing with 100 or 200 participants as it's difficult to get such a huge number of attendees in day-to-day testing.

**Comment by devalevenkatesh** [comment]
Thank you for reporting the issue.

The `audioVideoDidStartConnecting` is triggered when the SDK tries to re-connnect and at the initial start when you call `meetingSession.audioVideo.start()`. You should be getting the `audioVideoDidStartConnecting` with `receonnecting` parameter as a boolean, it will be `true` in re-connection and `false` if just normal initial start.

So, I assume, you have implemented `audioVideoDidStart` and showing banner from the `audioVideoDidStartConnecting` when `reconnecting` is `true` until `audioVideoDidStart`. Please let me know if this is correct?

This reconnecting FAQ explains when JS SDK triggers reconnection:
https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html#when-does-the-amazon-chime-sdk-retry-the-connection-can-i-customize-this-retry-behavior

We have a guide with few suggestions on the quality, request you to please go through the same:
https://aws.github.io/amazon-chime-sdk-js/modules/qualitybandwidth_connectivity.html

We have suggested various observers which you can listen to improve the performance overall.

Few next steps you can take:
1. Provide more information on attendee usage? Either mobile or any specific machine specs or problem with any specific browsers.
2. Since, this looks network related but have you considered profiling your app with the [Chrome performance dev tools](https://developers.google.com/web/tools/chrome-devtools/evaluate-performance) to see what's taking up the majority of processing.
3. Provide few browser console logs for affected attendees by integrating ConsoleLogger in your app if not already. Please check this [FAQ](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html#how-can-i-get-amazon-chime-sdk-logs-for-debugging).

For testing, we use our [meeting demo](https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/browser) as the test bed, so you may want to consider checking the demo implementation or compare results against it. You would still have to implement a mechanism to join 100 attendees to a meeting and we do not have a mechanism currently, but you have to use [puppeteer](https://developers.google.com/web/tools/puppeteer) or [playwright](https://playwright.dev/) to trigger browser sessions and add attendees and run through your app normally like a user would do and then collect data for a deep dive.

I will check more within team if I can add more to this. Thanks!

**Comment by JunedBrilworks** [comment]
@devalevenkatesh 
`So, I assume, you have implemented audioVideoDidStart and showing banner from the audioVideoDidStartConnecting when reconnecting is true until audioVideoDidStart. Please let me know if this is correct?`

yes that's correct

**Comment by JunedBrilworks** [comment]
Here are some event logs for the recent meeting. If it's helpful.  
[logs-insights-results.csv](https://github.com/aws/amazon-chime-sdk-js/files/7536223/logs-insights-results.csv)

**Comment by JunedBrilworks** [comment]
@devalevenkatesh  any update?

**Comment by devalevenkatesh** [comment]
Hi @JunedBrilworks ,

Thanks for providing some insight into the events. From the attached logs there are three types of failures I can see:
1. The signaling connection was closed with code 4403 and reason: attendee unavailable
2. WebSocket connection failure:
```
serial group task AudioVideoStart/269bef8f-b92f-4fe3-9ec1-21b2444c0706/eb1900a5-eb39-c1cf-8ea4-ce6ad2200192 was canceled due to subtask AudioVideoStart/269bef8f-b92f-4fe3-9ec1-21b2444c0706/eb1900a5-eb39-c1cf-8ea4-ce6ad2200192/Timeout15000ms error: serial group task AudioVideoStart/269bef8f-b92f-4fe3-9ec1-21b2444c0706/eb1900a5-eb39-c1cf-8ea4-ce6ad2200192/Timeout15000ms/Peer was canceled due to subtask AudioVideoStart/269bef8f-b92f-4fe3-9ec1-21b2444c0706/eb1900a5-eb39-c1cf-8ea4-ce6ad2200192/Timeout15000ms/Peer/SubscribeAndReceiveSubscribeAckTask (once) error: serial group task Signaling was canceled due to subtask Signaling/Timeout15000ms (once) error: WebSocket connection failed
```

We have an FAQ about these failures: https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html#what-does-it-mean-when-the-amazon-chime-sdk-for-javascript-throws-an-error-with-status-code-signalingbadrequest-meetingended-or-signalinginternalservererror-while-establishing-a-signaling-connection-to-the-chime-servers

The provided are just meeting events, could you be able to provide browser console logs for these attendees. Also request you to go through our Networking FAQs for issue on the Websocket connection failures.

**Comment by jing-chen1** [comment]
Closing it, feel free to reopen if you still have problems.
