### ISSUE TITLE
Question: How to re-create a meeting with same meeting title. If left meeting by accident.

### ISSUE THREAD

**Issue by abhimanusharma** [aws/amazon-chime-sdk-js#1793]
This question is related to Chime SDK js and not Chime application.

### What are you trying to do?

Scenario 1: Suppose I created a meeting and joined the meeting and by mistake closed the tab, then due to network issue I joined the same meeting after 5 minute. Then I am getting error meeting not found.
Scenario 2: Suppose I have scheduled a meeting from my application for Nov 17 at 12:50 and host joined the meeting early by accident like 12:40 and then left immediately. When any user try to join the meeting at the scheduled time. The meeting link not found error is coming up,

### How can the documentation be improved to help your use case?

Just add a method to reCreate the meeting with same title, as the PSTN user who already have the title will face issue joining if we change the meeting title on runtime when this error occurs.

### What documentation have you looked at so far?

README.md, Amazon Chime SDK Developer Guide, etc.

**Comment by michhyun1** [comment]
Hopefully you saw this guide in our docs: 
https://docs.aws.amazon.com/chime/latest/dg/create-mtgs.html
```
A meeting automatically ends after a period of inactivity, such as the following:
No audio connections are present in the meeting for more than five minutes.
Less than two audio connections are present in the meeting for more than 30 minutes.
Screen share viewer connections are inactive for more than 30 minutes.
The meeting time exceeds 24 hours.
```
Are you storing your meetings in some DDB - similar to how its done in the JS SDK demo? If a createMeeting API call is made with the same meeting title as another meeting that has already ended, then you should be able to call createMeeting and re-use the meeting title. Just note that the meeting id will be a new meeting id.

**Comment by devalevenkatesh** [comment]
@abhimanusharma as Michael pointed the auto-end policies you will get the same error if someone creates the meeting and joins it.

You can create the meeting with the same meeting title and I think Amazon Chime meeting does not have any constraint on the ExternalMeetingId as far as I checked here:
https://docs.aws.amazon.com/chime/latest/APIReference/API_CreateMeeting.html#API_CreateMeeting_RequestSyntax

For creating the same meeting or re-using it I think the Amazon Chime SDK meeting creation needs to get same `ClientRequestToken` which acts as a unique identifier to the created meeting. The meeting-title is a demo concept and actually maps to `ExternalMeetingId` in the `CreateMeeting` API.

If you are following the meetingV2 demo in our repo, that has a custom logic to handle the meeting creation based on meeting-title, we check whether the meeting-title if already existing we try to use the same meeting other-wise create a new one and then cache it. Since, this is something which varies by builder implementation we do not have any documentation around it.

Please let us know if you have more questions.
