### ISSUE TITLE
Attendee dropped

### ISSUE THREAD

**Issue by beta-alpha001** [aws/amazon-chime-sdk-js#1840]
### What happened and what did you expect to happen?

Attendee dropped in the middle of call while speaking but cannot find any log that explains this. There were no Errors or Warnings throughout the call.
Also received multiple logs like these however attendee has unmuted just once throughout the call
`received the mute event for tile\u003d1 id\u003d2533a108-a4b5-44bc-88c7-0ded23cc4a5e streamId\u003d5`
`received the unmute event for tile\u003d1 id\u003d2533a108-a4b5-44bc-88c7-0ded23cc4a5e streamId\u003d5`

We have all info level logs in the file attached, also can you please suggest the logs to look for in such cases, and cases where attendee is unable to hear other participant. We get 1/10 calls where attendee is not able to hear another participant.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Happens randomly, no exact steps to reproduce.

### Amazon Chime SDK for JavaScript version

2.17.0

### What browsers are you seeing the problem on?

edge-chromium

### Browser version

95 (95.0.1020)

### Meeting and Attendee ID Information.

Meeting Id- a490f130-8f62-42d5-b391-ea8bfc260706
Problematic attendee Id (that dropped from call) - b2bf2d07-272f-3d17-16c3-0c825aafe07e

### Browser console logs

events -
[events-chime.txt](https://github.com/aws/amazon-chime-sdk-js/files/7623504/events-chime.txt)

logs -
[logs.txt](https://github.com/aws/amazon-chime-sdk-js/files/7623509/logs.txt)

**Comment by simmkyu** [comment]
According to the Chime server logs, the attendee (`b2bf2d07-272f-3d17-16c3-0c825aafe07e`) was never dropped from the meeting. The attendee successfully joined the meeting at 13:34:33, muted the microphone for 5 seconds, and left a meeting at 13:36:16. These server events match log messages in the [attached browser logs](https://github.com/aws/amazon-chime-sdk-js/files/7623509/logs.txt).

Time|Action
--|--
11/10/21 13:34:12 | Created using CreateAttendee, BatchCreateAttendees, or CreateMeetingWithAttendees API in your server application
11/10/21 13:34:33 | Joined a meeting in a browser
11/10/21 13:34:43 | Muted using `meetingSession.audioVideo.realtimeMuteLocalAudio` API
11/10/21 13:34:48 | Unmuted using `meetingSession.audioVideo.realtimeUnmuteLocalAudio` API
11/10/21 13:36:16 | Left a meeting

⠀

---

> We have all info level logs in the file attached, also can you please suggest the logs to look for in such cases, and cases where attendee is unable to hear other participant

If an attendee experiences a drop event, the Chime SDK for JavaScript should output `WARN` or `ERROR` messages explaining reasons. The Chime SDK for JavaScript may attempt to retry the connection. In that case, it outputs a warning message like the following:

```
[WARN] reconnection recommended due to: no packets received: true, missed pongs: false, bad audio delay: false
```

⠀

### Question

What did other attendees experience when this attendee (`b2bf2d07-272f-3d17-16c3-0c825aafe07e`) was dropped? Is there any chance other attendees had a network issue viewing the attendee `b2bf2d07`'s audio or video?

**Comment by beta-alpha001** [comment]
Hi @simmkyu , we log actions performed by user - and in this case there was no end call action for `b2bf2d07-272f-3d17-16c3-0c825aafe07e`.
Also, when we call `meetingManager.leave()` there are some logs like - `running task ReleaseMediaStreamsTask`, `stopContentShare`, `stopLocalVideoTile`, `unbindAudioElement`, `chooseVideoInputDevice null`, etc which were not present here but the second participant received updated rosterState with one participant so I assumed may be participant dropped due to some other reason.

**Comment by simmkyu** [comment]
## Missing browser logs?

> We log actions performed by user - and in this case there was no end call action for b2bf2d07.

Yes, for example, the Chime SDK for JavaScript should output the following transition message when an attendee leaves a call.

```
transitioning from Disconnecting to NotConnected with Disconnect
```

Note that the [attached browser logs](https://github.com/aws/amazon-chime-sdk-js/files/7623509/logs.txt) contain transition messages for the initial connection, such as `transitioning from Connecting to Connected with FinishConnecting`.

The last message occurred on `2021-11-10T13:36:11.792Z`, so I guess that your application failed to capture Chime SDK logs after this timestamp. Is there any chance that your application misses those logs, such as redirecting to a different URL?

⠀

## No video from the attendee (`b2bf2d07`)?

> Other participant did not have network issue as there was no poor connection or reconnection log, only the video tile of dropped attendee was removed.

Both Chime server and browser logs indicate that the attendee (`b2bf2d07`) has never started a video. For example, the browser logs do not contain the `startLocalVideoTile` keyword.

Only one attendee (`f10002e4`) in the same meeting started a video. I updated the Chime SDK server event table:
⠀

Time|Action
--|--
11/10/21 13:34:12 | You created the attendee (`b2bf2d07`) using CreateAttendee, BatchCreateAttendees, or CreateMeetingWithAttendees API in your server application.
**11/10/21 13:34:32** | **Another attendee (`f10002e4`) started a video.**
11/10/21 13:34:33 | The attendee (`b2bf2d07`) joined a meeting in a browser.
11/10/21 13:34:43 | The attendee (`b2bf2d07`) muted itself using `meetingSession.audioVideo.realtimeMuteLocalAudio` API.
11/10/21 13:34:48 | The attendee (`b2bf2d07`) unmuted itself using `meetingSession.audioVideo.realtimeUnmuteLocalAudio` API.
11/10/21 13:36:16 | The attendee (`b2bf2d07`) left a meeting.

⠀

The following mute/unmute events tell that the attendee (`b2bf2d07`) had an issue viewing another attendee (`f10002e4`)'s video, possibly due to the sender or receiver's bandwidth problem.

```
received the mute event for tile\u003d1 id\u003d2533a108-a4b5-44bc-88c7-0ded23cc4a5e streamId\u003d5
received the unmute event for tile\u003d1 id\u003d2533a108-a4b5-44bc-88c7-0ded23cc4a5e streamId\u003d5
```

⠀

Otherwise, I don't see any "drop" event in the Chime SDK server side for this meeting.

Could you upload browser logs of both sender and receiver attendees when this situation happens again?

**Comment by beta-alpha001** [comment]
Sure, will do when this happens again. Till then I think we can close this issue

**Comment by xuesichao** [comment]
Close the issue for now. Feel free to reopen it if it happens again.
