### ISSUE TITLE
DefaultVideoTransformDevice is not working on Safari 15.1

### ISSUE THREAD

**Issue by amneeshsoftobiz** [aws/amazon-chime-sdk-js#1843]
my same code is working for chrome and all other browsers, but it os not working on safari

`const transformDevice = new Chime.DefaultVideoTransformDevice(
logger,
selectedVideoOutputDeviceId,
[processor]  // VirtualBackgroundProcessor implements VideoFrameProcessor
);`

getting OverconstrainedError that deviceId is not supported.

**Comment by ltrung** [comment]
It is a known issue in Safari 15 and 15.1 as documented in the pinned known issue https://github.com/aws/amazon-chime-sdk-js/issues/1059: 
>Video Frame Processor does not work in Safari 15 and will throw OverconstrainedError (Safari 15 bug).
Video Frame Processor sends black or red images in Safari 15 due to a bug in canvas.captureStream (Safari 15 bug). For a temporary workaround, you can copy the output content in VideoFrameProcessor.process method to another canvas and use that canvas to render the output video as seen in
DefaultVideoTransformDevice is not working on Safari #1758.
