### ISSUE TITLE
us-east-1

### ISSUE THREAD

**Issue by OliverEberlei** [aws/amazon-chime-sdk-js#1857]
### What happened and what did you expect to happen?

Since us-east-1 went down today, we had issues with our chime service. Our meetings are created in eu-central-1, so I am wondering if there are any best practices to deal with this situation. Did I do sth wrong or is it currently not possible to decouple the chime SDK from us-east-1?

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Try to connect create meetings on December 7th, 2021.

### Amazon Chime SDK for JavaScript version

2.9.0

### What browsers are you seeing the problem on?

All

### Browser version

Any

### Browser console logs

Error executing "CreateMeeting" on "https://chime.us-east-1.amazonaws.com/meetings"; AWS HTTP error: Server error: `POST https://chime.us-east-1.amazonaws.com/meetings` resulted in a `500 Internal Server Error` response:
{"Code":"ServiceFailure","Message":"Service has experienced an unexpected failure","RequestId":"38b9239c-3817-441c-bf06- (truncated...)

**Comment by simmkyu** [comment]
Sorry for the inconvenience. You may have set a media region to `eu-central-1`, but a control region is still `us-east-1`.

From the [Meeting Regions guide](https://docs.aws.amazon.com/chime/latest/dg/chime-sdk-meetings-regions.html):
> Amazon Chime SDK meetings have _control regions_ and _media regions_. A control region has an API endpoint used to create, update and delete meetings, and media regions host the actual meetings. 

⠀

Recently, we introduced the [Chime SDK Meetings namespace](https://docs.aws.amazon.com/chime/latest/APIReference/API_Operations_Amazon_Chime_SDK_Meetings.html) that supports other control regions. Please follow the steps in the [Migrating to the Amazon Chime SDK Meetings namespace](https://docs.aws.amazon.com/chime/latest/dg/meeting-namespace-migration.html) guide so that you can use `eu-central-1` for both the control region and media region. Note that this new namespace has limitations, such as no tagging support.

**Comment by OliverEberlei** [comment]
Thank you for your response. I implemented our chime SDK back when we still had to connect to us-east-1 for the control region and missed this update. Very happy that this is possible now, thank you for your great work :)
