### ISSUE TITLE
Content share tiles disapearing while using default video downlink and uplink policies

### ISSUE THREAD

**Issue by gustavofamorim** [aws/amazon-chime-sdk-js#1887]
### What happened and what did you expect to happen?

After upgrading chime SDK from version 2.17.0 to version 2.23.0, when a attendee starts a content share the video tile for other attendees gets removed temporarily in a intermitent manner. This causes the binded video element to disappear when the tile is removed.

It's important to notice that I'm not changing defaults downlink and uplink policies via `videoDownlinkBandwidthPolicy` and `videoUplinkBandwidthPolicy`. These methods are not even called. Also we are using simulcast.

In our app, this problem never occured with version 2.17.0 before. In the wrost cases the content share quality drops, but the tile is never removed untill the user decides to stop the content sharing.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

1. Enter meeting room with two attendees;
2. Start a content share from one attendee;
3. The attendee that is seen the content share, sometimes, gets missing video tile.

### Amazon Chime SDK for JavaScript version

2.23.0

### What browsers are you seeing the problem on?

Chrome

### Browser version

96.0.4664.110

### Meeting and Attendee ID Information.

Meeting id: 3291f2a1-2337-45b3-b27b-c1190f910706
Attendee id that started the conrtent share: c415d700-1f4f-c190-03b4-ef64b4a2b61e
Attendee id that have content share tile inactivated: 67c27112-56db-f49c-33b8-f08d34564770

### Browser console logs

Attendee c415d700-1f4f-c190-03b4-ef64b4a2b61e LOGS: [localhost-1639754623738.log](https://github.com/aws/amazon-chime-sdk-js/files/7736194/localhost-1639754623738.log)

Attendee 67c27112-56db-f49c-33b8-f08d34564770 LOGS: [localhost-1639754621430.log](https://github.com/aws/amazon-chime-sdk-js/files/7736204/localhost-1639754621430.log)

In the logs, the attendees starts and stops content sharing sometimes, but in the last share (started by the attendee id c415d700-1f4f-c190-03b4-ef64b4a2b61e) the problem occured.

**Comment by ltrung** [comment]
The behavior you described is due to this change https://github.com/aws/amazon-chime-sdk-js/pull/1614 which changes the defaut downlink policy from `AllHighestVideoBandwidthPolicy` to `VideoAdaptiveProbePolicy` to be the same as mentioned in the [Simulcast guide](https://github.com/aws/amazon-chime-sdk-js/blob/master/guides/05_Simulcast.md). 
Instead of trying to subscribe to all videos at the highest resolutions (which is not good for bandwidth), adaptive policy will try to subscribe to videos based on the browser downlink estimate. If there is not enough bandwidth, it will drop video.

To restore the previous behavior, you could set the `videoUplinkBandwidthPolicy` in configuration to `AllHighestVideoBandwidthPolicy` but depending on your use case, it might not be the best option. You can also consider [priority-based downlink policy](https://github.com/aws/amazon-chime-sdk-js/blob/v2.20.0/guides/11_Priority_Based_Downlink_Policy.md) so that you will receive notifications when a video is paused (instead of dropping).

**Comment by haofiltered** [comment]
I had the same issue on our end, I have to turn off simulcast to avoid this kind of issue happening. 
Keep an eye on this issue.

**Comment by gustavofamorim** [comment]
@ltrung I've updated my code to use the `AllHighestVideoBandwidthPolicy` and now it works flawlessly. Very thank you to help with this.

I was using the documentation page [Quality, Bandwidth, and Connectivity](https://aws.github.io/amazon-chime-sdk-js/modules/qualitybandwidth_connectivity.html#configure-a-video-downlink-policy) as a base for the update and I've not seen the Simulcast guide that you've mentioned. Since this page curerntly does't mention that the simulcast uses a different downlink policy, I couldn't figure out what the problem was.

I've propoused the pull request #1911 to improve the documentation, maybe other developers also have the same doubt.

**Comment by ltrung** [comment]
@gustavofamorim Here is the Simulcast guide https://aws.github.io/amazon-chime-sdk-js/modules/simulcast.html

**Comment by ltrung** [comment]
@gustavofamorim Depending on how many users have video on in a meeting, the default `AllHighestVideoBandwidthPolicy` may not be the best one to use. Can you try the `VideoPriorityBasedPolicy` and see if it works well for you?

**Comment by jing-chen1** [comment]
Closing it due to inactivity.
