### ISSUE TITLE
Video stream are paused even though having bandwidth availability.

### ISSUE THREAD

**Issue by JunedBrilworks** [aws/amazon-chime-sdk-js#1899]
### What happened and what did you expect to happen?

We have a video downlink policy applied in our application. We have noticed even though we are having enough bandwidth video tiles are remaining in the paused state specifically on **firefox** (logs are for Mac OS 11.1 & Firefox 95.0.2 but have been observed on all browsers). For the attached meeting's logs, I was having around 40 Mbps upload speed and 35-37 Mbps download speed in that case also all remote video tiles were paused for me (also no other app opened that could consume lots of bandwidth). 

In an implementation, on **`realtimeSubscribeToAttendeeIdPresence`** & **`subscribeToActiveSpeakerDetectoractive`** speakers change (with 2000 ms throttle) and giving high priority to screen/content share and active speakers. Here is code snippet of how we are defining priorities.

```
  updateDownlinkPreference = () => {
    const videoPreferences = VideoPreferences.prepare();
    for (const attendeeId in this.roster) {
      if (this.roster[attendeeId]) {
        const attendee = this.roster[attendeeId];
        let targetDisplaySize;
        if (attendee.videoPriority === 1) {
          targetDisplaySize = TargetDisplaySize.High;
        } else if (attendee.videoPriority === 2) {
          targetDisplaySize = TargetDisplaySize.Medium;
        } else {
          // priority 3/4
          targetDisplaySize = TargetDisplaySize.Low;
        }
        if (attendee && attendee.hasVideo) {
          videoPreferences.add(
            new VideoPreference(attendeeId, attendee.videoPriority || 4, targetDisplaySize),
          );
        }
      }
    }
    this.priorityBasedDownlinkPolicy.chooseRemoteVideoSources(videoPreferences.build());
  };
```

do we have general guidelines about how to calculate the required bandwidth?

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Join session and observer bandwidth usage.

### Amazon Chime SDK for JavaScript version

2.23.0

### What browsers are you seeing the problem on?

Mostly all

### Browser version

Mostly All 

### Browser console logs

[console-export-2021-12-27_14-31-26.txt](https://github.com/aws/amazon-chime-sdk-js/files/7779997/console-export-2021-12-27_14-31-26.txt)

**Comment by ltrung** [comment]
@JunedBrilworks Currently the priority-based downlink policy does not work in Firefox because Firefox does not support downlink bandwidth estimation metrics. For now, could you use this API [supportDownlinkBandwidthEstimation](https://aws.github.io/amazon-chime-sdk-js/classes/defaultbrowserbehavior.html#supportdownlinkbandwidthestimation) to check whether the browser support the policy?

**Comment by JunedBrilworks** [comment]
@itrung Noted will put browser compatibility and apply downlink policy accordingly. But for chrome and safari, we experience even though having bandwidth video tiles are still remain paused.

**Comment by JunedBrilworks** [comment]
Here is the log for another meeting user having an issue. The user was on around 80 Mbps connection with no other bandwidth-consuming content open in the browser. Even though there was only 5 attendee in the 
meeting video tile was remaining off.

[logfile.log](https://github.com/aws/amazon-chime-sdk-js/files/7784375/logfile.log)

**Comment by ltrung** [comment]
From the log it seems it is indeed paused due to bandwidth: 
```
Downlink bandwidth pressure is high: estimated bandwidth 1021.212Kbps, required bandwidth 1991.753Kbps
105.00ac4c90.chunk.js:2 2021-12-28T10:55:02.322Z [INFO] SDK - bwe: pausing streamId 1 attendee 6b402e52-1cc8-1b56-1139-ce400c199f02 due to bandwidth
105.00ac4c90.chunk.js:2 2021-12-28T10:55:02.326Z [INFO] SDK - bwe: pausing streamId 11 attendee fbb4f098-1573-557d-d921-0581a34c65fd due to bandwidth
```

The network estimate comes from the browser webRTC metrics (you can view it during the call if you open chrome chrome://webrtc-internals/). You can also get that metrics from `MetricsDidReceive` and log it as seen in our [demo](https://github.com/aws/amazon-chime-sdk-js/blob/main/demos/browser/app/meetingV2/meetingV2.ts#L1412).
In this case, the browser only estimated the bandwidth to be 1Mbps.

**Comment by JunedBrilworks** [comment]
ok have put this log and compare it with actual bandwidth requirement

**Comment by ltrung** [comment]
Closing the issue for now. Feel free to reopen if needed.

**Comment by JunedBrilworks** [comment]
@ltrung Once again one of our users faced the same issue. In the browser when they are doing a speed test it's showing around 40 Mbps, but on the browser log, it's showing very bandwidth estimation.
[log.txt](https://github.com/aws/amazon-chime-sdk-js/files/7889256/bandwidth.txt)

**Comment by hensmi-amazon** [comment]
Hi @JunedBrilworks , unfortunately the browser bandwidth estimation can be a bit finicky, and though we have modified our logic to wait until it sees packet loss, among other things to try to make it less sensitive, it is still dependent on the actual bitrate being received, which is why the active speaker logic to change resolution may be causing it to occasionally nose-dive if it happens to see a bit of packet loss at the same time.

We have attempted to lessen this impact by providing configuration of the delays (see https://github.com/aws/amazon-chime-sdk-js/blob/main/guides/11_Priority_Based_Downlink_Policy.md under *Configure network event delays*).  In this case I would recommend `VideoPriorityBasedPolicyConfig.StableNetworkPreset` which tries to delay downward movement, and speed recovery. *However*, we have found that this configuration should have more impact, so I would wait on https://github.com/aws/amazon-chime-sdk-js/pull/1921 until experimenting with that config. We can leave this issue open until then :).
