### ISSUE TITLE
Audio device issue Android tablet

### ISSUE THREAD

**Issue by venkatrv75** [aws/amazon-chime-sdk-js#1984]
### What happened and what did you expect to happen?

The issue is observed on certain android tablets only. In other android devices, working fine. When deviceController.chooseAudioInputDevice(microphoneId) is run, following error is thrown in the logs.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

On Samsung tablet Galaxy tab A, run the deviceController.chooseAudioInputDevice(deviceId) and can see this error.

### Amazon Chime SDK for JavaScript version

2.26.0

### What browsers are you seeing the problem on?

Android Chrome

### Browser version

97.0.4692

### Browser console logs

022-02-02T06:34:00.525Z [ERROR] ChimeMeetingLogs - failed to get audio device for constraints {"audio":{"echoCancellation":true,"googEchoCancellation":true,"googEchoCancellation2":true,"googAutoGainControl":true,"googAutoGainControl2":true,"googNoiseSuppression":true,"googNoiseSuppression2":true,"googHighpassFilter":true,"deviceId":{"exact":"default"},"sampleRate":{"ideal":48000},"sampleSize":{"ideal":16},"channelCount":{"ideal":1}}}: NotAllowedError: Permission denied

**Comment by jing-chen1** [comment]
Hi @venkatrv75,

Thanks for your interest in Chime SDK for JavaScript. Seems like it is a device issue since it works in other Android devices. We have other client SDK that can be used by applications based on different OS. Could you check [Amazon Chime SDK for Android](https://github.com/aws/amazon-chime-sdk-android) repo?

**Comment by jing-chen1** [comment]
I can see there is a permission error: `NotAllowedError: Permission denied` which indicates that the attendee did not provide the audio permission to the browser, so you have audio device issue. Could you please provide the audio permission once prompted when joining the meeting? Please let me know if it works.

Also want to check which version of Samsung tab you are using since we only support version 12 and later. For more details: [Amazon Chime Developer Guide](https://docs.aws.amazon.com/chime/latest/dg/meetings-sdk.html#mtg-browsers)

If you still have any issue, please provide logs so we can try our best to help you.

**Comment by ltrung** [comment]
Can you also try out the webRTC sample https://webrtc.github.io/samples/src/content/devices/input-output/ to see if you can get audio stream in that device?

**Comment by venkatrv75** [comment]
Turns out to be permissions issue on the device. webRTC samples worked fine.
