### ISSUE TITLE
Screenshare is not supported on Firefox ver 74.0 (64bit) for Ubuntu.

### ISSUE THREAD

**Issue by QueWu** [aws/amazon-chime-sdk-js#206]
**INFO log**
[INFO] Express::MeetingSaga::startScreenShare: Screen share is not supported for browser or version | web.aa1a246dfe507dcb85f3.js:1:1163475

**Discribe the bug**
Hi, the documentation (amazon-chime-user-guide/doc_source/screen-share.md) states that the web application supports screen share on Firefox for Linux OS without the need of plugins. However it seems that it is not supported for Firefox ver 74.0 (64bit) for Ubuntu, screen share is unable to start.

If there are no plans to support it, should the documentation change?

**Screenshots**
![Screenshot_2020-04-02 Amazon Chime(1)](https://user-images.githubusercontent.com/11834599/78253218-57acb500-74f4-11ea-99a5-a21c8fa2c4c5.png)

**Platform**
 - OS: Ubuntu 16.04.6 LTS 64-bit
 - Browser: Firefox
 - Browser Version: 74.0 (64bit) for Ubuntu.
 - Amazon Chime SDK GitHub Commit: N/A

**Comment by aburnson** [comment]
This issue pertains to the Amazon Chime web client application. This GitHub repository is for the Amazon Chime JS SDK. I have forwarded the issue along to the Amazon Chime web client team. In order to track this issue, please also have your Chime administrator open a ticket: https://docs.aws.amazon.com/chime/latest/ug/chime-getting-support.html
