### ISSUE TITLE
NotReadableError : Error fetching device

### ISSUE THREAD

**Issue by heyolajyd** [aws/amazon-chime-sdk-js#2170]
**What we observed:**
We have observed this noise in our datadog logs for some of our users: `NotReadableError: Error fetching device.`.  Unfortunately, I am unable to reproduce this on my machine and hence I'd like to understand what could have led to this error so we can address and provide a seamless experience for our users. 

Please see attached:

![Screenshot 2022-04-15 at 15 49 29](https://user-images.githubusercontent.com/8596553/163585646-02726ab1-47f4-4aee-800f-580aad39be6f.png)

Q1. Could this be because a user requests both the camera and microphone permissions even when there is no camera? 

**Platform**

OS: Windows
Browser: Chrome

**Comment by devalevenkatesh** [comment]
The `NotReadableError` is thrown when `navigator.getUserMedia` fails to acquire a device for which permission is asked.

From [MDN](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia#:~:text=Thrown%20if%2C%20although%20the%20user%20granted%20permission%20to%20use%20the%20matching%20devices%2C%20a%20hardware%20error%20occurred%20at%20the%20operating%20system%2C%20browser%2C%20or%20Web%20page%20level%20which%20prevented%20access%20to%20the%20device.):
Thrown if, although the user granted permission to use the matching devices, a hardware error occurred at the operating system, browser, or Web page level which prevented access to the device.

Q1. Could this be because a user requests both the camera and microphone permissions even when there is no camera?
- The Amazon Chime SDK for JavaScript just captures and re-throws the error from `navigator.getUserMedia` internally so we suggest checking this exceptions reference for more details. But as linked, even if permissions are available, this can happen due to some hardware, browser or OS issue.

**Comment by heyolajyd** [comment]
Thank you @devalevenkatesh. On a closer look, it appears that these users are trying to connect to the meeting via a desktop device that potentially doesn't have a camera attached.

Is it possible that the user should be able to join a meeting with a microphone only perhaps have the user request the permissions for only audio if no camera exists so that the user can still join the session?

**Comment by devalevenkatesh** [comment]
Yes, you should be able to join with requesting permission for audio, you can override the `setDeviceLabelTrigger` in the JS SDK requesting for audio permissions only. I tested this locally in our meeting demo and could not run into any error.

We have a [FAQ](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html#how-can-i-show-a-custom-ux-when-the-browser-prompts-the-user-for-permission-to-use-microphone-and-camera) code, you have to just remove the `video: true` while calling the `getUserMedia`. You can also check our [meeting demo](https://github.com/aws/amazon-chime-sdk-js/blob/ffecd31d55102fc43deb4732e2075139016002d6/demos/browser/app/meetingV2/meetingV2.ts#L2406-L2434) and try testing there for a repro.

I tested all this on a macOS using JS SDK v3 now, which JS SDK version you are using?

We would appreciate if you follow the bug template while filing issue.

**Comment by heyolajyd** [comment]
Thanks, @devalevenkatesh this issue was more of getting clarification than filing a bug. To answer your question, we're using `"amazon-chime-sdk-js": "2.30.0"`. But, thanks for taking the time to clarify and give examples. I will close this now.

**Comment by heyolajyd** [comment]
Hi @devalevenkatesh, I bumped our JS SDK to v3 and we're seeing this error
![image](https://user-images.githubusercontent.com/8596553/172675637-cfaca985-f227-46b1-bb6b-15754a7ef76c.png)

Is this still because `navigator.getUserMedia` fails to acquire a device for which permission is asked?

**Comment by xuesichao** [comment]
Hi @heyolajyd , according to MDN: https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia

#### NotReadableError
>Thrown if, although the user granted permission to use the matching devices, a hardware error occurred at the operating system, browser, or Web page level which prevented access to the device.

It seems the permission has been granted but there might be some errors on browser or device side.

**Comment by devalevenkatesh** [comment]
@heyolajyd request you to please go through the migration docs for v3 and see whether the necessary start/stop APIs are used for the audio part.
https://github.com/aws/amazon-chime-sdk-js/blob/main/guides/17_Migration_to_3_0.md#device-controller

But as Sichao mentioned this error may be due to the hardware error. From the logs or with users, you can check whether there is any other application using the Microphone or how, that can also result into this issue.

**Comment by heyolajyd** [comment]
ok will do thanks @devalevenkatesh and @xuesichao
