### ISSUE TITLE
Version 3.5.0

### ISSUE THREAD

**Issue by Nanosync** [aws/amazon-chime-sdk-js#2303]
Hi, I noticed that the repo version has been bumped to 3.5.0 but it is not available on npm. Could this version be published, or will it be published based on a schedule?

**Comment by devalevenkatesh** [comment]
We version bump for the next release while doing a current release, so that all next PRs go under the next version. Currently, 3.5.0 is not released and probably we will plan for a release next week. Generally we schedule bi-weekly releases but schedule can change based on features, fixes or not enough changes.

Closing this issue for now but please feel free to re-open if you are waiting on a change. Appreciate your interest and patience.
