### ISSUE TITLE
VideoTileGrid layout

### ISSUE THREAD

**Issue by jaeho0522** [aws/amazon-chime-sdk-js#2401]
### What are you trying to do?

I am using VideoTileGrid and I am trying to display whiteboard  in VideoTileGrid in two different ways.
1) When screen is shared, I want display whiteboard on top of shared screen video tile.
2) When screen is not shared, I want display whiteboard the same way as the shared screen.

### How can the documentation be improved to help your use case?

How can I achieve above two things?
Do I need to add custom layout to VideoTileGrid?
Is there anyway to customize VideoTileGrid's layout?

### What documentation have you looked at so far?

I searched Google and could not find anything about adding custom layout to VideoTileGrid.
Or anything about VideoTileGrid and whiteboard.

Thanks in advance.

**Comment by xuesichao** [comment]
Hi @jaeho0522 , are you using the `amazon-chime-sdk-component-library-react`? If so, could you close this issue and open another one under https://github.com/aws/amazon-chime-sdk-component-library-react?

For your use case, you should implement your own `VideoTileGrid` component. Simply duplicate what we have here https://github.com/aws/amazon-chime-sdk-component-library-react/blob/main/src/components/sdk/VideoTileGrid/index.tsx , let's call the duplicated one `MyVideoTileGrid`.

Basically you need to:
1. Use the `sharingAttendeeId` and `isLocalShareLoading` to check whether the screen is shared or not, and whether is sharer is local attendee or not. And use some flags to maintain these states.
2. We don't have a whiteboard component, I guess you implemented your own. You should add it in you` MyVideoTileGrid`. 
3. Based on the states from step 1, you can update the CSS of your `whiteboard` and `ContentShare` component so that they can match your desired position.

**Comment by jaeho0522** [comment]
Hi,

Thanks for your help.
I will try and will let you know if I need any more help.

Thanks and regards,


Jaeho Lee
CEO/Programmer

#202, Wonseong Bldg., 29, Seochojungang-ro 20-gil, Seocho-gu, Seoul, Republic of Korea
​Tel +82 2 6205 7370 Mobile +82 10 3720 6763​
Email ***@***.***



-----Original Message-----

**Comment by jaeho0522** [comment]
I moving this issue to amazon-chime-sdk-component-library-react.
https://github.com/aws/amazon-chime-sdk-component-library-react/issues/827
