### ISSUE TITLE
Promoted to primary meeting attendees dropping from meeting after ~40 minutes

### ISSUE THREAD

**Issue by JurijRevega** [aws/amazon-chime-sdk-js#2441]
### What happened and what did you expect to happen?

When a user is promoted to primary meeting (with camera and mic enabled), approx after 40-50 minutes after joining other attendees in the meeting stops receiving audio from that promoted user (video is still receiving).
Additionally, other users not receiving data about this user in a callback from `realtimeSubscribeToAttendeeIdPresence`

Is there a bug or any way to prevent this from happening?
This happens in [example code ](https://github.com/aws/amazon-chime-sdk-js/tree/main/demos/browser) without any modifications

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

1. Setup https://github.com/aws/amazon-chime-sdk-js/tree/main/demos/browser 
2. Create regular meeting and join as user1, enable camera, audio
3. Create replica meeting (based on meeting created at 2) and join as user2
4. Join replica as after 10minutes user3
5. Promote user2, user3 to primary `promoteToPrimaryMeeting`
6. Enable camera, audio for promoted users
7. Keep meeting alive at least for 50minutes

After 50 minutes user1 stops receiving audio from user2.
10 minutes later user1 stops receiving audio from user3.
New users in primary meeting not receiving audio from user2, user3. and no data about this users in callback `audioVideo.realtimeSubscribeToAttendeeIdPresence(this.attendeeIdPresenceHandler)`

### Amazon Chime SDK for JavaScript version

3.8.0

### What browsers are you seeing the problem on?

Google Chrome

### Browser version

Version 105.0.5195.102 (Official Build) (x86_64)

### Meeting and Attendee ID Information.

N/A

### Browser console logs

No errors in logs when this happens

**Comment by devalevenkatesh** [comment]
Thanks @JurijRevega for filling this issue. There are couple of auto meeting end policies with Chime SDK meetings:

The meetings end when you run the [DeleteMeeting](https://docs.aws.amazon.com/chime-sdk/latest/APIReference/API_DeleteMeeting.html) API action. Also, meetings end automatically when:
- The meeting time exceeds 24 hours.
- The meeting is a [replica meeting](https://docs.aws.amazon.com/chime-sdk/latest/dg/media-replication.html) and the primary meeting is ending.
- In a non-replica meeting, no attendess connect for five continuous minutes.

[Reference](https://docs.aws.amazon.com/chime-sdk/latest/dg/create-mtgs.html).

Could you please provide `MeetingId` and `AttendeeId` for the affected meeting to check if that happened?

**Comment by JurijRevega** [comment]
Hi, @devalevenkatesh thanks for responding

There are data:
primary meeting: `  "MeetingId": "1e0f1473-cb0d-4fb9-947e-241d69a02713"`
replica meeting:  `MeetingId": "ddb0178c-14dd-48fb-b379-3ffff4e82713"`

user-1  (joined directly to primary meeting)    `"AttendeeId": "c08a7c59-667a-4932-b39e-0383f1e84bf8" `
user-2 (promoted from replica)   `"AttendeeId": "c14eab5f-ba5f-bb0e-1df5-03277717ac05"`
user-3 (promoted from replica)   `"AttendeeId": "846d1d70-dcfc-883c-2495-8f27d1d1695b"`

The same issue happened, user-2, user3 were dropped from primary meeting.

I think this issue is attendee related, because, after user-2,user-3 was dropped, new user (user-4) was able to join the same replica, and successfully promoted
user-4 `"MeetingId": "ddb0178c-14dd-48fb-b379-3ffff4e82713"`

**Comment by devalevenkatesh** [comment]
Thank you for providing the Meeting and Attendee IDs.

**Replica Meeting Server events**
|  Time                  | Attendee                             | Event description                                                                                                                                                                              |
|------------------------|--------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 9/19/2022  7:46:46 AM  |                                      | Meeting Created.                                                                                                                                                                               |
| 9/19/2022  7:47:25 AM  | c14eab5f-ba5f-bb0e-1df5-03277717ac05 | Attendee joined into the replica meeting.                                                                                                                                                      |
| 9/19/2022  7:49:06 AM  | 846d1d70-dcfc-883c-2495-8f27d1d1695b | Attendee joined into the replica meeting.                                                                                                                                                      |
| 9/19/2022  8:30:33 AM  | c14eab5f-ba5f-bb0e-1df5-03277717ac05 | Attendee dropped from the replica meeting. At the same time, attendee leave event is seen from primary meeting for the promoted corresponding attendee (a0ee130d-a8a7-b885-5d3b-3a0520766bc3). |
| 9/19/2022  8:30:34 AM  | c14eab5f-ba5f-bb0e-1df5-03277717ac05 | Attendee joined again into the replica meeting.                                                                                                                                                |
| 9/19/2022  8:33:01 AM  | 846d1d70-dcfc-883c-2495-8f27d1d1695b | Attendee dropped from the replica meeting. At the same time, attendee leave event is seen from primary meeting for the promoted corresponding attendee (7172adf5-7597-b4e3-b655-73f1bdbb6557). |
| 9/19/2022  8:33:01 AM  | 846d1d70-dcfc-883c-2495-8f27d1d1695b | Attendee joined again into the replica meeting.                                                                                                                                                |
| 9/19/2022  10:05:40 AM | c14eab5f-ba5f-bb0e-1df5-03277717ac05 | Attendee left replica meeting.                                                                                                                                                                 |
| 9/19/2022  10:05:41 AM | 846d1d70-dcfc-883c-2495-8f27d1d1695b | Attendee left replica meeting.                                                                                                                                                                 |
| 9/19/2022  10:11:38 AM |                                      | Meeting ended.                                                                                                                                                                                 |


**Primary meeting server events**
|  Time                  | Attendee                             | Event description                                                                                   |
|------------------------|--------------------------------------|-----------------------------------------------------------------------------------------------------|
| 9/19/2022  7:42:58 AM  |                                      | Meeting Created.                                                                                    |
| 9/19/2022  8:30:33 AM  | c08a7c59-667a-4932-b39e-0383f1e84bf8 | First attendee joined in primary meeting.                                                           |
| 9/19/2022  7:47:30 AM  | a0ee130d-a8a7-b885-5d3b-3a0520766bc3 | Replica attendee (c14eab5f-ba5f-bb0e-1df5-03277717ac05) promoted and joined into primary meeting.   |
| 9/19/2022  7:49:57 AM  | 7172adf5-7597-b4e3-b655-73f1bdbb6557 | Replica attendee (846d1d70-dcfc-883c-2495-8f27d1d1695b) promoted and joined into primary meeting.   |
| 9/19/2022  8:30:33 AM  | a0ee130d-a8a7-b885-5d3b-3a0520766bc3 | Attendee leaves the meeting. This is where the drop event is seen in replica meeting server events. |
| 9/19/2022  8:33:01 AM  | 7172adf5-7597-b4e3-b655-73f1bdbb6557 | Attendee leaves the meeting. This is where the drop event is seen in replica meeting server events. |
| 9/19/2022  10:05:40 AM | c08a7c59-667a-4932-b39e-0383f1e84bf8 | Attendee leaves the meeting.                                                                        |
| 9/19/2022  10:11:38 AM |                                      | Meeting auto-ended.                                                                                 |

Few questions:
1. The meeting leave from the primary meeting is triggered by your application? Checking whether the leave in primary results into drop in replica.
2. I do not see any [client events](https://aws.github.io/amazon-chime-sdk-js/modules/clientevent_ingestion.html) for both of the meetings. Could you please enable them so that we can get the dropped events if any from client side? We include the JS SDK failure error with them, hence, might get insight into the client errors.
3. Could you please provide browser console logs when this happens?

I will try to check more internally to understand the behavior here.

**Comment by JurijRevega** [comment]
Hi, regarding your questions
1. To reproduce the issue I used https://github.com/aws/amazon-chime-sdk-js/tree/main/demos/browser. During the meeting, I didn't call any leave methods.
2. Events enabled
3. Browser logs attached


Here is new example data, with same problem after ~40min. :
Main meeting `"MeetingId": "db42e85e-5984-488d-b500-9952d32f2713"`
Replica meeting `"MeetingId": "97505f6c-b8de-44d6-af89-3d104b5e2713"`

User-1 
`"AttendeeId": "9a3a119f-6e69-d6b6-9bfb-6461a39ff332",
`
User2
 `"AttendeeId": "5e700f5f-b81d-1969-bbcc-cbf05e9cb196"`
  Promoted "AttendeeId": `"da4c7b1e-6d41-f095-ae7f-573f9abbca3b"`

User3
`"AttendeeId": "1dcd8243-394f-9a4f-e4b3-5a51e7800c21"`
 Promoted `"AttendeeId": "dcd8243-394f-9a4f-e4b3-5a51e7800c21"`


Browser logs

[127.0.0.1-1663688023376_user3.log](https://github.com/aws/amazon-chime-sdk-js/files/9609360/127.0.0.1-1663688023376_user3.log)
[127.0.0.1-1663688013710_user2.log](https://github.com/aws/amazon-chime-sdk-js/files/9609362/127.0.0.1-1663688013710_user2.log)
[127.0.0.1-1663688004246_user1.log](https://github.com/aws/amazon-chime-sdk-js/files/9609365/127.0.0.1-1663688004246_user1.log)

**Comment by kaspervm** [comment]
@devalevenkatesh any updates on this? Our team is stuck om this so we cannot push our product.

**Comment by pracheth** [comment]
Hi @kaspervm I'm also from the SDK team and working with Venkatesh on this. I'm able to reproduce this with my setup but I'm not sure about the root cause yet as to why this is happening. Will keep you posted. Apologies for the delay!

**Comment by pracheth** [comment]
Hi @kaspervm Apologies for the delay in getting to the root cause. We have identified a bug in our backend. It is currently being reviewed and the fix should be deployed through our pipelines by end of week!

**Comment by kaspervm** [comment]
@pracheth great news! Thank you very much for your help!
