### ISSUE TITLE
TypeError when running meeting demo on Ubuntu

### ISSUE THREAD

**Issue by ijt** [aws/amazon-chime-sdk-js#246]
I tried running the meeting demo on an Ubuntu VM, got this result:

```
root@chime:~/amazon-chime-sdk-js/demos/browser# npm run start --app=meeting
...
Entrypoint main [big] = meeting-bundle.js
[0] multi ./app/meeting/meeting.ts 28 bytes {main} [built]
[../../src/activespeakerdetector/DefaultActiveSpeakerDetector.ts] /root/amazon-chime-sdk-js/src/activespeakerdetector/DefaultActiveSpeakerDetector.ts 5.84 KiB {main} [built]
[../../src/activespeakerpolicy/DefaultActiveSpeakerPolicy.ts] /root/amazon-chime-sdk-js/src/activespeakerpolicy/DefaultActiveSpeakerPolicy.ts 1.92 KiB {main} [built]
[../../src/audiomixcontroller/DefaultAudioMixController.ts] /root/amazon-chime-sdk-js/src/audiomixcontroller/DefaultAudioMixController.ts 2.08 KiB {main} [built]
[../../src/audiovideocontroller/AudioVideoControllerState.ts] /root/amazon-chime-sdk-js/src/audiovideocontroller/AudioVideoControllerState.ts 2.01 KiB {main} [built]
[../../src/audiovideocontroller/DefaultAudioVideoController.ts] /root/amazon-chime-sdk-js/src/audiovideocontroller/DefaultAudioVideoController.ts 43.1 KiB {main} [built]
[../../src/audiovideocontroller/NoOpAudioVideoController.ts] /root/amazon-chime-sdk-js/src/audiovideocontroller/NoOpAudioVideoController.ts 2.98 KiB {main} [built]
[../../src/audiovideofacade/DefaultAudioVideoFacade.ts] /root/amazon-chime-sdk-js/src/audiovideofacade/DefaultAudioVideoFacade.ts 18.9 KiB {main} [built]
[../../src/backoff/FullJitterBackoff.ts] /root/amazon-chime-sdk-js/src/backoff/FullJitterBackoff.ts 1.43 KiB {main} [built]
[../../src/backoff/FullJitterBackoffFactory.ts] /root/amazon-chime-sdk-js/src/backoff/FullJitterBackoffFactory.ts 1.04 KiB {main} [built]
[../../src/backoff/FullJitterLimitedBackoff.ts] /root/amazon-chime-sdk-js/src/backoff/FullJitterLimitedBackoff.ts 1.57 KiB {main} [built]
[../../src/index.ts] /root/amazon-chime-sdk-js/src/index.ts 27.8 KiB {main} [built]
[./app/meeting/meeting.ts] 79.4 KiB {main} [built]
[./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {main} [built]
[./style.scss] 667 bytes {main} [built]
    + 202 hidden modules
Child html-webpack-plugin for "meeting.html":
     1 asset
    Entrypoint undefined = meeting.html
    [./node_modules/html-webpack-plugin/lib/loader.js!./app/meeting/meeting.html] 20.9 KiB {0} [built]
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {0} [built]
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]
        + 9 hidden modules
events.js:239
    throw new TypeError('"listener" argument must be a function');
    ^

TypeError: "listener" argument must be a function
    at _addListener (events.js:239:11)
    at Server.addListener (events.js:297:10)
    at new Server (_http_server.js:269:10)
    at Object.createServer (http.js:34:10)
    at Object.<anonymous> (/root/amazon-chime-sdk-js/demos/browser/server.js:37:34)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

```

**Platform**
 - OS: #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019
 - Amazon Chime SDK GitHub Commit: 57c600ec2a7e726a24953ab26a90ce0e93834c5b

**Comment by ijt** [comment]
It works just fine on my Mac.

**Comment by simmkyu** [comment]
Which version of Node.js and NPM you are using in Ubuntu VM? Chime SDK and demo apps require ([Prerequisites](https://github.com/aws/amazon-chime-sdk-js#prerequisites)):
- Node 10 or higher
- npm 6.11 or higher

According to [Amazon Chime Developer Guide](https://docs.aws.amazon.com/chime/latest/dg/meetings-sdk.html#mtg-browsers), Chime SDK for JS only supports browsers on macOS and Windows. We will update this guide and change logs once we officially support other OSs.

**Comment by ijt** [comment]
I was using Node 8, the default version included in Ubuntu 18. Just have to update it. Thanks.

**Comment by aalvarezcoco** [comment]
RROR in ./style.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/src??ref--5-2!./node_modules/sass-loader/dist/cjs.js!./style.scss)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Error: Missing binding /home/congas1983/Descargas/amazon-chime/demos/browser/node_modules/node-sass/vendor/linux-x64-72/binding.node
Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 12.x

Found bindings for the following environments:
  - Linux 64-bit with Node.js 10.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to download the binding for your current environment.
    at module.exports (/home/congas1983/Descargas/amazon-chime/demos/browser/node_modules/node-sass/lib/binding.js:15:13)
    at Object.<anonymous> (/home/congas1983/Descargas/amazon-chime/demos/browser/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (/home/congas1983/Descargas/amazon-chime/demos/browser/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (/home/congas1983/Descargas/amazon-chime/demos/browser/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at getDefaultSassImplementation (/home/congas1983/Descargas/amazon-chime/demos/browser/node_modules/sass-loader/dist/getDefaultSassImplementation.js:24:10)
    at getSassImplementation (/home/congas1983/Descargas/amazon-chime/demos/browser/node_modules/sass-loader/dist/getSassImplementation.js:19:72)
    at Object.loader (/home/congas1983/Descargas/amazon-chime/demos/browser/node_modules/sass-loader/dist/index.js:40:61)
 @ ./style.scss 2:26-181
 @ ./app/meeting/meeting.ts
 @ multi ./app/meeting/meeting.ts
Child html-webpack-plugin for "meeting.html":
     1 asset
    Entrypoint undefined = meeting.html
    [./node_modules/html-webpack-plugin/lib/loader.js!./app/meeting/meeting.html] 20.9 KiB {0} [built]
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {0} [built]
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]
        + 9 hidden modules
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! amazon-chime-sdk-js-demos@0.1.0 build:fast: `tsc && webpack --config ./webpack.config.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the amazon-chime-sdk-js-demos@0.1.0 build:fast script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/congas1983/.npm/_logs/2020-04-22T20_48_51_517Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! amazon-chime-sdk-js-demos@0.1.0 start:fast: `npm run build:fast && node server.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the amazon-chime-sdk-js-demos@0.1.0 start:fast script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/congas1983/.npm/_logs/2020-04-22T20_48_51_793Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! amazon-chime-sdk-js-demos@0.1.0 start: `npm run deps && npm install && npm install aws-sdk && npm run start:fast`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the amazon-chime-sdk-js-demos@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/congas1983/.npm/_logs/2020-04-22T20_48_51_864Z-debug.log
congas1983@node:~/Descargas/amazon-chime/demos/browser$ npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules/watchpack/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 7838 packages in 4.596s

31 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

congas1983@node:~/Descargas/amazon-chime/demos/browser$ sudo npm install

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules/watchpack/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 7838 packages in 6.197s

31 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
