### ISSUE TITLE
Uncaught (in promise) DOMException: Failed to load because no supported source was found

### ISSUE THREAD

**Issue by paggiorowarda** [aws/amazon-chime-sdk-js#253]
**Describe the bug**
I was trying the meetingV2 demo in the browser folder. When I try to transfer a file I get the error as in the screen. I have tried with TXT, JPG and files without extension. Always the usual mistake

**Screenshots**
![chime_error](https://user-images.githubusercontent.com/63292100/78660873-22c2a880-78ce-11ea-82a7-7bec5190342d.png)

**Platform**
 - OS: Ubuntu 19.10
 - Browser: Google Chrome
 - Browser Version: 80.0.3987.87 (64 bit)
 - Amazon Chime SDK GitHub Commit: 72914466156f97908bc201e3ab11d18a450cc6ff

**Comment by simmkyu** [comment]
This DOMException error is expected because the demo app's `<input type="file">` element takes in any type of file.

```
Uncaught (in promise) DOMException: Failed to load because no supported source was found.
```

However, building a demo app seemed to have an issue. Could you try again after installing Node 10+ and npm 6.11+?

```
Uncaught ReferenceError: a is not defined.
```

According to [Amazon Chime Developer Guide](https://docs.aws.amazon.com/chime/latest/dg/meetings-sdk.html#mtg-browsers), Chime SDK for JS only supports browsers on macOS and Windows. We will update this guide and change logs once we support other OSs.

**Comment by ltrung** [comment]
Just to clarify that the content sharing button is to share your screen or other media contents such as audio/video files and is not for file transferring.

**Comment by paggiorowarda** [comment]
> Solo per chiarire che il pulsante di condivisione del contenuto è quello di condividere lo schermo o altri contenuti multimediali come file audio / video e non è per il trasferimento di file.

I had missed this fundamental detail
