### ISSUE TITLE
Need more information on Meeting error messages.

### ISSUE THREAD

**Issue by sskrishnaswamy** [aws/amazon-chime-sdk-js#2542]
### What are you trying to do?

We are capturing the errors that the end users are facing in the Cloudwatch and display them a user friendly error messages. But we could see certain errors that our users are facing does not have a clear explanation in the Chime SDK error documentation. Can you please provide the explanation for the below errors:

AudioInputFailed:

- TypeError: Argument 1 of AudioContext.constructor '[object Object]' is not a valid value for enumeration AudioChannel.

VideoInputFailed:

- AbortError: Starting videoinput failed

MeetingFailed:

- Cannot read properties of null (reading 'realtimeSubscribeToVolumeIndicator')
- Cannot read properties of undefined (reading 'split')
- null is not an object (evaluating 'this._audioVideo.realtimeSubscribeToVolumeIndicator')
- Data size has to be less than 2048 bytes
- The meeting was reconnected.
- serial group task AudioVideoReconnect/731c33d7-e60d-477b-90d2-44d9eb472713/93249803-8b07-f025-a2f8-1761c4ff8a23 was canceled due to subtask AudioVideoReconnect/731c33d7-e60d-477b-90d2-44d9eb472713/93249803-8b07-f025-a2f8-1761c4ff8a23/Timeout15000ms error: serial group task AudioVideoReconnect/731c33d7-e60d-477b-90d2-44d9eb472713/93249803-8b07-f025-a2f8-1761c4ff8a23/Timeout15000ms/UpdateSession was canceled due to subtask AudioVideoReconnect/731c33d7-e60d-477b-90d2-44d9eb472713/93249803-8b07-f025-a2f8-1761c4ff8a23/Timeout15000ms/UpdateSession/FinishGatheringICECandidatesTask error: canceling AudioVideoReconnect/731c33d7-e60d-477b-90d2-44d9eb472713/93249803-8b07-f025-a2f8-1761c4ff8a23/Timeout15000ms/UpdateSession/FinishGatheringICECandidatesTask due to the meeting status code: 16

MeetingStartFailed:

- The signaling connection was closed with code 1006 and reason:
- The signaling connection was closed with code 4404 and reason: meeting unavailable
- serial group task AudioVideoStart/07a09388-1fa9-4e52-8d5a-4564a0ac2713/ec7f7f8e-ca1c-78c5-9f11-83ea2b791d9e was canceled due to subtask AudioVideoStart/07a09388-1fa9-4e52-8d5a-4564a0ac2713/ec7f7f8e-ca1c-78c5-9f11-83ea2b791d9e/Timeout15000ms error: serial group task AudioVideoStart/07a09388-1fa9-4e52-8d5a-4564a0ac2713/ec7f7f8e-ca1c-78c5-9f11-83ea2b791d9e/Timeout15000ms/Peer was canceled due to subtask AudioVideoStart/07a09388-1fa9-4e52-8d5a-4564a0ac2713/ec7f7f8e-ca1c-78c5-9f11-83ea2b791d9e/Timeout15000ms/Peer/Timeout5000ms error: parallel group task AudioVideoStart/07a09388-1fa9-4e52-8d5a-4564a0ac2713/ec7f7f8e-ca1c-78c5-9f11-83ea2b791d9e/Timeout15000ms/Peer/Timeout5000ms/FinalizeConnection failed for tasks: task AudioVideoStart/07a09388-1fa9-4e52-8d5a-4564a0ac2713/ec7f7f8e-ca1c-78c5-9f11-83ea2b791d9e/Timeout15000ms/Peer/Timeout5000ms/FinalizeConnection/WaitForAttendeePresenceTask failed: canceling AudioVideoStart/07a09388-1fa9-4e52-8d5a-4564a0ac2713/ec7f7f8e-ca1c-78c5-9f11-83ea2b791d9e/Timeout15000ms/Peer/Timeout5000ms/FinalizeConnection/WaitForAttendeePresenceTask due to the meeting status code: 23

### How can the documentation be improved to help your use case?

It will be helpful if we understand the scenarios in which these errors are thrown so that we will be able to form a user friendly error messages for each of these errors.

### What documentation have you looked at so far?

We are referring to the below Chime SDK documentations so far:
https://aws.github.io/amazon-chime-sdk-js/enums/meetingsessionstatuscode.html
https://aws.github.io/amazon-chime-sdk-js/modules/meetingevents.html#meeting-error-messages

**Comment by ltrung** [comment]
### AudioInputFailed
- TypeError: Argument 1 of AudioContext.constructor '[object Object]' is not a valid value for enumeration AudioChannel.
According to the following Mozilla bug ticket, older versions of Firefox appeared to have a bug throwing the above error when creating an [AudioContext](https://developer.mozilla.org/en-US/docs/Web/API/AudioContext) object.
https://bugzilla.mozilla.org/show_bug.cgi?id=1361475
The bug should be fixed in the Chime SDK-supported Firefox versions (75 and later).
### VideoInputFailed:
- AbortError: Starting videoinput failed
According to the [getUserMedia API documentation](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia#exceptions), the AbortError indicates "some problem" occurred which prevented the device from being used.
### MeetingFailed:
- Cannot read properties of null (reading 'realtimeSubscribeToVolumeIndicator')
   Cannot read properties of undefined (reading 'split')
   null is not an object (evaluating this._audioVideo.realtimeSubscribeToVolumeIndicator')
   This seems like application error that should not happen but we will need client logs to tell for sure.
- Data size has to be less than 2048 bytes
  The Chime SDK allows sending data messages up to 2048 bytes. A session will stop when you send a data message exceeding 2048 bytes.
- The meeting was reconnected.
  Chime SDK retries the connection in the following situations. (See [FAQs](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html#when-does-the-amazon-chime-sdk-retry-the-connection-can-i-customize-this-retry-behavior) for more information.)

    - The SDK misses consecutive pong messages from the Chime server.
    - The SDK detects a high rate of audio packet loss.
    - The SDK experiences a significant audio delay.
    - The SDK encounters a retryable error during the session.
    The above message indicates that the Chime SDK fails to retry the connection.
- Canceling AudioVideoReconnect/731c33d7-e60d-477b-90d2-44d9eb472713/93249803-8b07-f025-a2f8-1761c4ff8a23/Timeout15000ms/UpdateSession/FinishGatheringICECandidatesTask due to the meeting status code: 16.
  When establishing WebRTC connection, the Chime SDK for JavaScript collects [ICE](https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Protocols) candidates. The above error often occurs in Chrome when the browser is in a poor state due to a VPN.
https://bugs.chromium.org/p/webrtc/issues/detail?id=9097

### MeetingStartFailed
- The signaling connection was closed with code 1006
   WebSocket code 1006 indicates that the browser has abnormally closed the connection. This error often occurs due to an unstable internet connection or a misconfigured firewall; however, the browser does not provide exact reasons.
-  The signaling connection was closed with code 4404 and reason: meeting unavailable
   WebSocket 4404 should be thrown when the backend resource is not found. i.e., Chime SDK meeting is unavailable.
   The Chime SDK for JavaScript should invoke the audioVideoDidStop observer method with the MeetingEnded status code. Please use the audioVideoDidStop observer method to handle this case.
```
import { MeetingSessionStatusCode } from 'amazon-chime-sdk-js';

const observer = {
  audioVideoDidStop: sessionStatus => {
    const sessionStatusCode = sessionStatus.statusCode();
    if (sessionStatusCode === MeetingSessionStatusCode.MeetingEnded) {
       // Tell your users that the meeting has already ended.
    }
  },
};

meetingSession.audioVideo.addObserver(observer);
```
-  canceling AudioVideoStart/07a09388-1fa9-4e52-8d5a-4564a0ac2713/ec7f7f8e-ca1c-78c5-9f11-83ea2b791d9e/Timeout15000ms/Peer/Timeout5000ms/FinalizeConnection/WaitForAttendeePresenceTask due to the meeting status code: 23

   The SDK has timed out while attempting to join a session. This error often occurs when you have an unreliable internet connection.
   We recommend handling the MeetingSessionStatusCode.NoAttendeePresent status code in the audioVideoDidStop observer method.
```
import { MeetingSessionStatusCode } from 'amazon-chime-sdk-js';

const observer = {
  audioVideoDidStop: sessionStatus => {
    const sessionStatusCode = sessionStatus.statusCode();
    if (sessionStatusCode === MeetingSessionStatusCode.NoAttendeePresent) {
       // Show an error message.
    }
  },
};

meetingSession.audioVideo.addObserver(observer);
```
