### ISSUE TITLE
Simulcast issues with `ServerSideNetworkAdaptation.BandwidthProbing`

### ISSUE THREAD

**Issue by kelvin2200** [aws/amazon-chime-sdk-js#2559]
### What happened and what did you expect to happen?

Yet another attempt to implement simulcast has proven challenging.
I reported #2374 a few months ago, and it was reported as solved some time later, but I just saw #2550 which seems to be the same issue. Will that be released soon?

Apart from that, it seems that combining simulcast with BandwidthProbing leads to multiple issues.
all issues below assume that simulcast is enabled with the following config:
`const config = VideoPriorityBasedPolicyConfig.Default;
config.serverSideNetworkAdaption = ServerSideNetworkAdaption.BandwidthProbing;`

1. Incoming videos are jerky, sometimes freezing, other times laggish, and there seems to be a considerable drop in quality (compared to when BandwidthProbing is not used, for the same simulcast layer)
2.  At random intervals, random remote streams behave as if they were turned off and an on very fast (you just stop receiving the stream for about 1 sec, then it turns back on). In this particular situation `useAttendeeStatus().videoEnabled` becomes false, then true, just as if the user manually turned his cam off/on.
3. If some attendee suffers a temporary internet loss, when he reconnects, other streams (that never went offline) are lost on other attendees' side and they never recover (not the exact behavior as #2374 or #2550, but similar). It seems that one re-connecting to a meeting due to network issues, causes issues for other attendees. The only thing that works in this case, is either disconnecting and re-connecting to the meeting, or refreshing the page.

Providing a reproduction scenario for all these is very hard, as it took our QA team several days to find them. The one thing we know for sure is that they keep repeating, and there seems to be no pattern other than the combination between simulcast and BandwidthProbing (dunno... maybe it has something to do with the `VideoPriorityBasedPolicy` as well). Without BandwithProbing, the issues don't exist, but simulcast isn't really viable without it.

I'm really starting to feel that there's something wrong with this lib at a fundamental level. For 2 years we've been trying to implement simulcast in our app... still without success.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

none

### Amazon Chime SDK for JavaScript version

3.10.0

### What browsers are you seeing the problem on?

All

### Browser version

109

### Browser console logs

[attendee loses unrelated stream.log](https://github.com/aws/amazon-chime-sdk-js/files/10498118/attendee.loses.unrelated.stream.log)

**Comment by hensmi-amazon** [comment]
Thanks for the report @kelvin2200 , https://github.com/aws/amazon-chime-sdk-js/issues/2550 is partially deployed and should be done by end of week. 

I suspect these may be more an artifact of the priority policy rather then the bandwidth probing which simply smooths out the bandwidth estimation and allows it to increase without arbitrary stream upgrades. 1 is interesting given the change should not impact the simulcast senders. I can try to try to reproduce, but if you could save logging by default for your QA it would be an incredible help. 3 sounds like an easier reproduction (I assume these so I should hopefully be able to find the root cause there.

If possible, could you elaborate on whether your QA team is using an methods to manipulate network conditions? Tools like Network Link Conditioner (which I often use myself) are good for smoke testing but often not entirely similar to actual in-the-field network constraints. It also doesn't manage to clean up the impairments successfully (e.g. you may still have impairments after switching it off). Just would like to gather more information to try to reproduce these myself.

**Comment by SohanChoudhury** [comment]
Any update here?

**Comment by razvanduican12** [comment]
Hello,

@hensmi-amazon any updates?

Thanks!

**Comment by hensmi-amazon** [comment]
3. Should have a fix in https://github.com/aws/amazon-chime-sdk-js/issues/2560 . 1 and 2 are a lot more subtle issues (and are likely old issues not specific to bandwidth probing flag) so may not have an immediate fix soon. A meeting ID + reasonably small timestamp range (+console logs, and the remote videos facing issues) would help immensely for those.

**Comment by hensmi-amazon** [comment]
Going to resolve this due to age and feature release.
