### ISSUE TITLE
Document Chime SDK Meetings - replica meetings per primary meeting actual quota limit

### ISSUE THREAD

**Issue by paquinmathieu** [aws/amazon-chime-sdk-js#2582]
### What are you trying to do?

replica meetings 

### How can the documentation be improved to help your use case?

document the actual "Chime SDK Meetings - replica meetings per primary meeting" limit. in the [about-aws blog](https://aws.amazon.com/about-aws/whats-new/2022/03/amazon-chime-10000-live-participants/) it is specified 40
`Each WebRTC media session supports 250 connections, and can be replicated up to 40 times for an additional 10,000 participants.`
In reality it is more than that, when we requested our quota to be increased to 100, it was increased to 100. Is 100 the current limit or is it higher than that? The limit should be included [here](https://docs.aws.amazon.com/chime-sdk/latest/dg/media-replication.html) with requirements (if any) to be eligible for a specific quota.

### What documentation have you looked at so far?

*For example: 
- README.md, 
- Amazon Chime SDK Developer Guide
- https://github.com/aws/amazon-chime-sdk-js/blob/main/guides/18_Replicated_Meetings.md
- https://docs.aws.amazon.com/chime-sdk/latest/dg/media-replication.html
- https://aws.amazon.com/about-aws/whats-new/2022/03/amazon-chime-10000-live-participants/

Thank you

**Comment by hensmi-amazon** [comment]
Hi @paquinmathieu . I'm not sure what account ID corresponds to your usage, but we do not have any accounts allowlisted for more then 40 replica meetings. There may have been some miscommunication somewhere, sorry, please feel free to reach out to your support contact for more information (especially if the console inaccurately has marked your limit at 100).

We still only support up to 40 replica meetings, so going to close this issue since documentation does not need to be updated.

**Comment by paquinmathieu** [comment]
@hensmi-amazon Thank you for help. The quotas of 100 that was given to us around sept-oct2022 has been resetted to the default value of 4, I don't know when. (Or me and my colleague looked at the wrong item). 40 it is. Thank you for your time.
