### ISSUE TITLE
Documentation on Local tile and Remote Tile in Video sharing

### ISSUE THREAD

**Issue by kazinayem2011** [aws/amazon-chime-sdk-js#2602]
*I have heard several times about local tile and remote tile when sharing video meetings. I am trying to display all attendee video tile and facing difficulties making an app from scratch using Vue JS as I'm new to using AWS Chime SDK. I have several questions below.*

### React library is available. Javascript demo is also huge lines of code that are less helpful to understand for newcomers I think. Are there any chances for Vue JS and Its Demo?

*Your answer will be much helpful and appreciable for any new developer in near future. Thank you very much.*

**Comment by timanderson** [comment]
I think you will find the guide here helpful:

https://github.com/aws/amazon-chime-sdk-js/blob/main/guides/03_API_Overview.md

**Comment by kazinayem2011** [comment]
> I think you will find the guide here helpful:
> 
> https://github.com/aws/amazon-chime-sdk-js/blob/main/guides/03_API_Overview.md

Found helpful but still didn't understand the questions below:
What is the differences between local tile(getAllVideoTiles) and remote tile(getAllRemoteVideoTiles)?
How can I identify the Host?
React library is available. Javascript demo is also huge lines of code that are less helpful to understand for newcomers I think. Are there any chances for Vue JS and Its Demo?

**Comment by timanderson** [comment]
See section 7d in that document, it explains the difference between these calls.

I am not sure what you mean by identifying the host.

I agree that the demo apps are rather complex, also they like to involve other AWS services. But you can build an app based on the documentation OK.

**Comment by kazinayem2011** [comment]
From 7d, They didn't explain what remote and local attendees were. Here is my confusion.

Identifying host means: Who created the meeting? Can I filter the "meeting creator" tile from all attendees?

Thanks.

**Comment by timanderson** [comment]
There isn't a host unless you create one in the logic you add to the application. You can code it as you want.

**Comment by ltrung** [comment]
Thank @timanderson for helping answering.

- What is the differences between local tile(getAllVideoTiles) and remote tile(getAllRemoteVideoTiles)?
`getAllVideoTiles` get all video tiles including the local one where as `getAllRemoteVideoTiles` just return the remote video tiles. You can use `getLocalVideoTile` to get the local video tile for the current local client.
- How can I show all attendee video tile with their name?
Since we do not know your attendee name you would need to maintain a mapping of the attendee name with an id on your side. You can pass that Id to [createAttendee](https://docs.aws.amazon.com/chime/latest/APIReference/API_CreateAttendee.html) and then you should be able to retrieve that id in [videoTileDidUpdate](https://aws.github.io/amazon-chime-sdk-js/interfaces/audiovideoobserver.html#videotiledidupdate) event and get the id via [boundExternalUserId](https://aws.github.io/amazon-chime-sdk-js/classes/videotilestate.html#boundexternaluserid) property.
- How can I add the attendee's name? Where should I pass it? createAttendee or createMeeting API?
`createAttendee`. See the answer in the previous question
- How can I identify the Host? 
You can tell if it is a local video in `videoTileDidUpdate` from the tileState property [localTile](https://aws.github.io/amazon-chime-sdk-js/classes/videotilestate.html#localtile)
- How can I add in-meeting real-time chat and a list of connected attendees?
You can refer to this section of the [API Overview](https://github.com/aws/amazon-chime-sdk-js/blob/main/guides/03_API_Overview.md#9-send-and-receive-data-messages-optional) for a simple way to send messages in meeting. For a full-fledged chat feature, please refer to our chime SDK messaging guides in the README. 
Feel free to reach out for any additional questions.

**Comment by kazinayem2011** [comment]
> Thank @timanderson for helping answering.
> 
> * What is the differences between local tile(getAllVideoTiles) and remote tile(getAllRemoteVideoTiles)?
>   `getAllVideoTiles` get all video tiles including the local one where as `getAllRemoteVideoTiles` just return the remote video tiles. You can use `getLocalVideoTile` to get the local video tile for the current local client.
> * How can I show all attendee video tile with their name?
>   Since we do not know your attendee name you would need to maintain a mapping of the attendee name with an id on your side. You can pass that Id to [createAttendee](https://docs.aws.amazon.com/chime/latest/APIReference/API_CreateAttendee.html) and then you should be able to retrieve that id in [videoTileDidUpdate](https://aws.github.io/amazon-chime-sdk-js/interfaces/audiovideoobserver.html#videotiledidupdate) event and get the id via [boundExternalUserId](https://aws.github.io/amazon-chime-sdk-js/classes/videotilestate.html#boundexternaluserid) property.
> * How can I add the attendee's name? Where should I pass it? createAttendee or createMeeting API?
>   `createAttendee`. See the answer in the previous question
> * How can I identify the Host?
>   You can tell if it is a local video in `videoTileDidUpdate` from the tileState property [localTile](https://aws.github.io/amazon-chime-sdk-js/classes/videotilestate.html#localtile)
> * How can I add in-meeting real-time chat and a list of connected attendees?
>   You can refer to this section of the [API Overview](https://github.com/aws/amazon-chime-sdk-js/blob/main/guides/03_API_Overview.md#9-send-and-receive-data-messages-optional) for a simple way to send messages in meeting. For a full-fledged chat feature, please refer to our chime SDK messaging guides in the README.
>   Feel free to reach out for any additional question

Many Thanks.
