### ISSUE TITLE
Safari 16.3 Screen Sharing Blank from External Monitor on MBP

### ISSUE THREAD

**Issue by bryan-allen** [aws/amazon-chime-sdk-js#2639]
### What happened and what did you expect to happen?

After allowing Screen Recording for Safari and permitting "Allow" Sharing, Safari attempts to share my screen. Recipients on meeting do not see my screen, but rather a blank dark grey window.
This happens when I share my extended screens attached to my laptop. My main laptop screen share works as expected.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Share screen from secondary monitor attached to Mac Book Pro. Participants will not see screen share.
Share screen from MPB built-in monitor, participants will see screen share.
Monterey 12.6.3, Safari 16.3

### Amazon Chime SDK for JavaScript version

amazon-chime-sdk-js@3.13.0

### What browsers are you seeing the problem on?

Safari

### Browser version

16.3

### Meeting and Attendee ID Information.

meeting ID: test-screen-share-safari-2
Using demo app vanilla JS demo serverless.

### Browser console logs

[sharer.log](https://github.com/aws/amazon-chime-sdk-js/files/11212366/sharer.log)
[viewer.log](https://github.com/aws/amazon-chime-sdk-js/files/11212367/viewer.log)

**Comment by simmkyu** [comment]
## Chime SDK server logs

The Chime SDK server logs indicate that the sharer was dropped from the meeting at 14:03:29 and 14:05:03, potentially due to a network issue. The attached [sharer.log](https://github.com/aws/amazon-chime-sdk-js/files/11212366/sharer.log) file does not include Chime SDK logs from around that time, so I cannot determine the exact cause.

However, the sharer had no issue sharing their screen at 14:04:34 and 14:07:44 after each dropped connection. The viewer was also able to view the shared screen without any problems, according to the Chime SDK server events.

Time | Attendee | Action
--|--|--
14:02:27 | Sharer | Created with the CreateAttendee, BatchCreateAttendee, or CreateMeetingWithAttendees API in your server application.
14:02:41 | Viewer | Created with the CreateAttendee, BatchCreateAttendee, or CreateMeetingWithAttendees API in your server application.
14:02:52 | Sharer | Called the `meetingSession.audioVideo.start` API.
14:02:53 | Sharer | Successfully joined the meeting.
14:02:59 | Viewer | Called the `meetingSession.audioVideo.start` API.
14:02:59 | Viewer | Successfully joined the meeting.
**14:03:29** | **Sharer** | **Dropped from the meeting.**
14:04:33 | Sharer | Successfully joined the meeting.
**14:04:34** | **Sharer** | **Enabled screen sharing.**
14:04:52 | Sharer | Stopped screen sharing.
**14:05:03** | **Viewer** | **Dropped from the meeting.**
**14:07:44** | **Sharer** | **Enabled screen sharing.**
14:07:50 | Sharer | Stopped screen sharing.

⠀

## Questions

- Can you reproduce the same issue in other browsers, such as Chrome and Firefox, when sharing external monitors?
- What is the resolution of your external monitor? The Chime SDK utilizes the browser's `getUserMedia` or `getDisplayMedia` API for screen sharing. In certain browser versions, sharing at high resolutions may not function properly.

In the meantime, I will check with the team to replicate the issue and provide updates.

**Comment by ltrung** [comment]
Close due to inactivity. Feel free to reopen and provide the information asked above.
