### ISSUE TITLE
Conflicting documentation for meeting auto-end policy

### ISSUE THREAD

**Issue by JDSeiler** [aws/amazon-chime-sdk-js#2645]
### What are you trying to do?
Hello there, I have been looking into using AWS Chime for building a fairly typical WebRTC video streaming feature. In our expected use-case, there would be one video connection and a spectator (a connected client who is watching the video stream, but does not otherwise transmit audio or video). I am trying to figure out if Chime's meeting auto-end policy will work well with this use-case, and I'm finding different information in different documentation. I was hoping to clarify the meeting auto-end behavior before I start writing any code.

The bottom of [Creating Meetings](https://docs.aws.amazon.com/chime-sdk/latest/dg/create-mtgs.html) (from the Developer Guide) list the following conditions:
- The meeting time exceeds 24 hours
- The meeting is a replica meeting and the primary meeting ends
- In a non-replica meeting, no attendees connect for five continuous minutes

However, the `amazon-chime-sdk-js` [FAQ](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html#when-does-an-amazon-chime-sdk-meeting-end) says:
- No _audio connections_ are present in the meeting for more than five minutes
- 24 hours have elapsed since the meeting was created
- (only in the Amazon Chime namespace) Only _one audio connection_ is present in the meeting for more than 30 minutes

Which set of conditions is correct? The set of conditions listed in the developer guide would work perfectly for what I'm trying to do, but the conditions in the FAQ would be problematic since neither side of the connection is expected to transmit audio. If it is the latter set (where audio connections dictate auto-end), should I expect these hypothetical 1-video-1-spectator meetings to auto-end after 5 minutes?

### How can the documentation be improved to help your use case?
It would be nice for both pieces of documentation to agree with each other. Or, if I am misunderstanding the documentation, for additional clarification to be added that explains how the two sets of rules are equivalent

### What documentation have you looked at so far?
1. Developer Guide :: https://docs.aws.amazon.com/chime-sdk/latest/dg/create-mtgs.html
2. `amazon-chime-sdk-js` FAQ :: https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html#when-does-an-amazon-chime-sdk-meeting-end

**Comment by xuesichao** [comment]
Hi @JDSeiler , they are both correct. This could be confusing because we have two meeting namespaces.
* Amazon Chime SDK Meetings
* Amazon Chime

In general, we recommend you to use Amazon Chime SDK Meetings namespace. Check [Migrating to the Amazon Chime SDK Meetings namespace](https://docs.aws.amazon.com/chime-sdk/latest/dg/meeting-namespace-migration.html) for more details.

And for meeting auto-end policy:
* Amazon Chime SDK Meetings namespace
  * For non-replica/primary meetings:
    * 0 attendee in meeting, end in 5 mins
    * 1+ attendees in the meeting, end in 24 hours 
  * For replica meetings:
    * replica meetings end when primary meeting ends
* Amazon Chime namespace
  * Does not support Media replication (no replica meeting)
  * 0 attendee in the meeting, end in 5 mins
  * 1 attendee in the meeting, end in 30 mins
  * 2+ attendees in the meeting, end in 24 hours
