### ISSUE TITLE
How to encourage sdk to prefer lower quality video instead of pausing or ending streams. 

### ISSUE THREAD

**Issue by CodySchaaf** [aws/amazon-chime-sdk-js#2655]
### What are you trying to do?

Currently our app mostly focuses on meetings with 2-4 people (some on mobile), as well as a lot of screen sharing. My main goal right now is for as little interruption to video as possible. If quality needs to be downgraded to ensure consistent video availability (especially screen sharing), that is fine. 

We have primarily been utilizing the code provided here https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/meeting/src/providers/VideoTileGridProvider

With the following configuration:

```ts
const config = VideoPriorityBasedPolicyConfig.Default;
config.serverSideNetworkAdaption = ServerSideNetworkAdaption.BandwidthProbing;

const priorityBasedPolicy = new VideoPriorityBasedPolicy(logger, config)

//....      

meetingSessionConfiguration.enableSimulcastForUnifiedPlanChromiumBasedBrowsers = true;

meetingSessionConfiguration.videoDownlinkBandwidthPolicy = priorityBasedPolicy;

try {
  await meetingManager.join(meetingSessionConfiguration, options);
  setJoiningMeeting(false);
} catch {
  setJoiningMeeting(false);
}
```

With this configuration we are getting a lot of pausing of video and screen sharing as bandwidth becomes constrained. Even on networks that seem relatively stable/strong. There has been no interruption on other video platforms (google meet/zoom) with these same networks/computers. 

We have also tried to switch to the `VideoAdaptiveProbePolicy` but that comes with the issue of when it decides to kill the screen share stream there is no way for our UI to react. 

We have also tried toying with 

```
videoPreferences.add(
          new VideoPreference(attendeeId, 1, TargetDisplaySize.High),
        );
```

And setting it to prefer Low target size, but that seems like it is more of a suggestion and still doesn't set a lower band for the quality of "do not pause". 

### Question

Is there a way to configure these policies further to encourage the sdk to prefer decreasing frame rate/quality to allow videos/screen sharing to stay active. Basically do anything possible to keep these enabled while not degrading audio quality. Our fallback right now is to revert to `AllHighestVideoBandwidthPolicy`, but we would prefer to allow the sdk to do its thing and adjust quality when it determines it needs to. 

Thanks so much for any suggestions.

**Comment by hensmi-amazon** [comment]
Hi Cody, thanks for the report. We have ongoing work to improve network adaption and better utilize the network while avoiding flip-flopping. We should have new changes in around 1-2 months.

**Comment by CodySchaaf** [comment]
Oh that is great to hear. Thanks so much for the reply. For the time being would your suggestion be to just use `AllHighestVideoBandwidthPolicy`?

**Comment by hensmi-amazon** [comment]
Yes I think thats the best play for the time being.

**Comment by hensmi-amazon** [comment]
Hi again @CodySchaaf could you try enabling the feature in https://github.com/aws/amazon-chime-sdk-js/blob/main/guides/11_Priority_Based_Downlink_Policy.md#enabling-server-side-network-adaption-features- ? I have smoke tested it a bit with a similar setup (2 simulcast senders + content) and in addition to other benefits, will downgrade (at least to me) to a state where not all videos are paused.

I am continuing to tune the behavior though, so if it is still not to your liking, can you provide a meeting ID and a qualitative description of expected and desired behavior?

**Comment by CodySchaaf** [comment]
@hensmi-amazon Can't tell you how much I appreciate the follow up. I did see that new option pop up in the release notes and have a featured flagged release coming up later this week with that in it. Will report back asap. Thanks again!

**Comment by CodySchaaf** [comment]
@hensmi-amazon Ok we just released and after som initial testing we are seeing similar issues with bandwidth constrained quite often. Weren't having any issues with the `AllHighestVideoBandwidthPolicy` on the same network. My internet is very poor but is enough to work with the other Policy or other services. meeting id `caa714fc-913f-407f-a523-3ee165e12713` Thanks!

**Comment by hensmi-amazon** [comment]
Thanks for testing! I have found that the target rate of our congestion controller is pretty conservative (good of course to avoid interruptions), but it may be too quick for some applications, however I always have apprehension towards adjusting too much based on the artificial constraints I apply. I also think some issues may also have to due with the sender bitrate volatility in the call, which I can try to reproduce and adjust.

I'm OOTO for next week, but I will pick this up the week after.

**Comment by hensmi-amazon** [comment]
Just a quick update. Had taken a look at that call, in particular one attendee had a highly varying RTT which was probably leading to the pauses (the network adaption calculates a regression on latencies and tries to back off if the slope is high)
![Screen Shot 2023-07-27 at 2 25 58 PM](https://github.com/aws/amazon-chime-sdk-js/assets/36210679/3c494241-86cb-4494-8ccc-cd99b621a648). There was also some decryption issues just for that connection's RTCP feedback that I hadn't seen, if this was feedback used for congestion control it may have lead to the instability. That being said I've made the following collection of changes (probably TMI):
* I could not determine the source of the SRTCP decryption issues, but added additional logging that should help if this occurs again.
* I wired up some logic in the congestion controller that avoids sending additional packets if it thinks the network link is full. I haven't been able to reproduce a need for this, but it could help pushing too much on a constrained network and leading to pauses, in case that was the issue here. I will be able to determine if it kicks in.
* I changed some calculations in the congestion controller of receiver packet loss so that it doesn't propagate sender packet loss(old issue, but fix was only possible with SSNA). I didn't see much in that specific call but it should help with the general issue of too many pauses/bandwidth dips.

I am still investigating whether I need to adjust sensitivity in the downward direction further; I'd like to ensure that we still can avoid audio interruptions on constraint since that's the main intention of network adaptation after all, but I probably will make some more changes soon. That being said these changes will likely we in at least us-east-1 by end of next week, in which case I will ping this thread in case you could test again.

**Comment by CodySchaaf** [comment]
Awesome thanks for the update. Looking forward to testing it out. Let me know if it would help to provide more meeting ids for effected meetings. 

As for “ 0-2 seconds, no UX, just leave video as-is.” it seems like the video cuts out regardless if you react to the pause event. Is that not the case? Or is there a way to ignore it? This would be especially useful for content share where you never want it to pause. Thanks!

**Comment by CodySchaaf** [comment]
Also wondering why it doesn’t seem like the video first attempts to downgrade quality before cutting video all together. Is there any further configuration I can do on my end to prefer lower quality when these issues pop up instead of pausing the video.

**Comment by hensmi-amazon** [comment]
Sorry, I always forget, I believe you need to set `MeetingSessionConfiguration.keepLastFrameWhenPaused` to true so that it doesn't clear the last frame when paused. If this doesn't fix the issue I can look deeper, but I recall last time I tested this by removing demo logic it worked fine.

And at least in the meeting ID provided, it appeared that the the target bitrate (basically the bandwidth) was just quickly dropping past the point of subscribing to the lower (also as mentioned, those decryption issue may have also been really messing things up). So hopefully tuning it to be less aggressive in drops/utilize the jitter buffer/pacing queue will help here.

I'm trying to hold off from adding a 'never pause' mode (though i may relent eventually) as that keeps the 'min required bitrate' at pretty high values (e.g. if the lowest send quality is 150kbps and there are 4 videos that is already 700kbps+ to receive audio without interuption). But if its a necessity to bridge from the current 'all highest' policy (where the min is often like 5Mbps...) I'll make the addition.

**Comment by hensmi-amazon** [comment]
Also sorry for the delay, I ended up adding some more features/adjustments, will update here when the changes are in us-east-1 mid next week.

**Comment by hensmi-amazon** [comment]
The changes have been deployed, would you mind giving it some more smoke testing? Though I'm not certain I will have tuned it to where desired, hopefully it is at least closer and I can take a look at some improved debug logging I added. I also added some variables directly related to sensitivity that I can adjust solely for your account without another deployment.

**Comment by CodySchaaf** [comment]
Hi @hensmi-amazon just tried it out again with meeting 604e199f-fb28-4679-a95b-f6fb5c872713 it definitely seems better. But we were seeing very low video quality and quite a few pauses. Which we were not seeing in a prior meeting with AllHighestQuality

**Comment by hensmi-amazon** [comment]
Thanks, will take a look!

**Comment by hensmi-amazon** [comment]
Sorry for the delay, I've actually looked at this a few times trying to find the issue without needed to reach out for additional information without luck. I'm stuck on the following:
* I can't quite understand why your network appears to be as bad as it seems (lol!) to be during these calls, with the RTT bouncing all over and there being heavy packet loss for audio and video. I'm not sure whether there is something with the new feature leading to this (it does seem like this starts before you even start receiving video though, which is odd).
* For some reason we are receiving repeated RTP packets on the backend, and I can't figure out why since it seems to be using UDP and I'm pretty sure routers duplicating packets is super rare.

So as far as next steps goes, I would greatly appreciate if you could provide some information and experiment with additional debugging tools enabled :). For questions:
* What kind of network are you connected to? In particular the problematic attendee in `604e199f-fb28-4679-a95b-f6fb5c872713` was `ec7bed4c-8f76-266f-b3b3-a8027b2fa7ab`.
* Are there any possible firewalls on the connection?
* Do the issues reproduce on other networks?
* What device is being used (e.g. 'Macbook Pro')/OS version?
* Do these issues always reproduce? Are the other attendees on the same network?
* When using `AllHighest`, do you ever notice choppy audio or video?

And for experimenting (all would be great, but if you could even manage one it would help), next time you reproduce can you:

### Enable Verbose Browser Logs

Chrome has a [detailed help article with platform specific instructions](https://support.google.com/chrome/a/answer/6271282?hl=en#zippy=).

On MacOS this will look like:
```
open -a Google\ Chrome --args --enable-logging "--vmodule=*/webrtc/*=1"
```
On MacOS will usually be saved in `~/Library/Application\ Support/Google/Chrome/chrome_debug.log` though it is dependent on your [User Data Directory.](https://chromium.googlesource.com/chromium/src/+/master/docs/user_data_dir.md)

### Start RTC Event Log on Chrome

1. Open the page: [chrome://webrtc-internals](http://chrome//webrtc-internals)
2. Click on the Create diagnostic packet recordings dropdown in the top left corner
3. Check the box next to:"Enable diagnostic packet and event recording"
4. Choose a file location and name to save the logging. Now every new webrtc connection made will log to that file.
![Screenshot 2023-10-06 at 12 19 05 PM](https://github.com/aws/amazon-chime-sdk-js/assets/36210679/3c29b160-fcfe-4c1a-8d33-d5d7250a35a2)

### Packet captures
If you are comfortable, familiar with [wireshark](https://www.wireshark.org/) or other packet capture tools please provide a packet capture that filters to just traffic to Chime servers. This is not critical though and it can be tricky to ensure it is listening on the right interfaces and that it filters out non-Chime traffic.

**Comment by hensmi-amazon** [comment]
Going to resolve this due to age, please reopen if you still see issues.
