### ISSUE TITLE
Error on joining Video Room on Google Chrome Mobile Android

### ISSUE THREAD

**Issue by mmmaxi** [aws/amazon-chime-sdk-js#276]
**Describe the bug**
When joining a meeting with a Huawei Phone on the latest Google Chrome Version the attendee is not able to join and sees the following image a video response. The Graphic is coming from the AWS Cloud Video stream. Can you explain to me what this means since the browser is in the latest version of chrome mobile.

**Screenshots**
![Image Error](https://user-images.githubusercontent.com/31849433/79463042-9d8b7200-7ff8-11ea-96a1-27daefe63cf7.jpeg)

**Platform**
 - OS: Android 10
 - Browser: Google Chrome 81.0.4044.96
 - Amazon Chime SDK GitHub Commit: f8c345b

**Comment by KevinVonJocoon** [comment]
Same issue on an old testing device, as we had some feedback coming in from various Android device users.

- Device: Samsung Galaxy Tab 3 (GT-P5210)
- OS: Android 4.4.2 (yeah I know...)
- Browser: Google Chrome 80.0.3987.162 (identical issue with an old version < 78, but additional JS warnings)
- amazon-chime-sdk-js@1.2.1

**Comment by mmmaxi** [comment]
@KevinVonJocoon did you ever find a reason or description behind this mysterious error message, why this is happening?

**Comment by mikeantonelli** [comment]
This might be the error message displayed when the chipset on the device isn’t capable of H264 encoding.

**Comment by KevinVonJocoon** [comment]
@mmmaxi @mikeantonelli I also thought of that, but I suppose mmaxi's Android 10 device is a newer one which should support it - and as far as I can see, the old device I used for testing should also be capable of decoding it.
Another thought: there were several Android security-related CVEs/bugs in media-related OS components which might restrict or even crash these? It might even be some kind of protocol incompatibility due to SSL/TLS changes.

I had my device attached to **adb** and just watched what was happening in the broken session. There was no JS or browser error in the Chrome Dev Tools console, but there was this typical ping-pong mute-unmute thing happening when something went wrong during video stream initialization/binding.

Just to make sure: what strategy of video element binding are you using?
I had to add _playsinline_ for iOS devices to work correctly (e.g. `<video id="..." playsinline />`). I don't expect this to have a negative effect, as it works on other Android devices. 

@mmmaxi What's your Android 10 device manufacturer/product? What kind of JS Framework/Toolchain are you using? We're using Vue+Webpack (so a pretty fresh implementation without any example available).

**Comment by isaiasfsilva** [comment]
Hello everyone,

I've experimented the same issue testing the demo "browser/meetingV2" on Android systems. When users in laptops try to connect, everything works fine. However, when an android user tries to connect, the input and output audio are fine but the video input does not work. Some important information:

- The android user can see the other's video normally;
- The android user cannot even see the preview of the camera before getting in the meeting; The laptops's users can see that an android user is connected (audio works fine), but no video is shown.
- Tested with last version of Google Chrome, Mozilla Firefox and native browser on Android 9 (MIUI 11 - Xiaomi Redmi Note 6 Pro).
- Looking the  site's settings, the audio and video permissions are allowed on android client.
- On Google Chrome no message is given; On mozilla, the image "update your client to support recent video improvements" is shown.

I'm not sure about the problem. I'll stay connected here and follow the updates.

Thanks a lot.

**Comment by KevinVonJocoon** [comment]
If you didn't watch the other issues on this particular subject, we have some stuff happening here.
https://github.com/aws/amazon-chime-sdk-js/issues/299 also mentions this problem and the reason (Chipsets don't support native H.264 decoding or manufacturer doesn't have the license to use it).

https://github.com/aws/amazon-chime-sdk-js/issues/289 mentions the current "_workaround_" - or at least source of notification for this case. Especially https://github.com/aws/amazon-chime-sdk-js/issues/289#issuecomment-616878236

In short, what I'd do right now:
Query browser capabilities for video codec support and display an error message.
As far as AWS does not extend Chime to support codec fallbacks, we won't get this working from here, let alone WebRTC being ready for this kind of codec-switching stuff.

As far as I can see based on my research, there are chipsets out there capable of decoding H.264 in HW but Google decided to block usage due to bad performance. It is trivial to see software-based decoding is a bad idea for real-time mobile video conferencing as an alternative.

**Comment by yixial-amzn** [comment]
We recently made some fix for this. Could you please let us know if you still see this issue? Thank you very much.

**Comment by yixial-amzn** [comment]
Please open new ticket if there is still issue. Thanks.
