### ISSUE TITLE
Fails to build on Windows 10

### ISSUE THREAD

**Issue by HaydenFaulkner** [aws/amazon-chime-sdk-js#2779]
### What happened and what did you expect to happen?

upon running the initial `npm run build`, the process fails on:

```cmd
'.' is not recognized as an internal or external command,
operable program or batch file.

Error: Command failed: ./node_modules/typescript/bin/tsc --build config/tsconfig.red.json
'.' is not recognized as an internal or external command,
operable program or batch file.
```

Attempted on Windows 10 (OS build 19045.3570). Tried building on Linux system and builds as expected.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Run `npm run build` in `amazon-chime-sdk-js-main`

### Amazon Chime SDK for JavaScript version

NA

### What browsers are you seeing the problem on?

NA

### Browser version

NA

### Browser console logs

NA

**Comment by andrii-hrytsyshyn** [comment]
@HaydenFaulkner  I have the same problem. Do you know how to fix it?

**Comment by HaydenFaulkner** [comment]
Used Linux instead of Windows

**Comment by tkulis** [comment]
Any news here?

**Comment by andrii-hrytsyshyn** [comment]
@tkulis  No, I started working on Mac. Everything works fine there

**Comment by burnhamrobertp** [comment]
This can be done with some extra work that I pieced together from other (similar) issues. The root of the problem stems from the `generate-red-worker-code` file's attempt to run the relatively pathed call to `tsc`.

1. Navigate to amazon-chime-sdk-js root directory, run `node script/barrelize.js && node script/generate-version.js`
2. Edit `generate-red-worker-code.js` and comment out the line `runCommandWithLogs('./node_modules/typescript/bin/tsc --build config/tsconfig.red.json');`
3. Run `npm run red`
4. Run `./node_modules/typescript/bin/tsc --build config/tsconfig.red.json` to transpile the RedundantAudioEncoder (since we commented it out in step #2 to keep it from erroring in step #3)
5. cd into the demos/browser directory
6. run `npm run start`

**Comment by SneakyTurtle20** [comment]
Any news on this one working in windows? I have ran into this error as well.

**Comment by rlu-xseed** [comment]
Try removing the path in line 42. Change from:
`runCommandWithLogs('./node_modules/typescript/bin/tsc --build config/tsconfig.red.json');`
to:
`runCommandWithLogs('tsc --build config/tsconfig.red.json');`

 and in line 53 address the CR. Change from:
\`.replace(/"/g, '\'').replace(/\n/g, "\\n")
to:
\`.replace(/"/g, '\'').replace(/\n/g, "\\n").replace(/\r/g, "")
