### ISSUE TITLE
Issue with screen Share

### ISSUE THREAD

**Issue by koni-a** [aws/amazon-chime-sdk-js#293]
When we are sharing My meetings active screen it is generating infinite windows, Please check below image.

![Screen](https://user-images.githubusercontent.com/56219917/79872208-1fb5d500-8403-11ea-9a6a-47aaf8e5dd14.PNG)

Can you please help us to resolve this issue

Thanks
Koni

**Comment by simmkyu** [comment]
It's an expected behavior if you have shared the entire screen or the browser window displaying your own screen share. One solution is to hide the screen share from your app while sharing your screen. i.e. Display other's screen only.

We are implementing this solution using the content share in the demo v2. Note that you are running the v1 legacy screen sharing. Could you try again after appending `/v2` to your demo app's URL? e.g. `/Prod/v2`.

Please see [Screen and content share ](https://github.com/aws/amazon-chime-sdk-js#screen-and-content-share) for more information.

**Comment by koni-a** [comment]
I have tried with V2 also it is giving the same issue.

Please check below image

![image](https://user-images.githubusercontent.com/56219917/79939213-26ccf980-847c-11ea-8b41-3e974025c3b8.png)

**Comment by simmkyu** [comment]
In the attached screenshot, you are using one monitor for two attendees:
- Attendee 1: *Mohan* is sharing screen.
   -> If you open the *Mohan*'s browser window (or tab), you will not see the shared screen. This is what we've fixed in the demo V2.

- Attendee 2: *Koni* is viewing *Mohan*'s screen
   -> If you open the *Koni*'s browser window (or tab), you will see *Mohan*'s screen, sharing your computer's entire screen. It will generate infinite windows.
  
  In a browser, Chime SDK uses MediaDevices APIs for screen sharing. Infinite windows in the screen share is an expected behavior.
  https://developer.mozilla.org/en-US/docs/Web/API/Screen_Capture_API/Using_Screen_Capture

  To avoid this effect, let *Koni* join the same meeting from another computer. *Koni* will see *Mohan*'s entire screen without the effect.

**Comment by simmkyu** [comment]
Closing this issue as it's not an SDK issue. Please try out the demo V2 in two different computers.

**Comment by ekpono** [comment]
I am having this same issue.
