### ISSUE TITLE
#ask is it possible to use SDK without add Credit card to my account

### ISSUE THREAD

**Issue by mhanifahns** [aws/amazon-chime-sdk-js#300]
iam trying to checkout the demo here but the response ask me to input the credential .

server caught error: CredentialsError: Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1

 is it possible to use this SDK without add credit card to my account ?

**Comment by aburnson** [comment]
To build and run the demos you will need a billable AWS account and to [configure AWS credentials](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html) for an IAM role with the [AmazonChimeSDK policy](https://console.aws.amazon.com/iam/home?#/policies/arn%3Aaws%3Aiam%3A%3Aaws%3Apolicy%2FAmazonChimeSDK) attached.

Adding documentation tag, since this could be clearer in the demo READMEs.
