### ISSUE TITLE
videoStreamContentWidth and videoStreamContentHeight not provided for remote video tiles

### ISSUE THREAD

**Issue by jeffmerten** [aws/amazon-chime-sdk-js#309]
**Meeting and attendee IDs:**
N/A

**Timeline**
Outline the main actions the user performed and when:
Started the demo app  `meetingV2` and turned on the video for my own user. From another tab I joined as a new user in the same meeting.

**Describe the bug**
Any video tile for a participant does not include `videoStreamContentWidth` or `videoStreamContentHeight` from the observer callback `videoTileDidUpdate`. This is in contrast to the local video tile which does includes this information. The remote video tile does include `videoElementCSSHeightPixels`, `videoElementCSSWidthPixels`, `videoElementPhysicalHeightPixels`, and `videoElementPhysicalWidthPixels`. 

Also worth noting is those attributes on remote video tile that we do see seem to get hidden in our react implementation unless we bind our video tile when it's visible, although we do not need that information as it seems to be reflective of the video tile container height/width and not the height/width of the video content.

**Screenshots**
Local video tile
<img width="546" alt="Local video tile" src="https://user-images.githubusercontent.com/34603098/80599503-43bb7c80-89e8-11ea-9d23-537a9bd29868.png">

Remote video tile
<img width="604" alt="Remote video tile" src="https://user-images.githubusercontent.com/34603098/80599506-45854000-89e8-11ea-81f9-92fadd1426b4.png">

**Platform**
 - OS: MacOS
 - Browser: Chrome
 - Browser Version: 81
 - Amazon Chime SDK GitHub Commit: 1.4.0

**Comment by RidipDe** [comment]
We found that at the time when track.getSettings() is called when a video track is added for the first time, the values for videoStreamContentWidth and videoStreamContentHeight are undefined. Every subsequent calls to the track.getSettings() has the videoStreamContentWidth and videoStreamContentHeight. To mitigate this issue we tried to delay the call to the track.getSettings(). It seemed to work fine for Chrome. We then tested the behavior on different browsers and it turned out that different browsers had different response to the delay in the call to the method track.getSettings(). The videoStreamContentWidth and videoStreamContentHeight remained undefined for firefox.

To mitigate getting letterboxed video tiles while not knowing the dimensions of the incoming video, we can apply the following CSS rule to the HTML element that will contain the video: _object-fit: cover;._ 

This will ensure that the video, no matter what its' dimensions are, will always fit the container.

**Comment by jeffmerten** [comment]
I think I saw similar behavior in Firefox with a work around solution where I attached an event listener on the video element and noticed the video input height and width were undefined initially. We ended up going with `object-fit:cover` as our solution, so we don't need this information at the moment.
