### ISSUE TITLE
Unable to get Helpdesk demo to work 

### ISSUE THREAD

**Issue by yahoolane** [aws/amazon-chime-sdk-js#330]
I am following the steps for the Videohelpdesk demo 
I am on us-1 East 
I am logged in as root user 

I followed the instructions 
I see the build working 
I deploy the Lambda, its on the right side of the cloud9 

When I go test it on the gateway 
the Invoke URL 
I get 
{"message": "Internal server error"}
when I add /helpdesk I also get this error. 

https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/videohelpdesk

**Comment by pemmerich** [comment]
I had the same issue, which was related to the UUID module. The declaration has changed since this code was written, so if you're using the latest library you have to declare it like this:
const { v4: uuidv4 } = require('uuid');
rather than:
const uuidv4 = require('uuid/v4');
in handlers.js
Hope this helps.

**Comment by anuranduttaroy** [comment]
The `uuidv4` import issue was fixed with https://github.com/aws/amazon-chime-sdk-js/pull/515. @yahoolane can you confirm you are still seeing this issue?
