### ISSUE TITLE
Requesting Desktop Control 

### ISSUE THREAD

**Issue by w3villa** [aws/amazon-chime-sdk-js#339]
Amazon Chime does have Requesting Desktop Control  https://docs.aws.amazon.com/chime/latest/ug/remote-control.html

I do not see any documentation for the same. Is the JS SDK capable of same?

**Comment by simmkyu** [comment]
Chime SDK doesn't support the "Requesting Desktop Control" feature.

Since 1.6.0, we added data message APIs ([See changelog](https://github.com/aws/amazon-chime-sdk-js/blob/master/CHANGELOG.md#160---2020-05-15)). You might want to use data message APIs to build remote controls, such as muting and unmuting remotely, but the desktop control is out of scope for JavaScript SDK.
