### ISSUE TITLE
Cannot rejoin a meeting after leaving it (and not ending it)

### ISSUE THREAD

**Issue by paggiorowarda** [aws/amazon-chime-sdk-js#343]
**Describe the bug (Timeline)**
I installed the serverless application.
- At 14:40 I entered a room with name "roomName" correctly: I could activate video etc.
- I left (and not closed) the meeting at 14:42. (for clarity I used the button with the door and the arrow)
- At 15:20 I tryed to re-enter "roomName" meeting but I'm not able to get in. If i try to change the meeting name it works. Why?

When I joined the meeting It inserted a record in the meeting dynamodb table and it is still there.

**Screenshots**
![github_chime](https://user-images.githubusercontent.com/63292100/81181714-2751ae00-8fad-11ea-9d70-cc8e1349bbb0.png)

**Platform**
 - OS: Ubuntu 19.10
 - Browser: Google Chrome
 - Browser Version: 80.0.3987.87
 - Amazon Chime SDK GitHub Commit: #ede11a6

**Comment by ltrung** [comment]
@paggiorowarda This is an expected behavior and not a bug. The meeting will automatically end if:
- No audio connections are present in the meeting for more than five minutes.
- Fewer than two audio connections are present in the meeting for more than 30 minutes.
- Screen share viewer connections are inactive for more than 30 minutes.
- The meeting time exceeds 24 hours.
More details can be found here https://docs.aws.amazon.com/chime/latest/dg/mtgs-sdk-mtgs.html
In your case, you joined the meeting after one hour so it already ended.

**Comment by paggiorowarda** [comment]
@ltrung I didn't seem to have seen all this information in the documentation. In case they weren't there, it would be good to add them!
Thanks
