### ISSUE TITLE
Video Tile Become Lost

### ISSUE THREAD

**Issue by mfharding** [aws/amazon-chime-sdk-js#355]
When users update their video with chooseVideoInputDevice, occasionally a tile will be dropped from state with no way to get it back. The user will still be connected to the audio stream and be able to talk but the video tile will be gone. This is true when observed through meetingSession.audioVideo.getAllVideoTiles() and through keeping a list in tileDidUpdate. 

This issue also occasionally happens on load. Can this issue be fixed? 

Additionally in the short run is it possible to regenerate the list of tiles or access all of the video streams in an object? And/or both. This would be very useful.

**Comment by mfharding** [comment]
Additionally, this issue has been documented by our 1000+ users on virtually every video call of more than 5 people. On Chrome and safari.

**Comment by ltrung** [comment]
@mfharding Do you happen to have any log available when this happened?

**Comment by aburnson** [comment]
Unfortunately, there is not quite enough for us to go on to root cause this. We will need INFO-level logs from a session where the failure occurred in order to investigate this further. If you have a failure example, it would be great if you could re-open here or in a new issue with the [bug report template](https://github.com/aws/amazon-chime-sdk-js/issues/new?assignees=&labels=bug&template=bug-report.md&title=)
