### ISSUE TITLE
How to detect when a meeting attendee is publishing video

### ISSUE THREAD

**Issue by skwny** [aws/amazon-chime-sdk-js#357]
### What are you trying to do?
I would like to detect when a meeting attendee is publishing video.

### How can the documentation be improved to help your use case?
Provide an example of detecting attendee video publishing.

### What documentation have you looked at so far?
https://github.com/aws/amazon-chime-sdk-js

---
I'd like to know if there is a way to detect when a meeting attendee starts/stops publishing their video stream. The current way I'm doing it is as follows:

```
const observer = {
    videoTileDidUpdate: (tileState: VideoTileState) => {
        // Ignore a tile without attendee ID or content share.
      if (!tileState.boundAttendeeId || tileState.isContent) {
          return
      }

      if (tileState.boundVideoStream
        && tileState.boundVideoStream.active
        && tileState.boundExternalUserId
      ) {
        // Video is publishing...
      }
    },

    videoTileWasRemoved: (tileId: number) => {
      // Video is not publishing...
    },
}

this.meetingSession.audioVideo.addObserver(observer)
```

Does this look right? It is working for my use case but I'm not sure if there is some other method that will tell me this. I don't see anything I can subscribe to in the `RealtimeControllerFacade`.

Thanks.

**Comment by vidya-mohan** [comment]
@skwny could you take a look at our ReadMe (usecase 13/14) https://github.com/aws/amazon-chime-sdk-js#video for guidance

**Comment by aburnson** [comment]
@skwny That looks reasonable to me. If you need to observe the exact transition from stopped to started and started to stopped, you may want to remember previously created tileIds in a map since the update can happen when any number of tile properties change not just when it is first started. Issue #219 also asks for a dedicated create callback, which would eliminate the need to keep track of the state yourself. Closing in favor of #219 which is a more permanent fix for this issue.
