### ISSUE TITLE
Update documentation to make more obvious which methods require `await`

### ISSUE THREAD

**Issue by haxxxton** [aws/amazon-chime-sdk-js#371]
### What are you trying to do?

*When building an application that leverages the js Chime SDK, i want to be able to identify which methods need to be `await`ed in my code*

### How can the documentation be improved to help your use case?

*Add some kind of identifier that flags a method as being asynchronous*

### What documentation have you looked at so far?

*Amazon Chime SDK Developer Guide*

**Comment by aburnson** [comment]
Have you taken a look at the [Amazon Chime SDK for JavaScript Documentation](https://aws.github.io/amazon-chime-sdk-js/)? On that page you can quickly search for any object's method and determine the types of its parameters and returns (including whether or not it returns a `Promise`, i.e. can be used with `await`). In particular the page on the [AudioVideoFacade](https://aws.github.io/amazon-chime-sdk-js/interfaces/audiovideofacade.html) lists most of the methods you use when working with the SDK.

If you are asking for some type of built-in naming convention, that will have to wait until a future major version release of the library since that would be a backwards-incompatible change.

Closing for now as I don't think there is anything that needs to change at the moment. Feel free to re-open if there is something more to your request I am missing.
