### ISSUE TITLE
Videotile not reliable: No transition found from NotConnected with Update

### ISSUE THREAD

**Issue by JannikSt** [aws/amazon-chime-sdk-js#410]
When joining the meeting, I sometimes experience that my own video is not shown, even though the video is connected properly. Othertimes everything works out perfectly and my video shows once I join a meeting. 

The difference in the log is the following entry that only shows up in testcases, when my own video does not appear: 
`SDK - no transition found from NotConnected with Update`  

Once I deactivate and reactivate my camera, the video reappears in these cases. 

Can someone explain what the warning means and how to resolve this issue? 

Thanks! 

**Platform**
 - OS: Mac OSX
 - Browser: Firefox 
 - Browser Version: 76 
 - Amazon Chime SDK GitHub Commit: 812f3b2

**Comment by ltrung** [comment]
That message seems to indicate that the video is started before the session finishes connecting. Since it works for you sometimes and not the other, it seems like a race condition. 
Could you provide a full logs when it works and when it does not work?

**Comment by aburnson** [comment]
The SDK could do a better job of handling the case where video is enabled during connection. It should probably throw if the client attempts to `startLocalVideo` without an active session rather than sometimes working and sometimes not working due to asynchronous effects.

**Comment by rohit0337** [comment]
when someone using mobile browser someone video tile portrait size increasing ,how to manage

**Comment by vidya-mohan** [comment]
@rohit0337 is your question particular to rendering? If so thats may be different than the original question - you can find guidance here: https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html#how-can-i-create-a-video-tile-layout-for-my-application

**Comment by kaaaren** [comment]
The warning `no transition found from NotConnected with Update` indicates it tries  perform an update action on NotConnected state. It's likely that the client attempts to start a local video before the meeting session gets started.

It could happen when `meetingSession.audioVideo.startLocalVideoTile()` is called before meeting session is started (`audioVideoDidStart` is the callback where the session starts and occurs when the audio-video session finishes connecting)

It also happens when SDK gets disconnected for some reason when the client wants to start local video.

Hope this helps.

**Comment by triplrrr** [comment]
I am experiencing a similar issue except that my video hasn't started a single time. The line `meetingSession.audioVideo.startLocalVideoTile()` is called at the very end of my code, so I don't understand how this could be the case. Full code below. 

```javascript
import {
  ConsoleLogger,
  DefaultDeviceController,
  DefaultMeetingSession,
  LogLevel,
  MeetingSessionConfiguration
} from 'amazon-chime-sdk-js';
(async () => {
  const logger = new ConsoleLogger('MyLogger', LogLevel.INFO);
  const deviceController = new DefaultDeviceController(logger);
  // You need responses from server-side Chime API. See below for details.
  const meetingResponse = data.meeting;
  const attendeeResponse = data.attendee;
  const configuration = new MeetingSessionConfiguration(meetingResponse, attendeeResponse);
  // In the usage examples below, you will use this meetingSession object.
  const meetingSession = new DefaultMeetingSession(
    configuration,
    logger,
    deviceController
  );
  const videoElement = document.createElement('video');
  document.getElementsByTagName('main')[0].appendChild(videoElement);
  // Make sure you have chosen your camera. In this use case, you will choose the first device.
  const videoInputDevices = await meetingSession.audioVideo.listVideoInputDevices();
  // The camera LED light will turn on indicating that it is now capturing.
  // See the "Device" section for details.
  await meetingSession.audioVideo.chooseVideoInputDevice(videoInputDevices[0].deviceId);
  const observer = {
    // videoTileDidUpdate is called whenever a new tile is created or tileState changes.
    videoTileDidUpdate: tileState => {
      // Ignore a tile without attendee ID and other attendee's tile.
      if (!tileState.boundAttendeeId || !tileState.localTile) {
        return;
      }
      meetingSession.audioVideo.bindVideoElement(tileState.tileId, videoElement);
    }
  };
  meetingSession.audioVideo.addObserver(observer);
  meetingSession.audioVideo.startLocalVideoTile();
})();
```

**Comment by kaaaren** [comment]
Hi @triplrrr thanks for posting questions. It looks you haven't start the meeting session (`meetingSession.audioVideo.start()`) before displaying the video. You can check the [API overview](https://aws.github.io/amazon-chime-sdk-js/modules/apioverview.html) on how to create meeting with audio and video. 

Hope this helps1

**Comment by kaaaren** [comment]
Closing the issue for now.

**Comment by triplrrr** [comment]
Really? Dang. Well then, instead of complaining about a bug that doesn't exist for me, I'll complain about something else.

I could've realized that sooner if the documentation in the readme wasn't terrible, or if there were just some minimal code examples _somewhere_. The use cases are good at outlining the code, but not explaining it. 

There needs to be some serious work on documentation if this library is to be taken seriously. I'd be happy to write some short examples or create a setup guide if y'all'd let me, but I kinda wish it was already there.
