### ISSUE TITLE
Does AWS Chime JS SDK support mobile browsers?

### ISSUE THREAD

**Issue by HirdayGupta** [aws/amazon-chime-sdk-js#426]
### What are you trying to do?

I want to use the Chime JS SDK to allow users to join meetings from their mobile browsers - Safari for iOS and Chrome for Android.

### How can the documentation be improved to help your use case?

The docs linked below indicate that the JS SDK only supports web browsers on MacOS, Windows, Ubuntu, etc. They make no mention of mobile browsers. Yet I see some issues (#423, #372 etc) referencing mobile browsers and getting support - which leads me to believe that Chime JS SDK does support mobile browsers. Would love clarity on this! Does Chime JS SDK support mobile browsers? This can make or break my decision to use Chime.

### What documentation have you looked at so far?

1. README.MD 
2. https://docs.aws.amazon.com/chime/latest/dg/meetings-sdk.html#mtg-browsers

**Comment by aburnson** [comment]
Thanks for your question @HirdayGupta. We have received a lot of feedback asking for mobile browser support. Mobile browsers are challenging to support since some aspects of WebRTC, device management, and echo cancellation are more constrained on these platforms. Additionally, some behaviors we have seen or have been reported appear to be device specific. As it stands today, the Amazon Chime SDK for JavaScript is functional for audio and video on iOS Safari and Android Chrome for a wide range of devices. We are working to identify which device and browser versions are supported, known issues, and mitigations. We will update this issue and the documentation when we have more information on official support. In the meantime, we encourage you to try it out and let us know your experience.

**Comment by vidya-mohan** [comment]
@HirdayGupta we have launched support for 2 mobile browser versions Chrome/Android + Safari/iOS. https://docs.aws.amazon.com/chime/latest/dg/meetings-sdk.html#mtg-browsers
