### ISSUE TITLE
List meeting attendees

### ISSUE THREAD

**Issue by skwny** [aws/amazon-chime-sdk-js#432]
Is it possible to list meeting attendees via the SDK? I've only managed to subscribe to realtime presence. However, it would be useful to be able to capture a static value of an attendee after connecting to a meeting rather than waiting on callbacks.

**Comment by aburnson** [comment]
It is intended that you maintain your own map of present and non-present attendees with any properties you want to assign to them by keeping track of presence changes via the real-time callbacks. Would that work for your use case?

The full roster presence is sent shortly after your audio successfully connects. Due to the design of the backend architecture, this is the earliest you can receive attendee presence from the media backends. You could [ListAttendees](https://docs.aws.amazon.com/chime/latest/APIReference/API_ListAttendees.html) before joining but that will only tell you the attendees that have been created for the meeting, not whether they are presently connected.

**Comment by JDFISHERKING** [comment]
Hi @aburnson, you mentioned that 'the full roster presence is sent shortly after your audio successfully connects.' Where is this full roster presence data found?

**Comment by chuckntaylor** [comment]
Hi @aburnson, you mentioned that 'the full roster presence is sent shortly after your audio successfully connects.' Where is this full roster presence data found?

**Comment by aburnson** [comment]
@chuckntaylor, upon joining each present attendee generates a realtime attendee presence callback. For more information, see: https://aws.github.io/amazon-chime-sdk-js/#attendees.

Also in that [callback](https://aws.github.io/amazon-chime-sdk-js/classes/defaultrealtimecontroller.html#realtimesubscribetoattendeeidpresence) you can inspect the optional [posInFrame](https://aws.github.io/amazon-chime-sdk-js/classes/realtimeattendeepositioninframe.html) argument. This object indicates which attendee out of how many total attendees the update is for. For example, if you were to join on to a call with 3 total attendees, you would get presence callbacks for `attendeeIndex` 0, `attendeeIndex` 1, `attendeeIndex` 2 out of a total `attendeesInFrame` of 3. The first presence update you receive is for all of the present attendees and later presence updates are for individual attendees as they join and leave.

**Comment by chuckntaylor** [comment]
Thank you for the reply. I have been using the `realtimeSubscribeToAttendeeIdPresence`, but it is your clarification of `posInFrame` that helped me. While developing locally, I have been logging it, as I joined with other instances, and so it only showed the `attendeesInFrame` as 1 for each instance. Opening the console on the other instances, I see now as you pointed out that I get an accurate count to start off with, and can keep track from that point on via the callback.
