### ISSUE TITLE
 Cannot read property 'id' of undefined In angular 

### ISSUE THREAD

**Issue by mangalagiri** [aws/amazon-chime-sdk-js#479]
In angular ----------> ERROR TypeError: Cannot read property 'id' of undefined at CreatePeerConnectionTask.push../node_modules/amazon-chime-sdk-js/build/task/CreatePeerConnectionTask.js.CreatePeerConnectionTask.addRemoteVideoTrack (CreatePeerConnectionTask.js:228)

![MadhuLatest](https://user-images.githubusercontent.com/18577663/84617401-6f3cec80-aeec-11ea-92cd-f585a1ee85f3.png)

**Meeting and attendee IDs:**
List the meeting and attendee IDs that the attached logs apply to.

**Timeline**
Outline the main actions the user performed and when:

* <timestamp> <action>
* <timestamp> <action>

**Describe the bug**
Describe the bug and the timestamp at which it happened relative to the timestamp in the log file.

**Screenshots**
If applicable, add screenshots to help explain the problem.

**Platform**
 - OS: Windows 
 - Browser: Chrome 
 - Browser Version:  Version 74.0.3729.108 (Official Build) (64-bit)
 - Amazon Chime SDK GitHub Commit: amazon-chime-sdk-js@1.7.5

**Comment by simmkyu** [comment]
In https://github.com/aws/amazon-chime-sdk-js/issues/482, the attached screenshot shows that the session was connected okay. Are you still getting this `Cannot read property 'id' of undefined` error in your Angular application?

Two previous lines show that both audio and video tracks have valid IDs.

```
[INFO] SDK - received track event: kind=audio id=6af63725-9dbb-4cc0-8453-f332b24c837f label=6af63725-9dbb-4cc0-8453-f332b24c837f
[INFO] SDK - received track event: kind=video id=f033ede5-5848-4a26-b59f-548ce74a8828 label=f033ede5-5848-4a26-b59f-548ce74a8828
```

In the stack trace, the error originated from one of Angular dependencies: `zone-evergreen.js`. `zone-evergreen.js` from *Zone.js* patches web APIs in modern browsers. Have you included *Zone.js* patch for RTCPeerConnection APIs (`webapis-rtc-peer-connection.js`)?

**Comment by dashawk** [comment]
I have the same issue above. I use webpack to bundle my app using `commonjs2` as libraryTarget.

![image](https://user-images.githubusercontent.com/1437205/85377017-149a3500-b56b-11ea-96a3-dc7a8aad50d4.png)

**Comment by dashawk** [comment]
To give you more information, I used the `demos/browser` to test my suspicions.

Before I modify the codes, I tried to join a meeting and I noticed that my camera is not turn on even if I selected it before joining the meeting.
![image](https://user-images.githubusercontent.com/1437205/85378881-ab67f100-b56d-11ea-9014-c1bcd69b6fa2.png)

It turns my camera off after clicking the Join button
![image](https://user-images.githubusercontent.com/1437205/85378983-ca668300-b56d-11ea-8fe0-3594f87de84e.png)

So what I did is edit the `meetingV2.ts` since that is what I used for this example.

In the `meetingV2.ts` inside `videoTileDidUpdate`, I added `console.error('video tile started')`.

and then in the `form-devices` submit function, I added `this.audioVideo.startLocalVideoTile();`
![image](https://user-images.githubusercontent.com/1437205/85379208-174a5980-b56e-11ea-81c9-d06cf4799e5e.png)

Now when I started a new meeting and then tried to join by clicking on the Join button, the error appears as shown below.
![image](https://user-images.githubusercontent.com/1437205/85379385-4d87d900-b56e-11ea-846d-4af432a5f583.png)

**Comment by ltrung** [comment]
@dashawk It is expected since the device preview page is just for users to choose and check their devices. In the demo app, users would need to turn camera manually on.
I followed your modification to the demo app but did not encounter the error though. Could you retry and let me know the steps of your repo?

**Comment by dashawk** [comment]
Hi @ltrung I created a demo video for this issue just to explain everything in detail and to show you how I modified the demo app from the sdk.

Here is the [video link](https://youtu.be/V_XvV1jPZpg) if you could take a look at it.

**Comment by alochbau-amzn** [comment]
It is safe to ignore this error for now.

The TrackEvent is firing after the first WebRTC Offer/Answer due to a Transceiver being automatically created based on the local tile existing which sets a SDP option flag.  The stream is being created shortly after and the TrackEvent will fire again and trigger the correct behavior.

I am working on adjusting the logic so that this TrackEvent does not fire without a Stream.
