### ISSUE TITLE
iOS Safari Browserstack support?

### ISSUE THREAD

**Issue by shanepadgett** [aws/amazon-chime-sdk-js#509]
### What are you trying to do?
I would like to do local development using browserstack iOS Safari. Local development works with all other phones and browsers with the sdk, but with Safari it does not work. You get the following error. `TypeError: undefined is not an object (evaluating 'navigator.mediaDevices.addEventListener')`

### How can the documentation be improved to help your use case?

Include documentation around support offered for browserstack local testing of the chime-sdk-js package and what is supported/not supported for all platforms including mobile.

### What documentation have you looked at so far?

README.md, Amazon Chime SDK Developer Guide, Google

**Comment by simmkyu** [comment]
The media device Web APIs are only available in secure contexts ([Click here to see Web API doc](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia#Privacy_and_security)). In a non-HTTPS host, the Web API `navigator.mediaDevices` is undefined. We have an open issue (https://github.com/aws/amazon-chime-sdk-js/issues/456) for showing a better error message.

The hostname `localhost` is an exception. i.e. In `http://localhost:1234`, `navigator.mediaDevices` exists. Thus, other phones and desktop browsers might be working okay in your local environment because they are using the `localhost` hostname.

1. Could you ensure that BrowserStack is loading your web application under HTTPS or localhost (e.g. `http://localhost:1234`)?
   Note that if BrowserStack is accessing your localhost using IP address or other domain than `localhost`, it won't work.

2. Which version of iOS are you using?
  iOS 10 and lower don't support WebRTC. According to [Amazon Chime SDK system requirements](https://docs.aws.amazon.com/chime/latest/dg/meetings-sdk.html#mtg-browsers), *Chime SDK for JavaScript* doesn't support mobile browsers yet. We'll include the specific iOS and Android versions once we officially support them.

**Comment by shanepadgett** [comment]
> 1. Could you ensure that BrowserStack is loading your web application under HTTPS or localhost (e.g. `http://localhost:1234`)?
For iOS on browserstack, you get redirected to bs-local.com due to safari restrictions. See [here](https://www.browserstack.com/question/759). I have my webpack devserver setup to allow that host and application works well with the exception of this sdk.
>    Note that if BrowserStack is accessing your localhost using IP address or other domain than `localhost`, it won't work.
So I guess this is a no go then.
> 2. Which version of iOS are you using?
iOS 13 on the devices I'm testing with.

**Comment by simmkyu** [comment]
iOS 13 supports WebRTC, so `navigator.mediaDevices` should be available in HTTPS. These are two options for testing:
- If you can load any web URL in BrowserStack iOS Safari, you can host your web application on HTTPS and load it in BrowserStack.
- Browsers are providing an option for enabling MediaDevices API in insecure websites. If you can inspect the iOS Safari using the desktop Safari, you can enable the "Allow Media Capture on Insecure Sites" checkbox.
  <img width="382" alt="Screen Shot 2020-06-24 at 5 25 57 PM" src="https://user-images.githubusercontent.com/36240708/85640129-cdca3f00-b63f-11ea-89aa-f18c15b4c836.png">

  Please follow this WebKit instruction for details.
   https://webkit.org/blog/9454/changing-page-settings-on-ios-using-web-inspector/

**Comment by simmkyu** [comment]
Please try one of those two options and feel free to reopen the issue if it persists.
