### ISSUE TITLE
Remove Entire screen option and keep specific browser screen in "screen picker dialog"

### ISSUE THREAD

**Issue by riteshsc** [aws/amazon-chime-sdk-js#541]
Need help in below scenario
I am using Amazon chime sdk
1. open demo meeting and click on share screen button.
2. it open the screen picker dialog to select the window to share. it includes options like Your Entire Screen, Application Window, or Chrome Tab
3. once we select the one of the screen and share then screen then it will start the screen sharing.

Questions:
1. Is it possible to hide option from Your Entire Screen, Application Window, or Chrome Tab and only user can see chrome tab(other tabs will be hide).
2. if yes, is it possible to hide all tab from browser and keep the one which we need. like only tab containing google will be able to share and other are restricted to share.

**Comment by RidipDe** [comment]
For the screenshare feature in SDK we used getDisplayMedia()
The expected behavior is to open a screen picker dialog and give the users the flexibility to choose the screen share options. It is not possible to hide the options as the behavior is managed by the browser it is running on.
Also from security point of view, the screen share  screen picker dialog will always appear when ever the screen share is toggled on - to get the permission from the user and then initiate the content share only to the specific screen/tab after the user gives the consent.

**Comment by ltrung** [comment]
If you use Electron, you can implement your own screen picker.

**Comment by RidipDe** [comment]
Closing the ticket for now, feel free to open it if the problem still exists
