### ISSUE TITLE
Does the sdk allow for two simultaneous meetings in one browser session?

### ISSUE THREAD

**Issue by jackpmastrangelo** [aws/amazon-chime-sdk-js#559]
### What are you trying to do?

To have a client in two simultaneous chime meetings.

### How can the documentation be improved to help your use case?

From the current documentation this should be possible. I'm getting some bugs that I think are my fault but I just want to confirm I'm not trying something inherently impossible.

### What documentation have you looked at so far?

https://aws.github.io/amazon-chime-sdk-js/index.html

**Comment by simmkyu** [comment]
In one browser window, you can use Chime SDK in multiple tabs, e.g. one meeting per tab. But some browsers will have audio and video issues due to browser/WebRTC limitations. For example, in macOS Safari, if you enable videos in two tabs, the video tile in one tab will go black. This happens even if you turn on video in other WebRTC-based web application.

In one browser tab, you can technically run two meetings at the same time, but we don't recommend that scenario and have no examples of using multiple DefaultMeetingSession objects.

What bugs are you seeing?

**Comment by jackpmastrangelo** [comment]
Thanks for getting back to me @simmkyu!

When I stop the second meetingSession's audioVideo, the first meetingSession stops receiving audio. And the logger gives me a warning that says "MyLogger - reconnection recommended due to: no packets received: true, missed pongs: false, bad audio delay: false". Then Every few seconds the tileState's in my first meetingSession are being replaced, and the logger prints "MyLogger - connection failed with status code: ConnectionHealthReconnect". This just happens on and on forever.

During this whole process, my video is still playing, but I've lost audio.

**Comment by simmkyu** [comment]
Chime SDK logs this message when it fails to receive audio packets and internally attempts to reconnect the session. 

Specifically, SDK analyzes WebRTC statistics ([RTCPeerConnection.getStats](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/getStats)) every one second. In default, SDK will log this message if it doesn't receive audio packets 25 consecutive times, approximately no incoming audio for 25 secs.

```
MyLogger - reconnection recommended due to: no packets received: true, missed pongs: false, bad audio delay: false
```

---

I tried to reproduce it by creating two different `DefaultMeetingSession`s in one Chrome tab and stopping one of them. Another session seems running okay. These are possible reasons.

- **Browser limitaitons**: Two different SDK sessions are still using the same browser APIs incuding device APIs ([MediaDevices.getUserMedia](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia)). When stopping one session, SDK is cleaning up the resources and releasing acquired device streams such as camera and microphone. Stopping one session might release another session's resources.

  One specific example is that macOS Safari (tested on 13.1) allows up to 4 audio context objects. This shouldn't be related to your bug, but due to these kinds of browser limitations, we don't support the scenario for multiple sessions in one tab and have examples.
  ```
  (new webkitAudioContext()).createBufferSource() // Running this 5 times in Safari will fail
  ```

- **Deleted meeting**: Assume two sessions are using the same meeting response from AWS SDK.  When you stop one session, could you ensure that your meeting has not ended?
   
   The meeting will end if you manually delete the meeting via the [DeleteMeeting API](https://docs.aws.amazon.com/chime/latest/APIReference/API_DeleteMeeting.html) in your server application. The meeting will automatically end in one of these conditions (from [this AWS Chime guide](https://docs.aws.amazon.com/chime/latest/dg/mtgs-sdk-mtgs.html))
  - No audio connections are present in the meeting for more than five minutes.
  - Fewer than two audio connections are present in the meeting for more than 30 minutes.
  - Screen share viewer connections are inactive for more than 30 minutes.
  - The meeting time exceeds 24 hours.

- **Shared attendee**: If two sessions are using the same attendee response from AWS SDK, stopping one session will let the Chime server know this attendee leaves a meeting. (But I don't think this is a case. SDK will thorw an error earlier.)

**Comment by simmkyu** [comment]
We recommend running one Chime SDK meeting per browser. Please review the comment above and reopen if you see an issue even with a single meeting.

**Comment by jaltmayerpizzorno** [comment]
I'm looking into writing an application that, while a meeting is in progress, allows a subset of the participants to talk among themselves (muting themselves out of the larger meeting).  Given the issues above, can this be done with Chime? Thank you!

**Comment by kanovic** [comment]
> Chime SDK logs this message when it fails to receive audio packets and internally attempts to reconnect the session.
> 
> Specifically, SDK analyzes WebRTC statistics ([RTCPeerConnection.getStats](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/getStats)) every one second. In default, SDK will log this message if it doesn't receive audio packets 25 consecutive times, approximately no incoming audio for 25 secs.
> 
> ```
> MyLogger - reconnection recommended due to: no packets received: true, missed pongs: false, bad audio delay: false
> ```
> 
> I tried to reproduce it by creating two different `DefaultMeetingSession`s in one Chrome tab and stopping one of them. Another session seems running okay. These are possible reasons.
> 
>     * **Browser limitaitons**: Two different SDK sessions are still using the same browser APIs incuding device APIs ([MediaDevices.getUserMedia](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia)). When stopping one session, SDK is cleaning up the resources and releasing acquired device streams such as camera and microphone. Stopping one session might release another session's resources.
>       One specific example is that macOS Safari (tested on 13.1) allows up to 4 audio context objects. This shouldn't be related to your bug, but due to these kinds of browser limitations, we don't support the scenario for multiple sessions in one tab and have examples.
>       ```
>       (new webkitAudioContext()).createBufferSource() // Running this 5 times in Safari will fail
>       ```
> 
>     * **Deleted meeting**: Assume two sessions are using the same meeting response from AWS SDK.  When you stop one session, could you ensure that your meeting has not ended?
>       The meeting will end if you manually delete the meeting via the [DeleteMeeting API](https://docs.aws.amazon.com/chime/latest/APIReference/API_DeleteMeeting.html) in your server application. The meeting will automatically end in one of these conditions (from [this AWS Chime guide](https://docs.aws.amazon.com/chime/latest/dg/mtgs-sdk-mtgs.html))
>       
>       * No audio connections are present in the meeting for more than five minutes.
>       * Fewer than two audio connections are present in the meeting for more than 30 minutes.
>       * Screen share viewer connections are inactive for more than 30 minutes.
>       * The meeting time exceeds 24 hours.
> 
>     * **Shared attendee**: If two sessions are using the same attendee response from AWS SDK, stopping one session will let the Chime server know this attendee leaves a meeting. (But I don't think this is a case. SDK will thorw an error earlier.)

Can you share your code for setting up two DefaultMeetingSessions in one tab? I am experimenting with this.
