### ISSUE TITLE
Expose error message from getUserMedia()

### ISSUE THREAD

**Issue by ileccese** [aws/amazon-chime-sdk-js#560]
in DefaultDeviceController.chooseInputDevice(), if the call to getUserMedia() throws an exception, that error message is logged and `PermissionDeniedByBrowser` or `PermissionDeniedByUser` is returned. 

```javascript
  catch (error) {
      this.logger.error(
        `failed to get ${kind} device for constraints ${JSON.stringify(proposedConstraints)}: ${
          error.message
        }`
      );
      return Date.now() - startTimeMs <
        DefaultDeviceController.permissionDeniedOriginDetectionThresholdMs
        ? DevicePermission.PermissionDeniedByBrowser
        : DevicePermission.PermissionDeniedByUser;
    }
```

There are several different situations which could cause getUserMedia to throw an error and `PermissionDeniedByBrowser` or `PermissionDeniedByUser` are usually not accurate or descriptive enough. Therefore, it would be helpful to receive the error message (or something that describes this specific error) from getUserMedia in the response. 

For example, if I receive the error message `The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission` then I know that the browser permissions are blocking the device and I can show the user browser permissions instructions whereas if the error message is `The I/O read operation failed` then I know there's a different problem and I won't show the user browser permissions instructions.

**Comment by anuranduttaroy** [comment]
amazon-chime-sdk-js v2.0.0 introduces new error types which will be thrown in case of any failures in `chooseAudioInputDevice` and `chooseVideoInputDevice` APIs in the `DeviceController`. You can read more about it here: [Introducing the `GetUserMediaError` type](https://aws.github.io/amazon-chime-sdk-js/modules/migrationto_2_0.html#introducing-the-getusermediaerror-type)

Also, for introducing this change, we had to modify the API signature of `chooseAudioInputDevice` and `chooseVideoInputDevice` to return `Promise<void>` instead of `DevicePermission`. Read more about this here: [Introducing `AudioInputDevice` and `VideoInputDevice`](https://aws.github.io/amazon-chime-sdk-js/modules/migrationto_2_0.html#introducing-audioinputdevice-and-videoinputdevice)

Hope this resolves your issue. Feel free to re-open if you still have questions.
