### ISSUE TITLE
Screenshare in FF stops updating video if source window is larger than ~2.8 MPixel

### ISSUE THREAD

**Issue by Xarno** [aws/amazon-chime-sdk-js#570]
[Chime Log.txt](https://github.com/aws/amazon-chime-sdk-js/files/4947719/Chime.Log.txt)

**Meeting and attendee IDs:**
Dont have them recorded

**Timeline**
Outline the main actions the user performed and when:
Browser Chrome: Join Meeting, wait
Browser FF: Join Meeting, Start screenshare, Share one aplication Window
Browser FF: Resize Aplication Window, see changes mirroed in Chrome window
Browser FF: Reach some limit, see no more changes
Browser FF: Resize Aplication Window a bit smaller, see changes again

**Describe the bug**
On Firefox and on Mac OS the Screenshare has some size limit, which lies around 2.8MPixel. If the Window is larger than that, there are no updates in the video Stream. If the Window is resized below this limit there video resumes.

**Screenshots**
This window was just a bit too large to get transmitted.
<img width="1837" alt="Bildschirmfoto 2020-07-20 um 14 03 12" src="https://user-images.githubusercontent.com/4302553/87938427-decb6c00-ca96-11ea-8ab1-d609856446c3.png">

**Platform**
 - OS: Mac OS 10.15.6
 - Browser: Firefox 
 - Browser Version: 78.0.2
 - Amazon Chime SDK GitHub Commit: 1.12.0

**Comment by ltrung** [comment]
Could you try to see if you could reproduce this issue in our meeting demo app?
I tried to reproduce it in our meeting demo app but did not see the issue.

**Comment by Xarno** [comment]
I could reproduce it on the Meeting demo app.
It happened with a rather large window. And I have generally set the os zoom to minimum:
<img width="874" alt="Bildschirmfoto 2020-07-23 um 10 20 20" src="https://user-images.githubusercontent.com/4302553/88265619-1ec86400-ccce-11ea-99c0-353da96f2642.png">

I needed to change the video css to object-fit: contain; otherwise it would clip.
[firefox_log.txt](https://github.com/aws/amazon-chime-sdk-js/files/4964488/firefox_log.txt)
[chrome_log.txt](https://github.com/aws/amazon-chime-sdk-js/files/4964489/chrome_log.txt)

Video of the testsetup:
http://public.corussoft.de.s3.amazonaws.com/ChimeSDK%20%23570%20screencapture.mov

Amazon Chime SDK GitHub Commit: a4ee269d18b2f796494b38b436e467ebf9ca5fd3

**Comment by aburnson** [comment]
@Xarno, there is likely some sort of limit either in memory, system capture, the browser MediaStream, or the downscaling the browser does when it attaches the captured MediaStream to the RTCPeerConnection.

Could you try using the following WebRTC demo to see whether a screen share of comparable size renders in the page's video element?

https://webrtc.github.io/samples/src/content/getusermedia/getdisplaymedia/

This will help isolate where the limit might be coming from. However, there may not be much that the SDK client can do to address this issue from JavaScript depending on where the limit is.

In the test I did with the above demo, on macOS 10.14.6, as I increased the size, Firefox 68.8.0 rendered a black tile and even crashed the capture window host process.

**Comment by Xarno** [comment]
Hello aburnson,
i checked the demo with FF80.0.1, works fine with full desktop and with single window capture.

Mac OS: 10.15.6 (19G2021)
Firefox: 80.0.1 (64 bit)

If I size an aplication window 1 and a half time of my desktop size the capture flickers (switching between normal frame and black frame), but i think this limit is not part of this ticket.

**Comment by aburnson** [comment]
Thanks for testing that out. I was able to reproduce this locally with a horizontally large window (around 1500x7000); however that was much larger in terms of surface area than the 2.8MPixel you have reported. This suggests that there is not necessarily one fixed limit and other factors may go into the limit.

Unfortunately, there is not a whole lot the SDK client can do here. For one, it is not clear at the moment that it is possible to detect that the window is too large since this limit seems to be internal to the browser. I didn't see any obvious sign of the MediaStream being paused when in this state. Second, even if it is possible to detect this situation, it's unclear what can be done about it. I could imagine a fallback scenario where the SDK client attempts to directly copy the screen capture into a smaller-sized canvas and then stream that canvas back out as a properly sized MediaStream. However, this would likely not be performant.

More study, possibly at the browser source level, is needed in order to determine the root cause of where in chain the MediaStream is failing to encode frames.
