### ISSUE TITLE
Failed to load resource: the server responded with a status of 504 

### ISSUE THREAD

**Issue by Jhonsensf** [aws/amazon-chime-sdk-js#625]
**INFO-level log** 

[INFO-level.txt](https://github.com/aws/amazon-chime-sdk-js/files/5073815/INFO-level.txt)

**Describe the bug**
I'm having an issue with safari just in iOS, on safari MacOS is working fine. The problem is when calling the /turn_sessions endpoint:

```jsx
https://ccp.cp.ue1.app.chime.aws/v2/turn_sessions?X-Amzn-Version=1.14.0&X-Amzn-User-Agent=ios-13](https://ccp.cp.ue1.app.chime.aws/v2/turn_sessions?X-Amzn-Version=1.14.0&X-Amzn-User-Agent=ios-13)
```

I'm having a 504 

```jsx
[Error] Failed to load resource: the server responded with a status of 504 (Gateway Timeout) (turn_sessions, line 0)
```

**Screenshots**

![image](https://user-images.githubusercontent.com/20872950/90236930-bc253c80-de23-11ea-8068-5ec87a22b002.png)

**Platform**
 - OS: iOS 13.6
 - Browser: Safari 
 - Browser Version: 13
 - Amazon Chime SDK GitHub Commit: 1.14.0

**Comment by RidipDe** [comment]
Can you please provide us with a repo step using the demo app.

**Comment by simmkyu** [comment]
Fetching TURN credentials has failed with SyntaxError: `The string did not match the expected pattern.` You can find this error code in the MDN Web Doc: https://developer.mozilla.org/en-US/docs/Web/API/DOMError

In [the attached INFO-level.txt](https://github.com/aws/amazon-chime-sdk-js/files/5073815/INFO-level.txt), the warning message contains the error message. SDK logs the warning message per retry attempt.

```
[Warning] 2020-08-14T09:11:34.348Z [WARN] MyLogger - ... ReceiveTURNCredentialsTask failed: The string did not match the expected pattern.
```

---

From https://github.com/getsentry/sentry-javascript/issues/2487#issuecomment-654770612
> So apparently this is the old Safari (notice that events are using iOS 10/11) issue when DOM selector is malformed, see: https://www.reddit.com/r/firefox/comments/5nbmqi/on_handling_invalid_selector_strings/

The SyntaxError might happen due to the malformed DOM selector in older versions of Safari.

We haven't seen this error on iOS 13 Safari. In the attached screenshot, it seems that you are using the polyfill library (`polyfills-es2015...js`). Could you try running the same code without this polyfill library? Optionally, you can deploy [the serverless demo](https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/serverless) and try joining a meeting on your iOS Safari.

**Comment by Jhonsensf** [comment]
I had the same problem with Safari on MacOS. I'm using Ionic/Angular as framework and I've forced the compiler to generate the build only for the latest version of Safari and Safari iOS. This fixed the problem on Safari on MacOS but still happening in Safari on iOS 13.

Looks like I'm having the same issue

```
2020-09-01T16:55:40.705Z [WARN] MyLogger - will retry due to status code TaskFailed and error: serial group task AudioVideoStart/326d3935-af25-4f5a-bb3b-e24487a375d1/fb3daa87-1adf-474f-a084-61012731d146 was canceled due to subtask AudioVideoStart/326d3935-af25-4f5a-bb3b-e24487a375d1/fb3daa87-1adf-474f-a084-61012731d146/Timeout15000ms error: serial group task AudioVideoStart/326d3935-af25-4f5a-bb3b-e24487a375d1/fb3daa87-1adf-474f-a084-61012731d146/Timeout15000ms/Media was canceled due to subtask AudioVideoStart/326d3935-af25-4f5a-bb3b-e24487a375d1/fb3daa87-1adf-474f-a084-61012731d146/Timeout15000ms/Media/Setup error: parallel group task AudioVideoStart/326d3935-af25-4f5a-bb3b-e24487a375d1/fb3daa87-1adf-474f-a084-61012731d146/Timeout15000ms/Media/Setup failed for tasks: task AudioVideoStart/326d3935-af25-4f5a-bb3b-e24487a375d1/fb3daa87-1adf-474f-a084-61012731d146/Timeout15000ms/Media/Setup/ReceiveTURNCredentialsTask failed: The string did not match the expected pattern.
```

Now I'm not using `polyfills-es2015...js`but still using polyfills. 

![image](https://user-images.githubusercontent.com/20872950/91884365-33f9c080-ec86-11ea-9b71-e612c7d1aa36.png)

I don't know if I can build an Ionic/Angular site without polypills but I'll continue investigating.

Thanks

**Comment by devalevenkatesh** [comment]
@Jhonsensf Could you once check if you are successfully able to get the appr.tc to run fine? Or any peer-connection demo example in the official WebRTC samples?
https://webrtc.github.io/samples/ check examples under "RTCPeerConnection".

Please let us know if this is still an issue.

**Comment by jing-chen1** [comment]
Closing it, feel free to reopen if you still have problems.
