### ISSUE TITLE
Trouble getting dominant speaker video in expanded size

### ISSUE THREAD

**Issue by chanuuuu** [aws/amazon-chime-sdk-js#665]
Is there a way to show dominant speaker video in expanded size instead of tile based UI? Our product requires dominant speaker video in bigger size and in-active speakers video in smaller size. At this moment, all we are able to get is tile based UI where each participant is assigned a tile and all tiles are of same size. We would like to provide both speaker view and gallery view (current tiled based view) options to our users.

**Comment by bradmanAWS** [comment]
Hi @chanuuuu, we have a component library built in React which supports this feature. If you are using React, you can import this component directly. Otherwise, you can use this as an example of how to implement this features.

https://github.com/aws/amazon-chime-sdk-component-library-react/blob/master/src/components/ui/VideoGrid/VideoGrid.mdx
