### ISSUE TITLE
Same meeting session in different windows/tabs

### ISSUE THREAD

**Issue by AramAnd** [aws/amazon-chime-sdk-js#667]
### What are you trying to do?
I have Electron.js desktop app environment where I have multiple child windows and one main parent window. From the parent window I am creating the meeting session with the corresponding user and in that window i am showing/connecting the audio. The other user is (not the creator of session) shares the video of the her screen and ii want to show the screenshare content in the child window.

### Problem
I would like to understand the possible ways to connect to the same meeting session object in the creator side and get the screen share content in the child window without creating any unnecessary variables/object/requests. 

Thank you !

**Comment by simmkyu** [comment]
I don't think Electron.js allows child windows to communicate streaming data using the parent window's WebRTC peer connection. If allowed, you can call the content observer method `meetingSession.audioVideo.addContentShareObserver` in a child window and then display the screen content.

The following Stack Overflow answer suggests two approaches for sharing the Electron.js content to another window: `window.open()` and `WebRTC` (not a WebRTC connection established by Chime SDK but local connection).
https://stackoverflow.com/a/46913418

Here's an example using the `window.open()` approach. In your application or Chime SDK demo, replace `__replace_with_your_video_id__` with your `<video>` ID and run this code.

```
var video = document.getElementById('__replace_with_your_video_id__');
var win = window.open();
win.document.write('<canvas id="canvas" style="width:100%;height:100%;"></canvas>');
await new Promise(r => setTimeout(r, 100));
var canvas = win.document.getElementById('canvas');
setInterval(() => {
  canvas.getContext('2d').drawImage(video, 0, 0);
}, 1000 / 30);
```

This code performs:
1. Open a child window with `<canvas>`.
2. Take a snapshot of `<video>` in the parent window and draw it onto `<canvas>` every 33 ms (e.g. 30 fps).


I haven't tested this thoroughly, but this is one approach you can display the parent window's content in a child window.

**Comment by AramAnd** [comment]
@simmkyu thank you for the reply.

1. Unfortunately WebRTC connection will not work for me, as it is becoming slower.
2. Opening new Window might work for me.

On the other hand, i was thinking is there any way that I can create new attendee (or the same one) which will join to the existing meeting and will only show screenshare content, nothing else, no video no audio ?

Looking forward to your reply.

**Comment by ltrung** [comment]
@AramAnd Yes you should be able to join a meeting as an attendee with no audio and video.

**Comment by AramAnd** [comment]
@ltrung Thank you for the reply.

Whenever I am trying to attend to the meeting with the same attendee information (attendee and meeting in MeetingSessionConfiguration ), the previous is being disconnected. Please see below the second window code 

![image](https://user-images.githubusercontent.com/7838312/94156962-bb0b1480-fe91-11ea-9a39-8732d4a8e561.png)

**Comment by simmkyu** [comment]
> Whenever I am trying to attend to the meeting with the same attendee information (attendee and meeting in MeetingSessionConfiguration ), the previous is being disconnected. Please see below the second window code

It's expected behavior. If another attendee joins with the same attendee response, the first attendee's session will be stopped with the `AudioJoinedFromAnotherDevice` status code.

https://github.com/aws/amazon-chime-sdk-js/blob/d96981488fa41f492555ac8d3fa05afcd9ff8de2/src/meetingsession/MeetingSessionStatusCode.ts#L15-L18

⠀

When you create an attendee using one of these AWS SDK APIs, the response contains the join token. The Chime SDK for JavaScript, Android, and iOS uses this token to start a Chime SDK meeting as a unique participant.
- [CreateAttendee API](https://docs.aws.amazon.com/chime/latest/APIReference/API_CreateAttendee.html)
- [CreateMeetingWithAttendees API](https://docs.aws.amazon.com/chime/latest/APIReference/API_CreateMeetingWithAttendees.html)
- [BatchCreateAttendee API](https://docs.aws.amazon.com/chime/latest/APIReference/API_BatchCreateAttendee.html)
