### ISSUE TITLE
Video Call issue in Android Browser

### ISSUE THREAD

**Issue by sidharth-sid** [aws/amazon-chime-sdk-js#769]
The audio is working fine in my android phone browser But I'm not able to see attendee video or share my video and cannot see the screen share of the attendee. It's working perfectly on other android devices. Need to know why it is not working on this mobile specifically though it is having much recent versions and updates.
@aburnson 

Also attaching the error screen I see.
![image](https://user-images.githubusercontent.com/43243364/95485122-ea9c3f80-09ae-11eb-9cef-8b976d23814f.png)

Phone Version Details
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/43243364/95483470-e1aa6e80-09ac-11eb-986d-efb114b60af0.png)

I had gone through the closed issue. https://github.com/aws/amazon-chime-sdk-js/issues/299
But seems the error is still there for some other latest phones

**Comment by albertodam** [comment]
i have same issue with Huawei P20 Lite, Android 9

**Comment by anuranduttaroy** [comment]
This issue seems to be the same one mentioned here in our FAQ: [I see a slate which says "Your client does not support hardware acceleration" when I enable video on my device?](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html#i-see-a-slate-which-says-quotyour-client-does-not-support-hardware-accelerationquot-when-i-enable-video-on-my-device)

Can you take a look at that and let me know if that helps?

**Comment by p-foucht** [comment]
If you still have an issue, feel free to re-open
