### ISSUE TITLE
Unable to hear any audio on either device android demo

### ISSUE THREAD

**Issue by dylanmoo** [aws/amazon-chime-sdk-js#77]
**Logs**
[logs_android_tablet_test.txt](https://github.com/aws/amazon-chime-sdk-js/files/4067288/logs_android_tablet_test.txt)

**Describe the bug**
Describe the bug and the timestamp at which it happened relative to the timestamp in the log file.
I am testing by running the android demo on two android devices: Samsung Tab A and Pixel 3.
Both devices can join the same meeting and see the other device's video feed.
Neither device outputs any audio despite being on full volume, unmuted, and mics on.
I'm wondering how to get audio working and if it's been working at all since the demo was created.

**Platform**
 - OS: Android v9
 - Browser: Chromium
 - Amazon Chime SDK GitHub Commit: Add Android web view demo	3952080	Kyu Simm <simmkyu@amazon.com>	Dec 23, 2019 at 2:59 PM

**Comment by simmkyu** [comment]
@dylanmoo Sorry for the delay. We have not merged the Android demo PR yet because it does support full demo features.

Could you deploy [the browser demo](https://github.com/aws/amazon-chime-sdk-js#deploying-the-serverless-browser-demo) and try opening the output URL in your Android device's browser? The browser demo and the Android demo are using the same underlying SDK. The browser demo supports audio output selection.

<img width="386" alt="Screen Shot 2020-01-23 at 10 11 08 AM" src="https://user-images.githubusercontent.com/36240708/73011237-b3f2aa80-3dc8-11ea-81f2-ebaa6fb1b742.png">

Please let us know if you do not see any audio output option, or a selected output does not work.

**Comment by dylanmoo** [comment]
Thanks for your help @simmkyu. I was able to use the browser demo to open a meeting on my pixel 3 device and transmit audio between the device and a browser. Video is inconsistent from the android client and after joining the meeting, I'm forced back into the camera & microphone selection screen.

I have another device, a Samsung Tab A that gets stuck on a permissions check when trying to join the meeting and select a camera. 

I was hoping to use this sdk in our flutter app to add video/audio calling between android devices, but I'm not confident this is stable enough to use right now.  I'll continue to watch the repository for progress.

**Comment by simmkyu** [comment]
Could you please upload SDK demo logs of Pixel 3 and Samsung Tab A's browsers? It might be a browser issue.

Chime SDK currently supports these desktop browsers (from [Amazon Chime Developer Guide](https://docs.aws.amazon.com/chime/latest/dg/meetings-sdk.html#mtg-browsers)):
- Mozilla Firefox (version 60 and newer), for macOS and Windows
- Google Chrome (version 78 and newer), for macOS and Windows
- Chromium-based Edge (version 79 and newer), for Windows
- Chromium-based Electron (Electron 7 and newer, with Chromium version 78 and newer)

Please keep an eye on the repository and [Amazon Chime Developer Guide](https://docs.aws.amazon.com/chime/latest/dg/meetings-sdk.html#mtg-browsers) where we will post any updates on browser support.
