### ISSUE TITLE
WebSocket connection to failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by colin-shah** [aws/amazon-chime-sdk-js#828]
**Important-Describe the bug:** Some of our users facing issue from last few days . Getting Websocket connection to URL failed. ERR_NAME_NOT_RESOLVED. for me It happens every time it was working well till 23rd October . I have also validate from other device that meeting has not ended and I have attached Info log file.

**Meeting and attendee IDs:**
AttendeeId: 6ad9fb91-8ecc-2b9e-05f2-eba7daebf1e9
MeetingId: 0c72c82e-1486-42eb-aa90-36f427198886

**Screenshots**
If applicable, add screenshots to help explain the problem.
![image](https://user-images.githubusercontent.com/73495765/97909401-24722300-1d6e-11eb-8471-a1159ecb9370.png)

**Platform**
 OS: Windows
 Browser: Chrome, Firefox
 Browser Version: For chrome 86.0.4242.111
 Amazon Chime SDK: 1.20.2
[Untitled.txt](https://github.com/aws/amazon-chime-sdk-js/files/5477495/Untitled.txt)

**Comment by devalevenkatesh** [comment]
Hello @colin-shah,

Sorry for the delayed response.

The Websocket connection failed with `ERR_NAME_NOT_RESOLVED` error which means the DNS was unable to resolve your public IP. This may happen due to firewalls or your network configuration. This is not an issue with the JS SDK. I would suggest you to check the other device's network settings as you said you were able to join the meeting and it was not ended from some other device. I checked the logs for the meeting `0c72c82e-1486-42eb-aa90-36f427198886` and see only one attendee tried to join. You may have tried with other attendees in a different meeting. You can further check what network related settings got changed before and after it stopped working.

Since this does not seem to be an JS SDK issue, I am closing this issue and would request you to open if you are still facing websocket issue even after the network settings have been verified.
