### ISSUE TITLE
I'm trying to show overlay screen which contains the username of the member when the video is turned off

### ISSUE THREAD

**Issue by Anisubhra** [aws/amazon-chime-sdk-js#853]
### What are you trying to do?

We are trying to show  a div block over the video tile when the video is turned off. But the issue happening there is when the video is turned off for a user and turned back on again it switches among those 16 static video elements. Meaning if the video was showing in tile number 1 and we turn it off and turn it on again there's no guarantee it'll bound the video to that previous tile which is tile 1. How can we achieve this feature without having bugs. Please suggest us some options with in-depth technical details.

### How can the documentation be improved to help your use case?

Please provide a bit more in-depth documentation about attendee tile creator, how the tiles and working internally and binding video data to those static 16 video elements provided.

### What documentation have you looked at so far?

Amazon Chime SDK Developer Guide

**Comment by Anisubhra** [comment]
We are trying to show  a div block with the username of the member on it over the video tile when the video is turned off. But the issue happening there is when the video is turned off for a user and turned back on again it switches among those 16 static video elements. Meaning if the video is showing in tile number 1 and we turn it off and turn it on again there's no guarantee it'll bound the video to that previous tile which is tile 1. How can we achieve this feature without having bugs. Please suggest us some options with in-depth technical details.

**Comment by devalevenkatesh** [comment]
Hello @Anisubhra,

We have built a solution in our demo to show `attendeeId` when hovered on the video element / video tile. This is a JS + CSS solution. Since the video `tileId` mapping is changing when you turn on/off your video, we have used a map of the HTML video tile indexes to the SDK's video `tileId` so that we can update the mapping whenever it changes. This mapping update is done under the `videoTileDidUpdate` observer method so that we always keep the mapping correct.

Here are few links which will help you understand how this is done:
> Note: The links are relative and may change as the demo is updated.
1. In our README, under [Video](https://github.com/aws/amazon-chime-sdk-js#video) check use cases 13, 14, 15, 16. Use case 16 specifically speaks about how to handle the video tiles.
2. In our [meeting demo](https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/browser), check [videoTileDidUpdate](https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/browser/app/meetingV2/meetingV2.ts#L1884) which is responsible to acquire the tileIndex from the [DemoTIleOrganizer](https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/browser/app/meetingV2/meetingV2.ts#L51) and [videoTileWasRemoved](https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/browser/app/meetingV2/meetingV2.ts#L1919) to release the mapped index.
3. For the overlay part, we use HTML `div` elements as [siblings](https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/browser/app/meetingV2/meetingV2.html#L338) and use [CSS](https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/browser/app/meetingV2/styleV2.scss#L837) to toggle its display based on the HTML `video` element or its wrapping HTML `div` element.

Please let us know if this helps.
