### ISSUE TITLE
How to tell if a user is streaming? 

### ISSUE THREAD

**Issue by ellismarte** [aws/amazon-chime-sdk-js#926]
if I open another app from my phone & the browser goes in the background, the people viewing my stream see a black screen, I can't seem to find a way to figure out if a user is in a state where they aren't sending video, does this exist? 

I'd like to show a photo if the user's video is not available.

**Comment by bradmanAWS** [comment]
Hi @ellismarte you can find documentation around this issue in the FAQ: https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html#i-notice-that-if-i-turn-on-camera-and-put-the-browsers-in-background-others-in-the-meeting-will-see-black-tile-in-safari-in-ios-and-frozen-tile-in-chrome-in-android-is-this-a-known-issue

In general, you would need to add custom logic to show an image instead of a video tile.

**Comment by bradmanAWS** [comment]
I am closing this issue. Feel free to reopen if you still have questions.
