### ISSUE TITLE
Can I use AWS-SDK v2 in a browser witch unsupported sinkId

### ISSUE THREAD

**Issue by rusicsemenov** [aws/amazon-chime-sdk-js#932]
### What are you trying to do?

I try chooseAudioOutputDevice in a browser without support sinkId, and get an error **"Cannot select audio output device. This browser does not support setSinkId."** 

### How can the documentation be improved to help your use case?

We need more information, do we can use SKD on these browsers. I saw updated information:
`Additionally, if the browser does not support setSinkId() API, the bindAudioDevice() will throw an error with a message 'Cannot select audio output device. This browser does not support setSinkId.' Check https://caniuse.com/?search=setSinkId for the setSinkId browser support.` in a migration instruction.

**Comment by bradmanAWS** [comment]
Hi @rusicsemenov, you can find information about supported browsers here: https://docs.aws.amazon.com/chime/latest/dg/meetings-sdk.html#mtg-browsers and more information in our FAQ section here: https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html

You can read in the FAQ that the setSinkId error does not mean you cannot use the SDK in that browser; it just limits some features like device reselection.

**Comment by bradmanAWS** [comment]
I'll close this issue, but feel free to reopen if you need anything else.

**Comment by rusicsemenov** [comment]
@bradmanAWS Thanks, but I received an error when I try chooseAudioOutput. And no hear a sound.

1. In Safari, I received empy array from `meetingSession.audioVideo.listAudioOutputDevices();` when i use **null**(or default) for deviceId  
2. Try `meetingSession.audioVideo.chooseAudioOutputDevice(null);`  and received `Cannot select audio output device. This browser does not support setSinkId.`

Sorry I can't understand why I can fix it on sdk v2 you wrote 
![image](https://user-images.githubusercontent.com/20163858/101391219-12d3ec00-38d5-11eb-986c-553048860f55.png)

I can show you:
<img width="543" alt="Hagen Test Regular 2020-12-07 22-03-06" src="https://user-images.githubusercontent.com/20163858/101393782-a955dc80-38d8-11eb-8e4d-ccb7f4e78b4e.png">
First on is array of devices `meetingSession.audioVideo.listAudioOutputDevices()`
```js
                console.log('chooseAudioOutputDevice');
                await meetingSession.audioVideo.chooseAudioOutputDevice(
                    this.selectedDevices.audioOutputDevice
                );

                try {
                    console.log('bindAudioElement');
                    await meetingSession.audioVideo.bindAudioElement(
                        document.getElementById('meeting-audio')
                    );
                } catch (e) {
                    console.log('Failed to bindAudioElement', e);
                }
```

Yes, Safari get back an empty array, but in v1.22 this all works perfectly)

**Comment by ellismarte** [comment]
I'm also having the same problem.

**Comment by evandroguedes** [comment]
Same issue here.

**Comment by tommy-superviz** [comment]
Same here.

**Comment by gustavofamorim** [comment]
I'm having similar issue here.
When I call `bindAudioElement` function, this error is trow: `Error: Cannot select audio output device. This browser does not support setSinkId.`. As result I cannot hear other connected attendees.
A similar problem occurs with `meetingV2` demo app, using safari I cannot hear anyone connected in the meeting.
It's important to notice that I'm not choosing audio output using `chooseAudioOutputDevice` when browser doesn't support setSinkId since it will throw an unnecessary error.
Looking in SDK code, it appears to be related to this [code snippet](https://github.com/aws/amazon-chime-sdk-js/blob/ad7440109c919f8977d4d4d35fd200da9de5d115/src/audiomixcontroller/DefaultAudioMixController.ts#L71-L75).

Version details: 
- Chime SDK: 2.2.0
- Safari: 14.0.1 (16610.2.11.51.8)
- MacOS: 11.0.1
- Node: 14.15.0

**Comment by irothschild** [comment]
Does PR #930 fix this issue?

I'm mystified how SDK v2.2.0 was released with Safari not even working with the meetingV2 demo app.

**Comment by rnewman** [comment]
@irothschild the output in the demo app was just logging; the demo app was written to catch the relevant error and log.

A full suite of manual and automated smoke and regression tests are run on all supported platforms (including Safari) prior to every release, and continuously in the form of canaries.

#930 ensures that an error is only thrown if the developer is trying to bind a particular audio output device, which should avoid the need to catch and muffle the error.

**Comment by rnewman** [comment]
@gustavofamorim, @rusicsemenov:

>  but I received an error when I try chooseAudioOutput. And no hear a sound.

This is because you did not guard the call to `chooseAudioOutput` in a check for `this.browserBehavior.supportsSetSinkId()`:

```typescript
                await meetingSession.audioVideo.chooseAudioOutputDevice(
                    this.selectedDevices.audioOutputDevice
                );

                try {
                    console.log('bindAudioElement');
                    await meetingSession.audioVideo.bindAudioElement(
                        document.getElementById('meeting-audio')
```

and so your code is throwing prior to calling `bindAudioElement`.

[You will see that the demo app in the repo has `try..catch` blocks around `chooseAudioOutputDevice` and `bindAudioDevice` calls](https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/browser/app/meetingV2/meetingV2.ts#L1512-L1516), which is the logging that others in this ticket have observed.

If you are using an older version of the demo app as the base for your own code, you are necessarily responsible for keeping it up to date with the infrequent breaking changes that are shipped in major version updates like 2.0. The [migration guide](https://aws.github.io/amazon-chime-sdk-js/modules/migrationto_2_0.html#update-bindaudioelement-bindaudiostream-and-bindaudiodevice-to-return-promiseltvoidgt-instead-of-boolean) gives thorough guidance about these changes.

This logging is expected in 2.2. It will not appear in the demo app in the next release as we have refined the situations in which these methods will throw. I still suggest you guard calls to fallible methods.

> Yes, Safari get back an empty array, but in v1.22 this all works perfectly

The API was changed in 2.0 to make it clear that choosing an output device *failed* in browsers that do not support `setSinkId`. In 1.22 the call returned `false` on failure.

Your experience is evidence that most developers did not check the return value or conditionally call the method; the change to throw was to make it less likely that a builder would deliver an inconsistent user experience as a result of testing only on Chrome.

The change in #930 makes these APIs not throw when calling these APIs without a device, which should minimize spurious error logging.

**Comment by irothschild** [comment]
@rnewman I get the `Cannot select audio output device. This browser does not support setSinkId.` error when I call `meetingSession.audioVideo.bindAudioElement()` on Safari. Not just an error log, it actually throws the exception.

Should I only call `bindAudioElement()` if `browserBehavior.supportsSetSinkId()`? The docs make it seem mandatory to hear audio. The Overview says `To hear audio from the remote attendees, bind the audio output device to an HTMLAudioElement in the DOM`

**Comment by rnewman** [comment]
> @rnewman I get the `Cannot select audio output device. This browser does not support setSinkId.` error when I call `meetingSession.audioVideo.bindAudioElement()` on Safari. Not just an error log, it actually throws the exception.
> 
> Should I only call `bindAudioElement()` if `browserBehavior.supportsSetSinkId()`? The docs make it seem mandatory to hear audio.

You do indeed have to do so. If you need a workaround in the interim, I suggest `try..catch` and muffle the error, as the `meetingV2.ts` demo does. I am investigating to see if any additional changes are needed.

**Comment by rnewman** [comment]
@irothschild, @gustavofamorim, @rusicsemenov: could you confirm whether the current code in `master` reproduces the issues you are seeing? I believe you should be able to change your `package.json` to just `aws/amazon-chime-sdk-js#master` to test.

**Comment by rusicsemenov** [comment]
@rnewman Thanks for your attention.
`try..catch` didn't fix this issue, yes it catch error in `chooseAudioOutputDevice`. I know Safari doesn't support sinkI, and if I check `browserBehavior.supportsSetSinkId()` of course I received false. But participants, who use Safari can't hear any sound. 
![image](https://user-images.githubusercontent.com/20163858/101611433-8e8b8100-3a1a-11eb-9d80-be1ba64e02f9.png)

If you want I can try switch project to test breach, but I think this will should call error with dependency

**Comment by rnewman** [comment]
@rusicsemenov we are unable to reproduce a failure to emit audio in Safari. It is expected in 2.2 that `bindAudioElement` will (incorrectly) throw, but audio output does work in our testing — `bindAudioElement` throws *after* setting `srcObject` on the audio element, and so the `catch` renders that harmless.

Are you able to reproduce the issue in the 2.2.0 demo app? If not, then the issue is presumably somewhere in how your code is calling the SDK. I am happy to take a look if you would like.

**Comment by irothschild** [comment]
@rnewman I can confirm that things are working in Safari (both 13.0.4 on Mac OS and 14 on iPad) in version 2.2 with catching and ignoring the `bindAudioElement` error. (It didn't work on my first test but that seems to have been a transient "no audio" problem that happens with Safari sometimes and is usually resolved by reloading the page.)

**Comment by ellismarte** [comment]
```
If you are using an older version of the demo app as the base for your own code, you are necessarily responsible for keeping it up to date with the infrequent breaking changes that are shipped in major version updates like 2.0. 
```
I'm pretty sure its the breaking changes that are causing everyone's problem. A lot of repos will add to the top of a readme in bold "2.0 BREAKING CHANGES". I think that would have prevented me from upgrading. Also looking at the changelog I didn't see anything about breaking changes.

**Comment by rusicsemenov** [comment]
@irothschild what diviceId did you use in safari? When I try to get the output devices list, safari gets back an empty array.

**Comment by irothschild** [comment]
> @rnewman, @irothschild what diviceId did you use in safari? When I try to get the output devices list, safari gets back an empty array.

@rusicsemenov I do not select an output device in Safari. 

```
if (this.browserBehavior.supportsSetSinkId()) {
   deviceController.chooseAudioOutputDevice(deviceId);
}
```

**Comment by rusicsemenov** [comment]
![image](https://user-images.githubusercontent.com/20163858/101672026-60cc2980-3a66-11eb-9ec6-b0f5026baf21.png)
How you can hear the sound?

**Comment by ltrung** [comment]
@rusicsemenov As mentioned in Use Case 5 in the README, you can call bindAudioElement to bind the audio stream to the audio element in your UI. For browsers that do not support setSinkId, it should choose with the default device.

```
const audioElement = /* HTMLAudioElement object e.g. document.getElementById('audio-element-id') */;
meetingSession.audioVideo.bindAudioElement(audioElement);
```

**Comment by rnewman** [comment]
> @rnewman I can confirm that things are working in Safari (both 13.0.4 on Mac OS and 14 on iPad) in version 2.2 with catching and ignoring the `bindAudioElement` error. (It didn't work on my first test but that seems to have been a transient "no audio" problem that happens with Safari sometimes and is usually resolved by reloading the page.)

Thanks for validating this @irothschild; much appreciated.


@rusicsemenov:

> @rnewman I don't use 2.2.0 demo, I have adapted chime on vuejs, one part of it use chime-sdk.

Yes, I understand that; just hoping to validate that you're not seeing some other issue.

> If you want I can show how I make a new MeetingSession, but this all same as in `meetingv2.ts`

If you're not getting audio output in Safari, then you are doing _something_ different to what `meetingV2.ts` is doing. I would be happy to look at your code.


@ellismarte:

> I'm pretty sure its the breaking changes that are causing everyone's problem. A lot of repos will add to the top of a readme in bold "2.0 BREAKING CHANGES". I think that would have prevented me from upgrading. Also looking at the changelog I didn't see anything about breaking changes.

Thank you for the feedback. We will bear that in mind.

This library follows semver; a major version change indicates breaking changes.

The [migration guide](https://aws.github.io/amazon-chime-sdk-js/modules/migrationto_2_0.html) is linked from the first section of the README, and does address this specific case. We want to make it as straightforward as possible to migrate, because features and improvements will only be delivered in the current major version. I strongly encourage you not to stick with an earlier major version beyond their deprecation period.

**Comment by rusicsemenov** [comment]
I sow you update `meetingv2.ts`, ok. your code:
```js
 async openAudioOutputFromSelection(): Promise<void> {
    if (this.defaultBrowserBehaviour.supportsSetSinkId()) {
      try {
        const audioOutput = document.getElementById('audio-output') as HTMLSelectElement;
        await this.audioVideo.chooseAudioOutputDevice(audioOutput.value);
      } catch (e) {
        this.log('failed to chooseAudioOutputDevice', e);
      }
    }
    const audioMix = document.getElementById('meeting-audio') as HTMLAudioElement;
    try {
      await this.audioVideo.bindAudioElement(audioMix);
    } catch (e) {
      this.log('failed to bindAudioElement', e);
    }
  }
```
I rewrote the code in our project to:
```js

if (this.defaultBrowserBehaviour?.supportsSetSinkId()) {
    try {
        console.log(
            `try chooseAudioOutputDevice, device: ${this.selectedDevices.audioOutputDevice}`
        );
        await meetingSession.audioVideo.chooseAudioOutputDevice(
            this.selectedDevices.audioOutputDevice
        );
    } catch (e) {
        console.log('failed to chooseAudioOutputDevice', e);
    }
}

const audioMix = document.getElementById('meeting-audio');
try {
    console.log(`bind elem`, audioMix);
    await meetingSession.audioVideo.bindAudioElement(audioMix);
} catch (e) {
    console.log('failed to bindAudioElement', e);
}
```
<img width="786" alt="Hagen Test Regular 2020-12-09 22-12-20" src="https://user-images.githubusercontent.com/20163858/101676166-dd153b80-3a6b-11eb-9e78-235d70899fb5.png">

**Comment by rnewman** [comment]
That error is currently expected, and should still result in working audio.

**Comment by rusicsemenov** [comment]
@rnewman  Oh ... my mistake, yes I didn't check. Yes, I have sound after that error. I'm sorry.

**Comment by rnewman** [comment]
Great, thanks for reporting back!

**Comment by rusicsemenov** [comment]
Yes, I checked on iPad, works too. I didn't clear the cache. Close issue.

**Comment by rnewman** [comment]
v2.2.1 was just released which should prevent `bindAudioElement` from throwing in ordinary circumstances.
