### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by ellismarte** [aws/amazon-chime-sdk-js#946]
My users are reporting their fans turning on during calls. I've also noticed high CPU usage. What is the best way to figure out what is causing this?

**Comment by jrowny** [comment]
This is true of most video conferencing software when encoding/decoding video happens on CPU. It can be particularly bad when you've got many video tiles rendering at the same time. I'd ensure that your users have hardware acceleration turned on.

**Comment by p-foucht** [comment]
In addition to @jrowny's comment, you may want to consider profiling your app with the [Chrome performance dev tools](https://developers.google.com/web/tools/chrome-devtools/evaluate-performance) to see what's taking up the majority of processing. But it may end up just being the encoding/decoding cost

**Comment by haofiltered** [comment]
@p-foucht 
We had the same high GPU usage issue on Chorme as well, and this only happens on Chrome, not for firefox or safari.

When there are many video tiles, for example 12, the GPU usage on chrome could goes up to 80%, 90%.
And I did some research on this, I suspected it related with video encode/decode. Is there a way we can config the video encode/decode on the chime side? So that we can use `vp8` or `h264` to test if we can solve the issue. Because we can't ask user to config their chrome settings.
